package scaleway

import "github.com/roman-mazur/cuetf/scaleway/res"

#Terraform: {
	#scalewayPrefix: string
	_#res: "\(#scalewayPrefix)_account_project": res.#scaleway_account_project
	_#res: "\(#scalewayPrefix)_account_ssh_key": res.#scaleway_account_ssh_key
	_#res: "\(#scalewayPrefix)_apple_silicon_runner": res.#scaleway_apple_silicon_runner
	_#res: "\(#scalewayPrefix)_apple_silicon_server": res.#scaleway_apple_silicon_server
	_#res: "\(#scalewayPrefix)_autoscaling_instance_group": res.#scaleway_autoscaling_instance_group
	_#res: "\(#scalewayPrefix)_autoscaling_instance_policy": res.#scaleway_autoscaling_instance_policy
	_#res: "\(#scalewayPrefix)_autoscaling_instance_template": res.#scaleway_autoscaling_instance_template
	_#res: "\(#scalewayPrefix)_baremetal_server": res.#scaleway_baremetal_server
	_#res: "\(#scalewayPrefix)_block_snapshot": res.#scaleway_block_snapshot
	_#res: "\(#scalewayPrefix)_block_volume": res.#scaleway_block_volume
	_#res: "\(#scalewayPrefix)_cockpit_alert_manager": res.#scaleway_cockpit_alert_manager
	_#res: "\(#scalewayPrefix)_cockpit_exporter": res.#scaleway_cockpit_exporter
	_#res: "\(#scalewayPrefix)_cockpit": res.#scaleway_cockpit
	_#res: "\(#scalewayPrefix)_cockpit_grafana_user": res.#scaleway_cockpit_grafana_user
	_#res: "\(#scalewayPrefix)_cockpit_source": res.#scaleway_cockpit_source
	_#res: "\(#scalewayPrefix)_cockpit_token": res.#scaleway_cockpit_token
	_#res: "\(#scalewayPrefix)_container_cron": res.#scaleway_container_cron
	_#res: "\(#scalewayPrefix)_container_domain": res.#scaleway_container_domain
	_#res: "\(#scalewayPrefix)_container": res.#scaleway_container
	_#res: "\(#scalewayPrefix)_container_namespace": res.#scaleway_container_namespace
	_#res: "\(#scalewayPrefix)_container_token": res.#scaleway_container_token
	_#res: "\(#scalewayPrefix)_container_trigger": res.#scaleway_container_trigger
	_#res: "\(#scalewayPrefix)_datawarehouse_database": res.#scaleway_datawarehouse_database
	_#res: "\(#scalewayPrefix)_datawarehouse_deployment": res.#scaleway_datawarehouse_deployment
	_#res: "\(#scalewayPrefix)_datawarehouse_user": res.#scaleway_datawarehouse_user
	_#res: "\(#scalewayPrefix)_domain_record": res.#scaleway_domain_record
	_#res: "\(#scalewayPrefix)_domain_registration": res.#scaleway_domain_registration
	_#res: "\(#scalewayPrefix)_domain_zone": res.#scaleway_domain_zone
	_#res: "\(#scalewayPrefix)_edge_services_backend_stage": res.#scaleway_edge_services_backend_stage
	_#res: "\(#scalewayPrefix)_edge_services_cache_stage": res.#scaleway_edge_services_cache_stage
	_#res: "\(#scalewayPrefix)_edge_services_dns_stage": res.#scaleway_edge_services_dns_stage
	_#res: "\(#scalewayPrefix)_edge_services_head_stage": res.#scaleway_edge_services_head_stage
	_#res: "\(#scalewayPrefix)_edge_services_pipeline": res.#scaleway_edge_services_pipeline
	_#res: "\(#scalewayPrefix)_edge_services_plan": res.#scaleway_edge_services_plan
	_#res: "\(#scalewayPrefix)_edge_services_route_stage": res.#scaleway_edge_services_route_stage
	_#res: "\(#scalewayPrefix)_edge_services_tls_stage": res.#scaleway_edge_services_tls_stage
	_#res: "\(#scalewayPrefix)_edge_services_waf_stage": res.#scaleway_edge_services_waf_stage
	_#res: "\(#scalewayPrefix)_file_filesystem": res.#scaleway_file_filesystem
	_#res: "\(#scalewayPrefix)_flexible_ip": res.#scaleway_flexible_ip
	_#res: "\(#scalewayPrefix)_flexible_ip_mac_address": res.#scaleway_flexible_ip_mac_address
	_#res: "\(#scalewayPrefix)_function_cron": res.#scaleway_function_cron
	_#res: "\(#scalewayPrefix)_function_domain": res.#scaleway_function_domain
	_#res: "\(#scalewayPrefix)_function": res.#scaleway_function
	_#res: "\(#scalewayPrefix)_function_namespace": res.#scaleway_function_namespace
	_#res: "\(#scalewayPrefix)_function_token": res.#scaleway_function_token
	_#res: "\(#scalewayPrefix)_function_trigger": res.#scaleway_function_trigger
	_#res: "\(#scalewayPrefix)_iam_api_key": res.#scaleway_iam_api_key
	_#res: "\(#scalewayPrefix)_iam_application": res.#scaleway_iam_application
	_#res: "\(#scalewayPrefix)_iam_group": res.#scaleway_iam_group
	_#res: "\(#scalewayPrefix)_iam_group_membership": res.#scaleway_iam_group_membership
	_#res: "\(#scalewayPrefix)_iam_policy": res.#scaleway_iam_policy
	_#res: "\(#scalewayPrefix)_iam_saml_certificate": res.#scaleway_iam_saml_certificate
	_#res: "\(#scalewayPrefix)_iam_saml": res.#scaleway_iam_saml
	_#res: "\(#scalewayPrefix)_iam_ssh_key": res.#scaleway_iam_ssh_key
	_#res: "\(#scalewayPrefix)_iam_user": res.#scaleway_iam_user
	_#res: "\(#scalewayPrefix)_inference_deployment": res.#scaleway_inference_deployment
	_#res: "\(#scalewayPrefix)_inference_model": res.#scaleway_inference_model
	_#res: "\(#scalewayPrefix)_instance_image": res.#scaleway_instance_image
	_#res: "\(#scalewayPrefix)_instance_ip": res.#scaleway_instance_ip
	_#res: "\(#scalewayPrefix)_instance_ip_reverse_dns": res.#scaleway_instance_ip_reverse_dns
	_#res: "\(#scalewayPrefix)_instance_placement_group": res.#scaleway_instance_placement_group
	_#res: "\(#scalewayPrefix)_instance_private_nic": res.#scaleway_instance_private_nic
	_#res: "\(#scalewayPrefix)_instance_security_group": res.#scaleway_instance_security_group
	_#res: "\(#scalewayPrefix)_instance_security_group_rules": res.#scaleway_instance_security_group_rules
	_#res: "\(#scalewayPrefix)_instance_server": res.#scaleway_instance_server
	_#res: "\(#scalewayPrefix)_instance_snapshot": res.#scaleway_instance_snapshot
	_#res: "\(#scalewayPrefix)_instance_user_data": res.#scaleway_instance_user_data
	_#res: "\(#scalewayPrefix)_instance_volume": res.#scaleway_instance_volume
	_#res: "\(#scalewayPrefix)_iot_device": res.#scaleway_iot_device
	_#res: "\(#scalewayPrefix)_iot_hub": res.#scaleway_iot_hub
	_#res: "\(#scalewayPrefix)_iot_network": res.#scaleway_iot_network
	_#res: "\(#scalewayPrefix)_iot_route": res.#scaleway_iot_route
	_#res: "\(#scalewayPrefix)_ipam_ip": res.#scaleway_ipam_ip
	_#res: "\(#scalewayPrefix)_ipam_ip_reverse_dns": res.#scaleway_ipam_ip_reverse_dns
	_#res: "\(#scalewayPrefix)_job_definition": res.#scaleway_job_definition
	_#res: "\(#scalewayPrefix)_k8s_acl": res.#scaleway_k8s_acl
	_#res: "\(#scalewayPrefix)_k8s_cluster": res.#scaleway_k8s_cluster
	_#res: "\(#scalewayPrefix)_k8s_pool": res.#scaleway_k8s_pool
	_#res: "\(#scalewayPrefix)_kafka_cluster": res.#scaleway_kafka_cluster
	_#res: "\(#scalewayPrefix)_key_manager_key": res.#scaleway_key_manager_key
	_#res: "\(#scalewayPrefix)_lb_acl": res.#scaleway_lb_acl
	_#res: "\(#scalewayPrefix)_lb_backend": res.#scaleway_lb_backend
	_#res: "\(#scalewayPrefix)_lb_certificate": res.#scaleway_lb_certificate
	_#res: "\(#scalewayPrefix)_lb_frontend": res.#scaleway_lb_frontend
	_#res: "\(#scalewayPrefix)_lb": res.#scaleway_lb
	_#res: "\(#scalewayPrefix)_lb_ip": res.#scaleway_lb_ip
	_#res: "\(#scalewayPrefix)_lb_private_network": res.#scaleway_lb_private_network
	_#res: "\(#scalewayPrefix)_lb_route": res.#scaleway_lb_route
	_#res: "\(#scalewayPrefix)_mnq_nats_account": res.#scaleway_mnq_nats_account
	_#res: "\(#scalewayPrefix)_mnq_nats_credentials": res.#scaleway_mnq_nats_credentials
	_#res: "\(#scalewayPrefix)_mnq_sns_credentials": res.#scaleway_mnq_sns_credentials
	_#res: "\(#scalewayPrefix)_mnq_sns": res.#scaleway_mnq_sns
	_#res: "\(#scalewayPrefix)_mnq_sns_topic": res.#scaleway_mnq_sns_topic
	_#res: "\(#scalewayPrefix)_mnq_sns_topic_subscription": res.#scaleway_mnq_sns_topic_subscription
	_#res: "\(#scalewayPrefix)_mnq_sqs_credentials": res.#scaleway_mnq_sqs_credentials
	_#res: "\(#scalewayPrefix)_mnq_sqs": res.#scaleway_mnq_sqs
	_#res: "\(#scalewayPrefix)_mnq_sqs_queue": res.#scaleway_mnq_sqs_queue
	_#res: "\(#scalewayPrefix)_mongodb_instance": res.#scaleway_mongodb_instance
	_#res: "\(#scalewayPrefix)_mongodb_snapshot": res.#scaleway_mongodb_snapshot
	_#res: "\(#scalewayPrefix)_mongodb_user": res.#scaleway_mongodb_user
	_#res: "\(#scalewayPrefix)_object_bucket_acl": res.#scaleway_object_bucket_acl
	_#res: "\(#scalewayPrefix)_object_bucket": res.#scaleway_object_bucket
	_#res: "\(#scalewayPrefix)_object_bucket_lock_configuration": res.#scaleway_object_bucket_lock_configuration
	_#res: "\(#scalewayPrefix)_object_bucket_policy": res.#scaleway_object_bucket_policy
	_#res: "\(#scalewayPrefix)_object_bucket_server_side_encryption_configuration": res.#scaleway_object_bucket_server_side_encryption_configuration
	_#res: "\(#scalewayPrefix)_object_bucket_website_configuration": res.#scaleway_object_bucket_website_configuration
	_#res: "\(#scalewayPrefix)_object": res.#scaleway_object
	_#res: "\(#scalewayPrefix)_opensearch_deployment": res.#scaleway_opensearch_deployment
	_#res: "\(#scalewayPrefix)_rdb_acl": res.#scaleway_rdb_acl
	_#res: "\(#scalewayPrefix)_rdb_database_backup": res.#scaleway_rdb_database_backup
	_#res: "\(#scalewayPrefix)_rdb_database": res.#scaleway_rdb_database
	_#res: "\(#scalewayPrefix)_rdb_instance": res.#scaleway_rdb_instance
	_#res: "\(#scalewayPrefix)_rdb_privilege": res.#scaleway_rdb_privilege
	_#res: "\(#scalewayPrefix)_rdb_read_replica": res.#scaleway_rdb_read_replica
	_#res: "\(#scalewayPrefix)_rdb_snapshot": res.#scaleway_rdb_snapshot
	_#res: "\(#scalewayPrefix)_rdb_user": res.#scaleway_rdb_user
	_#res: "\(#scalewayPrefix)_redis_cluster": res.#scaleway_redis_cluster
	_#res: "\(#scalewayPrefix)_registry_namespace": res.#scaleway_registry_namespace
	_#res: "\(#scalewayPrefix)_s2s_vpn_connection": res.#scaleway_s2s_vpn_connection
	_#res: "\(#scalewayPrefix)_s2s_vpn_customer_gateway": res.#scaleway_s2s_vpn_customer_gateway
	_#res: "\(#scalewayPrefix)_s2s_vpn_gateway": res.#scaleway_s2s_vpn_gateway
	_#res: "\(#scalewayPrefix)_s2s_vpn_routing_policy": res.#scaleway_s2s_vpn_routing_policy
	_#res: "\(#scalewayPrefix)_sdb_sql_database": res.#scaleway_sdb_sql_database
	_#res: "\(#scalewayPrefix)_secret": res.#scaleway_secret
	_#res: "\(#scalewayPrefix)_secret_version": res.#scaleway_secret_version
	_#res: "\(#scalewayPrefix)_tem_blocked_list": res.#scaleway_tem_blocked_list
	_#res: "\(#scalewayPrefix)_tem_domain": res.#scaleway_tem_domain
	_#res: "\(#scalewayPrefix)_tem_domain_validation": res.#scaleway_tem_domain_validation
	_#res: "\(#scalewayPrefix)_tem_webhook": res.#scaleway_tem_webhook
	_#res: "\(#scalewayPrefix)_vpc_acl": res.#scaleway_vpc_acl
	_#res: "\(#scalewayPrefix)_vpc_connector": res.#scaleway_vpc_connector
	_#res: "\(#scalewayPrefix)_vpc_gateway_network": res.#scaleway_vpc_gateway_network
	_#res: "\(#scalewayPrefix)_vpc": res.#scaleway_vpc
	_#res: "\(#scalewayPrefix)_vpc_private_network": res.#scaleway_vpc_private_network
	_#res: "\(#scalewayPrefix)_vpc_public_gateway_dhcp": res.#scaleway_vpc_public_gateway_dhcp
	_#res: "\(#scalewayPrefix)_vpc_public_gateway_dhcp_reservation": res.#scaleway_vpc_public_gateway_dhcp_reservation
	_#res: "\(#scalewayPrefix)_vpc_public_gateway": res.#scaleway_vpc_public_gateway
	_#res: "\(#scalewayPrefix)_vpc_public_gateway_ip": res.#scaleway_vpc_public_gateway_ip
	_#res: "\(#scalewayPrefix)_vpc_public_gateway_ip_reverse_dns": res.#scaleway_vpc_public_gateway_ip_reverse_dns
	_#res: "\(#scalewayPrefix)_vpc_public_gateway_pat_rule": res.#scaleway_vpc_public_gateway_pat_rule
	_#res: "\(#scalewayPrefix)_vpc_route": res.#scaleway_vpc_route
	_#res: "\(#scalewayPrefix)_webhosting": res.#scaleway_webhosting

}
