package elasticstack

import (
	"github.com/roman-mazur/cuetf"
	"github.com/roman-mazur/cuetf/providers/elasticstack/data"
)

#Terraform: {
	#elasticstackPrefix: string
	_#ds: "\(#elasticstackPrefix)_elasticsearch_connector": close({data.elasticstack_elasticsearch_connector & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_enrich_policy": close({data.elasticstack_elasticsearch_enrich_policy & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_index_template": close({data.elasticstack_elasticsearch_index_template & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_indices": close({data.elasticstack_elasticsearch_indices & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_info": close({data.elasticstack_elasticsearch_info & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_append": close({data.elasticstack_elasticsearch_ingest_processor_append & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_bytes": close({data.elasticstack_elasticsearch_ingest_processor_bytes & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_circle": close({data.elasticstack_elasticsearch_ingest_processor_circle & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_community_id": close({data.elasticstack_elasticsearch_ingest_processor_community_id & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_convert": close({data.elasticstack_elasticsearch_ingest_processor_convert & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_csv": close({data.elasticstack_elasticsearch_ingest_processor_csv & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_date": close({data.elasticstack_elasticsearch_ingest_processor_date & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_date_index_name": close({data.elasticstack_elasticsearch_ingest_processor_date_index_name & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_dissect": close({data.elasticstack_elasticsearch_ingest_processor_dissect & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_dot_expander": close({data.elasticstack_elasticsearch_ingest_processor_dot_expander & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_drop": close({data.elasticstack_elasticsearch_ingest_processor_drop & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_enrich": close({data.elasticstack_elasticsearch_ingest_processor_enrich & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_fail": close({data.elasticstack_elasticsearch_ingest_processor_fail & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_fingerprint": close({data.elasticstack_elasticsearch_ingest_processor_fingerprint & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_foreach": close({data.elasticstack_elasticsearch_ingest_processor_foreach & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_geoip": close({data.elasticstack_elasticsearch_ingest_processor_geoip & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_grok": close({data.elasticstack_elasticsearch_ingest_processor_grok & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_gsub": close({data.elasticstack_elasticsearch_ingest_processor_gsub & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_html_strip": close({data.elasticstack_elasticsearch_ingest_processor_html_strip & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_inference": close({data.elasticstack_elasticsearch_ingest_processor_inference & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_join": close({data.elasticstack_elasticsearch_ingest_processor_join & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_json": close({data.elasticstack_elasticsearch_ingest_processor_json & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_kv": close({data.elasticstack_elasticsearch_ingest_processor_kv & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_lowercase": close({data.elasticstack_elasticsearch_ingest_processor_lowercase & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_network_direction": close({data.elasticstack_elasticsearch_ingest_processor_network_direction & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_pipeline": close({data.elasticstack_elasticsearch_ingest_processor_pipeline & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_registered_domain": close({data.elasticstack_elasticsearch_ingest_processor_registered_domain & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_remove": close({data.elasticstack_elasticsearch_ingest_processor_remove & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_rename": close({data.elasticstack_elasticsearch_ingest_processor_rename & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_reroute": close({data.elasticstack_elasticsearch_ingest_processor_reroute & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_script": close({data.elasticstack_elasticsearch_ingest_processor_script & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_set": close({data.elasticstack_elasticsearch_ingest_processor_set & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_set_security_user": close({data.elasticstack_elasticsearch_ingest_processor_set_security_user & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_sort": close({data.elasticstack_elasticsearch_ingest_processor_sort & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_split": close({data.elasticstack_elasticsearch_ingest_processor_split & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_trim": close({data.elasticstack_elasticsearch_ingest_processor_trim & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_uppercase": close({data.elasticstack_elasticsearch_ingest_processor_uppercase & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_uri_parts": close({data.elasticstack_elasticsearch_ingest_processor_uri_parts & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_urldecode": close({data.elasticstack_elasticsearch_ingest_processor_urldecode & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ingest_processor_user_agent": close({data.elasticstack_elasticsearch_ingest_processor_user_agent & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_ml_trained_model": close({data.elasticstack_elasticsearch_ml_trained_model & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_query_ruleset": close({data.elasticstack_elasticsearch_query_ruleset & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_security_role": close({data.elasticstack_elasticsearch_security_role & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_security_role_mapping": close({data.elasticstack_elasticsearch_security_role_mapping & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_security_user": close({data.elasticstack_elasticsearch_security_user & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_snapshot_repository": close({data.elasticstack_elasticsearch_snapshot_repository & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_elasticsearch_synonym_set": close({data.elasticstack_elasticsearch_synonym_set & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_fleet_enrollment_tokens": close({data.elasticstack_fleet_enrollment_tokens & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_fleet_integration": close({data.elasticstack_fleet_integration & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_fleet_output": close({data.elasticstack_fleet_output & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_action_connector": close({data.elasticstack_kibana_action_connector & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_agentbuilder_agent": close({data.elasticstack_kibana_agentbuilder_agent & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_agentbuilder_skill": close({data.elasticstack_kibana_agentbuilder_skill & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_agentbuilder_tool": close({data.elasticstack_kibana_agentbuilder_tool & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_agentbuilder_workflow": close({data.elasticstack_kibana_agentbuilder_workflow & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_export_saved_objects": close({data.elasticstack_kibana_export_saved_objects & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_security_entity_store_entities": close({data.elasticstack_kibana_security_entity_store_entities & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_security_entity_store_resolution_group": close({data.elasticstack_kibana_security_entity_store_resolution_group & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_security_entity_store_status": close({data.elasticstack_kibana_security_entity_store_status & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_security_role": close({data.elasticstack_kibana_security_role & cuetf.MetaArgs})
	_#ds: "\(#elasticstackPrefix)_kibana_spaces": close({data.elasticstack_kibana_spaces & cuetf.MetaArgs})

}
