package res

import "list"

#scaleway_container: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/scaleway_container")
	close({
		health_check?: matchN(1, [#health_check, list.MaxItems(1) & [...#health_check]])
		liveness_probe?: matchN(1, [#liveness_probe, list.MaxItems(1) & [...#liveness_probe]])
		scaling_option?: matchN(1, [#scaling_option, [...#scaling_option]])
		startup_probe?: matchN(1, [#startup_probe, list.MaxItems(1) & [...#startup_probe]])
		timeouts?: #timeouts

		// Arguments passed to the command from the command "field".
		// Overrides the arguments from the container image.
		args?: [...string]

		// Command executed when the container starts. Overrides the
		// command from the container image.
		command?: [...string]

		// The amount of vCPU computing resources to allocate to each
		// container. Defaults to 70.
		cpu_limit?: number

		// The cron status
		cron_status?: string

		// The container description
		description?: string

		// The environment variables to be injected into your container at
		// runtime.
		environment_variables?: [string]: string

		// The error description
		error_message?: string

		// If true, it will allow only HTTPS connections to access your
		// container to prevent it from being triggered by insecure
		// connections (HTTP).
		https_connections_only?: bool
		id?:                     string

		// The image reference (e.g.
		// "rg.fr-par.scw.cloud/my-registry-namespace/image:tag" or
		// "nginx:latest").
		image?: string

		// Local storage limit of the container (in bytes)
		local_storage_limit_bytes?: number

		// The maximum of number of instances this container can scale to.
		max_scale?: number

		// The memory computing resources in bytes to allocate to each
		// container.
		memory_limit_bytes?: number

		// The minimum of number of instances this container can scale to.
		min_scale?: number

		// The container name
		name?: string

		// The container namespace associated
		namespace_id!: string

		// The port to expose the container.
		port?: number

		// The privacy type defines the way to authenticate to your
		// container
		privacy?: string

		// ID of the Private Network the container is connected to
		private_network_id?: string

		// The communication protocol http1 or h2c. Defaults to http1.
		protocol?: string

		// Public URL of the container. This is the default endpoint
		// generated by Scaleway to access the container from the
		// Internet.
		public_endpoint?: string

		// The region you want to attach the resource to
		region?: string

		// The sha256 of your source registry image, changing it will
		// re-apply the deployment. Can be any string
		registry_sha256?: string

		// Execution environment of the container.
		sandbox?: string

		// The secret environment variables to be injected into your
		// container at runtime.
		secret_environment_variables?: [string]: string

		// The container status
		status?: string

		// List of tags ["tag1", "tag2", ...] attached to the container.
		tags?: [...string]

		// The maximum amount of time in seconds during which your
		// container can process a request before we stop it. Defaults to
		// 300s.
		timeout?: number
	})

	#health_check: close({
		http?: matchN(1, [_#defs."/$defs/health_check/$defs/http", list.MaxItems(1) & [..._#defs."/$defs/health_check/$defs/http"]])

		// Number of consecutive health check failures before considering
		// the container unhealthy.
		failure_threshold?: number

		// Period between health checks.
		interval?: string

		// Perform TCP check on the container
		tcp?: bool
	})

	#liveness_probe: close({
		http?: matchN(1, [_#defs."/$defs/liveness_probe/$defs/http", list.MaxItems(1) & [..._#defs."/$defs/liveness_probe/$defs/http"]])

		// Number of consecutive failures before considering the container
		// has to be restarted.
		failure_threshold!: number

		// Time interval between checks (in duration notation).
		interval!: string

		// Perform TCP check on the container
		tcp?: bool

		// Duration before the check times out (in duration notation).
		timeout!: string
	})

	#scaling_option: close({
		// Scale depending on the number of concurrent requests being
		// processed per container instance.
		concurrent_requests_threshold?: number

		// Scale depending on the CPU usage of a container instance.
		cpu_usage_threshold?: number

		// Scale depending on the memory usage of a container instance.
		memory_usage_threshold?: number
	})

	#startup_probe: close({
		http?: matchN(1, [_#defs."/$defs/startup_probe/$defs/http", list.MaxItems(1) & [..._#defs."/$defs/startup_probe/$defs/http"]])

		// Number of consecutive failures before considering the container
		// has to be restarted.
		failure_threshold!: number

		// Time interval between checks (in duration notation).
		interval!: string

		// Perform TCP check on the container
		tcp?: bool

		// Duration before the check times out (in duration notation).
		timeout!: string
	})

	#timeouts: close({
		create?:  string
		default?: string
		delete?:  string
		read?:    string
		update?:  string
	})

	_#defs: "/$defs/health_check/$defs/http": close({
		// Path to use for the HTTP health check.
		path?: string
	})

	_#defs: "/$defs/liveness_probe/$defs/http": close({
		// Path to use for the HTTP health check.
		path!: string
	})

	_#defs: "/$defs/startup_probe/$defs/http": close({
		// Path to use for the HTTP health check.
		path!: string
	})
}
