package azurerm

import "github.com/roman-mazur/cuetf/azurerm/data"

#Terraform: {
	#azurermPrefix: string
	_#ds: "\(#azurermPrefix)_aadb2c_directory": data.#azurerm_aadb2c_directory
	_#ds: "\(#azurermPrefix)_active_directory_domain_service": data.#azurerm_active_directory_domain_service
	_#ds: "\(#azurermPrefix)_advisor_recommendations": data.#azurerm_advisor_recommendations
	_#ds: "\(#azurermPrefix)_api_connection": data.#azurerm_api_connection
	_#ds: "\(#azurermPrefix)_api_management_api": data.#azurerm_api_management_api
	_#ds: "\(#azurermPrefix)_api_management_api_version_set": data.#azurerm_api_management_api_version_set
	_#ds: "\(#azurermPrefix)_api_management_gateway": data.#azurerm_api_management_gateway
	_#ds: "\(#azurermPrefix)_api_management_gateway_host_name_configuration": data.#azurerm_api_management_gateway_host_name_configuration
	_#ds: "\(#azurermPrefix)_api_management": data.#azurerm_api_management
	_#ds: "\(#azurermPrefix)_api_management_group": data.#azurerm_api_management_group
	_#ds: "\(#azurermPrefix)_api_management_product": data.#azurerm_api_management_product
	_#ds: "\(#azurermPrefix)_api_management_subscription": data.#azurerm_api_management_subscription
	_#ds: "\(#azurermPrefix)_api_management_user": data.#azurerm_api_management_user
	_#ds: "\(#azurermPrefix)_app_configuration": data.#azurerm_app_configuration
	_#ds: "\(#azurermPrefix)_app_configuration_key": data.#azurerm_app_configuration_key
	_#ds: "\(#azurermPrefix)_app_configuration_keys": data.#azurerm_app_configuration_keys
	_#ds: "\(#azurermPrefix)_app_service_certificate": data.#azurerm_app_service_certificate
	_#ds: "\(#azurermPrefix)_app_service_certificate_order": data.#azurerm_app_service_certificate_order
	_#ds: "\(#azurermPrefix)_app_service_environment_v3": data.#azurerm_app_service_environment_v3
	_#ds: "\(#azurermPrefix)_app_service": data.#azurerm_app_service
	_#ds: "\(#azurermPrefix)_app_service_plan": data.#azurerm_app_service_plan
	_#ds: "\(#azurermPrefix)_application_gateway": data.#azurerm_application_gateway
	_#ds: "\(#azurermPrefix)_application_insights": data.#azurerm_application_insights
	_#ds: "\(#azurermPrefix)_application_security_group": data.#azurerm_application_security_group
	_#ds: "\(#azurermPrefix)_arc_machine": data.#azurerm_arc_machine
	_#ds: "\(#azurermPrefix)_arc_resource_bridge_appliance": data.#azurerm_arc_resource_bridge_appliance
	_#ds: "\(#azurermPrefix)_attestation_provider": data.#azurerm_attestation_provider
	_#ds: "\(#azurermPrefix)_automation_account": data.#azurerm_automation_account
	_#ds: "\(#azurermPrefix)_automation_runbook": data.#azurerm_automation_runbook
	_#ds: "\(#azurermPrefix)_automation_variable_bool": data.#azurerm_automation_variable_bool
	_#ds: "\(#azurermPrefix)_automation_variable_datetime": data.#azurerm_automation_variable_datetime
	_#ds: "\(#azurermPrefix)_automation_variable_int": data.#azurerm_automation_variable_int
	_#ds: "\(#azurermPrefix)_automation_variable_object": data.#azurerm_automation_variable_object
	_#ds: "\(#azurermPrefix)_automation_variable_string": data.#azurerm_automation_variable_string
	_#ds: "\(#azurermPrefix)_automation_variables": data.#azurerm_automation_variables
	_#ds: "\(#azurermPrefix)_availability_set": data.#azurerm_availability_set
	_#ds: "\(#azurermPrefix)_backup_policy_file_share": data.#azurerm_backup_policy_file_share
	_#ds: "\(#azurermPrefix)_backup_policy_vm": data.#azurerm_backup_policy_vm
	_#ds: "\(#azurermPrefix)_bastion_host": data.#azurerm_bastion_host
	_#ds: "\(#azurermPrefix)_batch_account": data.#azurerm_batch_account
	_#ds: "\(#azurermPrefix)_batch_application": data.#azurerm_batch_application
	_#ds: "\(#azurermPrefix)_batch_certificate": data.#azurerm_batch_certificate
	_#ds: "\(#azurermPrefix)_batch_pool": data.#azurerm_batch_pool
	_#ds: "\(#azurermPrefix)_billing_enrollment_account_scope": data.#azurerm_billing_enrollment_account_scope
	_#ds: "\(#azurermPrefix)_billing_mca_account_scope": data.#azurerm_billing_mca_account_scope
	_#ds: "\(#azurermPrefix)_billing_mpa_account_scope": data.#azurerm_billing_mpa_account_scope
	_#ds: "\(#azurermPrefix)_blueprint_definition": data.#azurerm_blueprint_definition
	_#ds: "\(#azurermPrefix)_blueprint_published_version": data.#azurerm_blueprint_published_version
	_#ds: "\(#azurermPrefix)_cdn_frontdoor_custom_domain": data.#azurerm_cdn_frontdoor_custom_domain
	_#ds: "\(#azurermPrefix)_cdn_frontdoor_endpoint": data.#azurerm_cdn_frontdoor_endpoint
	_#ds: "\(#azurermPrefix)_cdn_frontdoor_firewall_policy": data.#azurerm_cdn_frontdoor_firewall_policy
	_#ds: "\(#azurermPrefix)_cdn_frontdoor_origin_group": data.#azurerm_cdn_frontdoor_origin_group
	_#ds: "\(#azurermPrefix)_cdn_frontdoor_profile": data.#azurerm_cdn_frontdoor_profile
	_#ds: "\(#azurermPrefix)_cdn_frontdoor_rule_set": data.#azurerm_cdn_frontdoor_rule_set
	_#ds: "\(#azurermPrefix)_cdn_frontdoor_secret": data.#azurerm_cdn_frontdoor_secret
	_#ds: "\(#azurermPrefix)_cdn_profile": data.#azurerm_cdn_profile
	_#ds: "\(#azurermPrefix)_client_config": data.#azurerm_client_config
	_#ds: "\(#azurermPrefix)_cognitive_account": data.#azurerm_cognitive_account
	_#ds: "\(#azurermPrefix)_communication_service": data.#azurerm_communication_service
	_#ds: "\(#azurermPrefix)_confidential_ledger": data.#azurerm_confidential_ledger
	_#ds: "\(#azurermPrefix)_consumption_budget_resource_group": data.#azurerm_consumption_budget_resource_group
	_#ds: "\(#azurermPrefix)_consumption_budget_subscription": data.#azurerm_consumption_budget_subscription
	_#ds: "\(#azurermPrefix)_container_app_environment_certificate": data.#azurerm_container_app_environment_certificate
	_#ds: "\(#azurermPrefix)_container_app_environment": data.#azurerm_container_app_environment
	_#ds: "\(#azurermPrefix)_container_app": data.#azurerm_container_app
	_#ds: "\(#azurermPrefix)_container_group": data.#azurerm_container_group
	_#ds: "\(#azurermPrefix)_container_registry_cache_rule": data.#azurerm_container_registry_cache_rule
	_#ds: "\(#azurermPrefix)_container_registry": data.#azurerm_container_registry
	_#ds: "\(#azurermPrefix)_container_registry_scope_map": data.#azurerm_container_registry_scope_map
	_#ds: "\(#azurermPrefix)_container_registry_token": data.#azurerm_container_registry_token
	_#ds: "\(#azurermPrefix)_cosmosdb_account": data.#azurerm_cosmosdb_account
	_#ds: "\(#azurermPrefix)_cosmosdb_mongo_database": data.#azurerm_cosmosdb_mongo_database
	_#ds: "\(#azurermPrefix)_cosmosdb_restorable_database_accounts": data.#azurerm_cosmosdb_restorable_database_accounts
	_#ds: "\(#azurermPrefix)_cosmosdb_sql_database": data.#azurerm_cosmosdb_sql_database
	_#ds: "\(#azurermPrefix)_cosmosdb_sql_role_definition": data.#azurerm_cosmosdb_sql_role_definition
	_#ds: "\(#azurermPrefix)_dashboard_grafana": data.#azurerm_dashboard_grafana
	_#ds: "\(#azurermPrefix)_data_factory": data.#azurerm_data_factory
	_#ds: "\(#azurermPrefix)_data_factory_trigger_schedule": data.#azurerm_data_factory_trigger_schedule
	_#ds: "\(#azurermPrefix)_data_factory_trigger_schedules": data.#azurerm_data_factory_trigger_schedules
	_#ds: "\(#azurermPrefix)_data_protection_backup_vault": data.#azurerm_data_protection_backup_vault
	_#ds: "\(#azurermPrefix)_data_share_account": data.#azurerm_data_share_account
	_#ds: "\(#azurermPrefix)_data_share_dataset_blob_storage": data.#azurerm_data_share_dataset_blob_storage
	_#ds: "\(#azurermPrefix)_data_share_dataset_data_lake_gen2": data.#azurerm_data_share_dataset_data_lake_gen2
	_#ds: "\(#azurermPrefix)_data_share_dataset_kusto_cluster": data.#azurerm_data_share_dataset_kusto_cluster
	_#ds: "\(#azurermPrefix)_data_share_dataset_kusto_database": data.#azurerm_data_share_dataset_kusto_database
	_#ds: "\(#azurermPrefix)_data_share": data.#azurerm_data_share
	_#ds: "\(#azurermPrefix)_database_migration_project": data.#azurerm_database_migration_project
	_#ds: "\(#azurermPrefix)_database_migration_service": data.#azurerm_database_migration_service
	_#ds: "\(#azurermPrefix)_databox_edge_device": data.#azurerm_databox_edge_device
	_#ds: "\(#azurermPrefix)_databricks_access_connector": data.#azurerm_databricks_access_connector
	_#ds: "\(#azurermPrefix)_databricks_workspace": data.#azurerm_databricks_workspace
	_#ds: "\(#azurermPrefix)_databricks_workspace_private_endpoint_connection": data.#azurerm_databricks_workspace_private_endpoint_connection
	_#ds: "\(#azurermPrefix)_dedicated_host": data.#azurerm_dedicated_host
	_#ds: "\(#azurermPrefix)_dedicated_host_group": data.#azurerm_dedicated_host_group
	_#ds: "\(#azurermPrefix)_dev_center_attached_network": data.#azurerm_dev_center_attached_network
	_#ds: "\(#azurermPrefix)_dev_center_catalog": data.#azurerm_dev_center_catalog
	_#ds: "\(#azurermPrefix)_dev_center_dev_box_definition": data.#azurerm_dev_center_dev_box_definition
	_#ds: "\(#azurermPrefix)_dev_center_environment_type": data.#azurerm_dev_center_environment_type
	_#ds: "\(#azurermPrefix)_dev_center_gallery": data.#azurerm_dev_center_gallery
	_#ds: "\(#azurermPrefix)_dev_center": data.#azurerm_dev_center
	_#ds: "\(#azurermPrefix)_dev_center_network_connection": data.#azurerm_dev_center_network_connection
	_#ds: "\(#azurermPrefix)_dev_center_project_environment_type": data.#azurerm_dev_center_project_environment_type
	_#ds: "\(#azurermPrefix)_dev_center_project": data.#azurerm_dev_center_project
	_#ds: "\(#azurermPrefix)_dev_center_project_pool": data.#azurerm_dev_center_project_pool
	_#ds: "\(#azurermPrefix)_dev_test_lab": data.#azurerm_dev_test_lab
	_#ds: "\(#azurermPrefix)_dev_test_virtual_network": data.#azurerm_dev_test_virtual_network
	_#ds: "\(#azurermPrefix)_digital_twins_instance": data.#azurerm_digital_twins_instance
	_#ds: "\(#azurermPrefix)_disk_access": data.#azurerm_disk_access
	_#ds: "\(#azurermPrefix)_disk_encryption_set": data.#azurerm_disk_encryption_set
	_#ds: "\(#azurermPrefix)_dns_a_record": data.#azurerm_dns_a_record
	_#ds: "\(#azurermPrefix)_dns_aaaa_record": data.#azurerm_dns_aaaa_record
	_#ds: "\(#azurermPrefix)_dns_caa_record": data.#azurerm_dns_caa_record
	_#ds: "\(#azurermPrefix)_dns_cname_record": data.#azurerm_dns_cname_record
	_#ds: "\(#azurermPrefix)_dns_mx_record": data.#azurerm_dns_mx_record
	_#ds: "\(#azurermPrefix)_dns_ns_record": data.#azurerm_dns_ns_record
	_#ds: "\(#azurermPrefix)_dns_ptr_record": data.#azurerm_dns_ptr_record
	_#ds: "\(#azurermPrefix)_dns_soa_record": data.#azurerm_dns_soa_record
	_#ds: "\(#azurermPrefix)_dns_srv_record": data.#azurerm_dns_srv_record
	_#ds: "\(#azurermPrefix)_dns_txt_record": data.#azurerm_dns_txt_record
	_#ds: "\(#azurermPrefix)_dns_zone": data.#azurerm_dns_zone
	_#ds: "\(#azurermPrefix)_dynatrace_monitor": data.#azurerm_dynatrace_monitor
	_#ds: "\(#azurermPrefix)_elastic_cloud_elasticsearch": data.#azurerm_elastic_cloud_elasticsearch
	_#ds: "\(#azurermPrefix)_elastic_san": data.#azurerm_elastic_san
	_#ds: "\(#azurermPrefix)_elastic_san_volume_group": data.#azurerm_elastic_san_volume_group
	_#ds: "\(#azurermPrefix)_elastic_san_volume_snapshot": data.#azurerm_elastic_san_volume_snapshot
	_#ds: "\(#azurermPrefix)_eventgrid_domain": data.#azurerm_eventgrid_domain
	_#ds: "\(#azurermPrefix)_eventgrid_domain_topic": data.#azurerm_eventgrid_domain_topic
	_#ds: "\(#azurermPrefix)_eventgrid_partner_namespace": data.#azurerm_eventgrid_partner_namespace
	_#ds: "\(#azurermPrefix)_eventgrid_partner_registration": data.#azurerm_eventgrid_partner_registration
	_#ds: "\(#azurermPrefix)_eventgrid_system_topic": data.#azurerm_eventgrid_system_topic
	_#ds: "\(#azurermPrefix)_eventgrid_topic": data.#azurerm_eventgrid_topic
	_#ds: "\(#azurermPrefix)_eventhub_authorization_rule": data.#azurerm_eventhub_authorization_rule
	_#ds: "\(#azurermPrefix)_eventhub_cluster": data.#azurerm_eventhub_cluster
	_#ds: "\(#azurermPrefix)_eventhub_consumer_group": data.#azurerm_eventhub_consumer_group
	_#ds: "\(#azurermPrefix)_eventhub": data.#azurerm_eventhub
	_#ds: "\(#azurermPrefix)_eventhub_namespace_authorization_rule": data.#azurerm_eventhub_namespace_authorization_rule
	_#ds: "\(#azurermPrefix)_eventhub_namespace": data.#azurerm_eventhub_namespace
	_#ds: "\(#azurermPrefix)_eventhub_sas": data.#azurerm_eventhub_sas
	_#ds: "\(#azurermPrefix)_express_route_circuit": data.#azurerm_express_route_circuit
	_#ds: "\(#azurermPrefix)_express_route_circuit_peering": data.#azurerm_express_route_circuit_peering
	_#ds: "\(#azurermPrefix)_extended_location_custom_location": data.#azurerm_extended_location_custom_location
	_#ds: "\(#azurermPrefix)_extended_locations": data.#azurerm_extended_locations
	_#ds: "\(#azurermPrefix)_firewall": data.#azurerm_firewall
	_#ds: "\(#azurermPrefix)_firewall_policy": data.#azurerm_firewall_policy
	_#ds: "\(#azurermPrefix)_function_app": data.#azurerm_function_app
	_#ds: "\(#azurermPrefix)_function_app_host_keys": data.#azurerm_function_app_host_keys
	_#ds: "\(#azurermPrefix)_graph_services_account": data.#azurerm_graph_services_account
	_#ds: "\(#azurermPrefix)_hdinsight_cluster": data.#azurerm_hdinsight_cluster
	_#ds: "\(#azurermPrefix)_healthcare_dicom_service": data.#azurerm_healthcare_dicom_service
	_#ds: "\(#azurermPrefix)_healthcare_fhir_service": data.#azurerm_healthcare_fhir_service
	_#ds: "\(#azurermPrefix)_healthcare_medtech_service": data.#azurerm_healthcare_medtech_service
	_#ds: "\(#azurermPrefix)_healthcare_service": data.#azurerm_healthcare_service
	_#ds: "\(#azurermPrefix)_healthcare_workspace": data.#azurerm_healthcare_workspace
	_#ds: "\(#azurermPrefix)_image": data.#azurerm_image
	_#ds: "\(#azurermPrefix)_images": data.#azurerm_images
	_#ds: "\(#azurermPrefix)_iothub_dps": data.#azurerm_iothub_dps
	_#ds: "\(#azurermPrefix)_iothub_dps_shared_access_policy": data.#azurerm_iothub_dps_shared_access_policy
	_#ds: "\(#azurermPrefix)_iothub": data.#azurerm_iothub
	_#ds: "\(#azurermPrefix)_iothub_shared_access_policy": data.#azurerm_iothub_shared_access_policy
	_#ds: "\(#azurermPrefix)_ip_group": data.#azurerm_ip_group
	_#ds: "\(#azurermPrefix)_ip_groups": data.#azurerm_ip_groups
	_#ds: "\(#azurermPrefix)_key_vault_access_policy": data.#azurerm_key_vault_access_policy
	_#ds: "\(#azurermPrefix)_key_vault_certificate_data": data.#azurerm_key_vault_certificate_data
	_#ds: "\(#azurermPrefix)_key_vault_certificate": data.#azurerm_key_vault_certificate
	_#ds: "\(#azurermPrefix)_key_vault_certificate_issuer": data.#azurerm_key_vault_certificate_issuer
	_#ds: "\(#azurermPrefix)_key_vault_certificates": data.#azurerm_key_vault_certificates
	_#ds: "\(#azurermPrefix)_key_vault_encrypted_value": data.#azurerm_key_vault_encrypted_value
	_#ds: "\(#azurermPrefix)_key_vault": data.#azurerm_key_vault
	_#ds: "\(#azurermPrefix)_key_vault_key": data.#azurerm_key_vault_key
	_#ds: "\(#azurermPrefix)_key_vault_managed_hardware_security_module": data.#azurerm_key_vault_managed_hardware_security_module
	_#ds: "\(#azurermPrefix)_key_vault_managed_hardware_security_module_key": data.#azurerm_key_vault_managed_hardware_security_module_key
	_#ds: "\(#azurermPrefix)_key_vault_managed_hardware_security_module_role_definition": data.#azurerm_key_vault_managed_hardware_security_module_role_definition
	_#ds: "\(#azurermPrefix)_key_vault_secret": data.#azurerm_key_vault_secret
	_#ds: "\(#azurermPrefix)_key_vault_secrets": data.#azurerm_key_vault_secrets
	_#ds: "\(#azurermPrefix)_kubernetes_cluster": data.#azurerm_kubernetes_cluster
	_#ds: "\(#azurermPrefix)_kubernetes_cluster_node_pool": data.#azurerm_kubernetes_cluster_node_pool
	_#ds: "\(#azurermPrefix)_kubernetes_fleet_manager": data.#azurerm_kubernetes_fleet_manager
	_#ds: "\(#azurermPrefix)_kubernetes_node_pool_snapshot": data.#azurerm_kubernetes_node_pool_snapshot
	_#ds: "\(#azurermPrefix)_kubernetes_service_versions": data.#azurerm_kubernetes_service_versions
	_#ds: "\(#azurermPrefix)_kusto_cluster": data.#azurerm_kusto_cluster
	_#ds: "\(#azurermPrefix)_kusto_database": data.#azurerm_kusto_database
	_#ds: "\(#azurermPrefix)_lb_backend_address_pool": data.#azurerm_lb_backend_address_pool
	_#ds: "\(#azurermPrefix)_lb": data.#azurerm_lb
	_#ds: "\(#azurermPrefix)_lb_outbound_rule": data.#azurerm_lb_outbound_rule
	_#ds: "\(#azurermPrefix)_lb_rule": data.#azurerm_lb_rule
	_#ds: "\(#azurermPrefix)_linux_function_app": data.#azurerm_linux_function_app
	_#ds: "\(#azurermPrefix)_linux_web_app": data.#azurerm_linux_web_app
	_#ds: "\(#azurermPrefix)_load_test": data.#azurerm_load_test
	_#ds: "\(#azurermPrefix)_local_network_gateway": data.#azurerm_local_network_gateway
	_#ds: "\(#azurermPrefix)_location": data.#azurerm_location
	_#ds: "\(#azurermPrefix)_log_analytics_workspace": data.#azurerm_log_analytics_workspace
	_#ds: "\(#azurermPrefix)_log_analytics_workspace_table": data.#azurerm_log_analytics_workspace_table
	_#ds: "\(#azurermPrefix)_logic_app_integration_account": data.#azurerm_logic_app_integration_account
	_#ds: "\(#azurermPrefix)_logic_app_standard": data.#azurerm_logic_app_standard
	_#ds: "\(#azurermPrefix)_logic_app_workflow": data.#azurerm_logic_app_workflow
	_#ds: "\(#azurermPrefix)_machine_learning_workspace": data.#azurerm_machine_learning_workspace
	_#ds: "\(#azurermPrefix)_maintenance_configuration": data.#azurerm_maintenance_configuration
	_#ds: "\(#azurermPrefix)_managed_api": data.#azurerm_managed_api
	_#ds: "\(#azurermPrefix)_managed_application_definition": data.#azurerm_managed_application_definition
	_#ds: "\(#azurermPrefix)_managed_disk": data.#azurerm_managed_disk
	_#ds: "\(#azurermPrefix)_managed_disks": data.#azurerm_managed_disks
	_#ds: "\(#azurermPrefix)_managed_redis": data.#azurerm_managed_redis
	_#ds: "\(#azurermPrefix)_management_group": data.#azurerm_management_group
	_#ds: "\(#azurermPrefix)_management_group_template_deployment": data.#azurerm_management_group_template_deployment
	_#ds: "\(#azurermPrefix)_maps_account": data.#azurerm_maps_account
	_#ds: "\(#azurermPrefix)_marketplace_agreement": data.#azurerm_marketplace_agreement
	_#ds: "\(#azurermPrefix)_mobile_network_attached_data_network": data.#azurerm_mobile_network_attached_data_network
	_#ds: "\(#azurermPrefix)_mobile_network_data_network": data.#azurerm_mobile_network_data_network
	_#ds: "\(#azurermPrefix)_mobile_network": data.#azurerm_mobile_network
	_#ds: "\(#azurermPrefix)_mobile_network_packet_core_control_plane": data.#azurerm_mobile_network_packet_core_control_plane
	_#ds: "\(#azurermPrefix)_mobile_network_packet_core_data_plane": data.#azurerm_mobile_network_packet_core_data_plane
	_#ds: "\(#azurermPrefix)_mobile_network_service": data.#azurerm_mobile_network_service
	_#ds: "\(#azurermPrefix)_mobile_network_sim": data.#azurerm_mobile_network_sim
	_#ds: "\(#azurermPrefix)_mobile_network_sim_group": data.#azurerm_mobile_network_sim_group
	_#ds: "\(#azurermPrefix)_mobile_network_sim_policy": data.#azurerm_mobile_network_sim_policy
	_#ds: "\(#azurermPrefix)_mobile_network_site": data.#azurerm_mobile_network_site
	_#ds: "\(#azurermPrefix)_mobile_network_slice": data.#azurerm_mobile_network_slice
	_#ds: "\(#azurermPrefix)_monitor_action_group": data.#azurerm_monitor_action_group
	_#ds: "\(#azurermPrefix)_monitor_data_collection_endpoint": data.#azurerm_monitor_data_collection_endpoint
	_#ds: "\(#azurermPrefix)_monitor_data_collection_rule": data.#azurerm_monitor_data_collection_rule
	_#ds: "\(#azurermPrefix)_monitor_diagnostic_categories": data.#azurerm_monitor_diagnostic_categories
	_#ds: "\(#azurermPrefix)_monitor_scheduled_query_rules_alert": data.#azurerm_monitor_scheduled_query_rules_alert
	_#ds: "\(#azurermPrefix)_monitor_scheduled_query_rules_log": data.#azurerm_monitor_scheduled_query_rules_log
	_#ds: "\(#azurermPrefix)_monitor_workspace": data.#azurerm_monitor_workspace
	_#ds: "\(#azurermPrefix)_mssql_database": data.#azurerm_mssql_database
	_#ds: "\(#azurermPrefix)_mssql_elasticpool": data.#azurerm_mssql_elasticpool
	_#ds: "\(#azurermPrefix)_mssql_failover_group": data.#azurerm_mssql_failover_group
	_#ds: "\(#azurermPrefix)_mssql_managed_database": data.#azurerm_mssql_managed_database
	_#ds: "\(#azurermPrefix)_mssql_managed_instance": data.#azurerm_mssql_managed_instance
	_#ds: "\(#azurermPrefix)_mssql_server": data.#azurerm_mssql_server
	_#ds: "\(#azurermPrefix)_mysql_flexible_server": data.#azurerm_mysql_flexible_server
	_#ds: "\(#azurermPrefix)_nat_gateway": data.#azurerm_nat_gateway
	_#ds: "\(#azurermPrefix)_netapp_account_encryption": data.#azurerm_netapp_account_encryption
	_#ds: "\(#azurermPrefix)_netapp_account": data.#azurerm_netapp_account
	_#ds: "\(#azurermPrefix)_netapp_backup_policy": data.#azurerm_netapp_backup_policy
	_#ds: "\(#azurermPrefix)_netapp_backup_vault": data.#azurerm_netapp_backup_vault
	_#ds: "\(#azurermPrefix)_netapp_pool": data.#azurerm_netapp_pool
	_#ds: "\(#azurermPrefix)_netapp_snapshot": data.#azurerm_netapp_snapshot
	_#ds: "\(#azurermPrefix)_netapp_snapshot_policy": data.#azurerm_netapp_snapshot_policy
	_#ds: "\(#azurermPrefix)_netapp_volume": data.#azurerm_netapp_volume
	_#ds: "\(#azurermPrefix)_netapp_volume_group_oracle": data.#azurerm_netapp_volume_group_oracle
	_#ds: "\(#azurermPrefix)_netapp_volume_group_sap_hana": data.#azurerm_netapp_volume_group_sap_hana
	_#ds: "\(#azurermPrefix)_netapp_volume_quota_rule": data.#azurerm_netapp_volume_quota_rule
	_#ds: "\(#azurermPrefix)_network_ddos_protection_plan": data.#azurerm_network_ddos_protection_plan
	_#ds: "\(#azurermPrefix)_network_interface": data.#azurerm_network_interface
	_#ds: "\(#azurermPrefix)_network_manager_connectivity_configuration": data.#azurerm_network_manager_connectivity_configuration
	_#ds: "\(#azurermPrefix)_network_manager": data.#azurerm_network_manager
	_#ds: "\(#azurermPrefix)_network_manager_ipam_pool": data.#azurerm_network_manager_ipam_pool
	_#ds: "\(#azurermPrefix)_network_manager_network_group": data.#azurerm_network_manager_network_group
	_#ds: "\(#azurermPrefix)_network_security_group": data.#azurerm_network_security_group
	_#ds: "\(#azurermPrefix)_network_service_tags": data.#azurerm_network_service_tags
	_#ds: "\(#azurermPrefix)_network_watcher": data.#azurerm_network_watcher
	_#ds: "\(#azurermPrefix)_nginx_api_key": data.#azurerm_nginx_api_key
	_#ds: "\(#azurermPrefix)_nginx_certificate": data.#azurerm_nginx_certificate
	_#ds: "\(#azurermPrefix)_nginx_configuration": data.#azurerm_nginx_configuration
	_#ds: "\(#azurermPrefix)_nginx_deployment": data.#azurerm_nginx_deployment
	_#ds: "\(#azurermPrefix)_notification_hub": data.#azurerm_notification_hub
	_#ds: "\(#azurermPrefix)_notification_hub_namespace": data.#azurerm_notification_hub_namespace
	_#ds: "\(#azurermPrefix)_oracle_adbs_character_sets": data.#azurerm_oracle_adbs_character_sets
	_#ds: "\(#azurermPrefix)_oracle_adbs_national_character_sets": data.#azurerm_oracle_adbs_national_character_sets
	_#ds: "\(#azurermPrefix)_oracle_autonomous_database_backup": data.#azurerm_oracle_autonomous_database_backup
	_#ds: "\(#azurermPrefix)_oracle_autonomous_database_backups": data.#azurerm_oracle_autonomous_database_backups
	_#ds: "\(#azurermPrefix)_oracle_autonomous_database_clone_from_backup": data.#azurerm_oracle_autonomous_database_clone_from_backup
	_#ds: "\(#azurermPrefix)_oracle_autonomous_database_clone_from_database": data.#azurerm_oracle_autonomous_database_clone_from_database
	_#ds: "\(#azurermPrefix)_oracle_autonomous_database": data.#azurerm_oracle_autonomous_database
	_#ds: "\(#azurermPrefix)_oracle_cloud_vm_cluster": data.#azurerm_oracle_cloud_vm_cluster
	_#ds: "\(#azurermPrefix)_oracle_db_nodes": data.#azurerm_oracle_db_nodes
	_#ds: "\(#azurermPrefix)_oracle_db_servers": data.#azurerm_oracle_db_servers
	_#ds: "\(#azurermPrefix)_oracle_db_system_shapes": data.#azurerm_oracle_db_system_shapes
	_#ds: "\(#azurermPrefix)_oracle_exadata_infrastructure": data.#azurerm_oracle_exadata_infrastructure
	_#ds: "\(#azurermPrefix)_oracle_exascale_database_storage_vault": data.#azurerm_oracle_exascale_database_storage_vault
	_#ds: "\(#azurermPrefix)_oracle_gi_versions": data.#azurerm_oracle_gi_versions
	_#ds: "\(#azurermPrefix)_oracle_resource_anchor": data.#azurerm_oracle_resource_anchor
	_#ds: "\(#azurermPrefix)_orchestrated_virtual_machine_scale_set": data.#azurerm_orchestrated_virtual_machine_scale_set
	_#ds: "\(#azurermPrefix)_palo_alto_local_rulestack": data.#azurerm_palo_alto_local_rulestack
	_#ds: "\(#azurermPrefix)_platform_image": data.#azurerm_platform_image
	_#ds: "\(#azurermPrefix)_policy_assignment": data.#azurerm_policy_assignment
	_#ds: "\(#azurermPrefix)_policy_definition_built_in": data.#azurerm_policy_definition_built_in
	_#ds: "\(#azurermPrefix)_policy_definition": data.#azurerm_policy_definition
	_#ds: "\(#azurermPrefix)_policy_set_definition": data.#azurerm_policy_set_definition
	_#ds: "\(#azurermPrefix)_policy_virtual_machine_configuration_assignment": data.#azurerm_policy_virtual_machine_configuration_assignment
	_#ds: "\(#azurermPrefix)_portal_dashboard": data.#azurerm_portal_dashboard
	_#ds: "\(#azurermPrefix)_postgresql_flexible_server": data.#azurerm_postgresql_flexible_server
	_#ds: "\(#azurermPrefix)_postgresql_server": data.#azurerm_postgresql_server
	_#ds: "\(#azurermPrefix)_private_dns_a_record": data.#azurerm_private_dns_a_record
	_#ds: "\(#azurermPrefix)_private_dns_aaaa_record": data.#azurerm_private_dns_aaaa_record
	_#ds: "\(#azurermPrefix)_private_dns_cname_record": data.#azurerm_private_dns_cname_record
	_#ds: "\(#azurermPrefix)_private_dns_mx_record": data.#azurerm_private_dns_mx_record
	_#ds: "\(#azurermPrefix)_private_dns_ptr_record": data.#azurerm_private_dns_ptr_record
	_#ds: "\(#azurermPrefix)_private_dns_resolver_dns_forwarding_ruleset": data.#azurerm_private_dns_resolver_dns_forwarding_ruleset
	_#ds: "\(#azurermPrefix)_private_dns_resolver_forwarding_rule": data.#azurerm_private_dns_resolver_forwarding_rule
	_#ds: "\(#azurermPrefix)_private_dns_resolver": data.#azurerm_private_dns_resolver
	_#ds: "\(#azurermPrefix)_private_dns_resolver_inbound_endpoint": data.#azurerm_private_dns_resolver_inbound_endpoint
	_#ds: "\(#azurermPrefix)_private_dns_resolver_outbound_endpoint": data.#azurerm_private_dns_resolver_outbound_endpoint
	_#ds: "\(#azurermPrefix)_private_dns_resolver_virtual_network_link": data.#azurerm_private_dns_resolver_virtual_network_link
	_#ds: "\(#azurermPrefix)_private_dns_soa_record": data.#azurerm_private_dns_soa_record
	_#ds: "\(#azurermPrefix)_private_dns_srv_record": data.#azurerm_private_dns_srv_record
	_#ds: "\(#azurermPrefix)_private_dns_txt_record": data.#azurerm_private_dns_txt_record
	_#ds: "\(#azurermPrefix)_private_dns_zone": data.#azurerm_private_dns_zone
	_#ds: "\(#azurermPrefix)_private_dns_zone_virtual_network_link": data.#azurerm_private_dns_zone_virtual_network_link
	_#ds: "\(#azurermPrefix)_private_endpoint_connection": data.#azurerm_private_endpoint_connection
	_#ds: "\(#azurermPrefix)_private_link_service_endpoint_connections": data.#azurerm_private_link_service_endpoint_connections
	_#ds: "\(#azurermPrefix)_private_link_service": data.#azurerm_private_link_service
	_#ds: "\(#azurermPrefix)_proximity_placement_group": data.#azurerm_proximity_placement_group
	_#ds: "\(#azurermPrefix)_public_ip": data.#azurerm_public_ip
	_#ds: "\(#azurermPrefix)_public_ip_prefix": data.#azurerm_public_ip_prefix
	_#ds: "\(#azurermPrefix)_public_ips": data.#azurerm_public_ips
	_#ds: "\(#azurermPrefix)_public_maintenance_configurations": data.#azurerm_public_maintenance_configurations
	_#ds: "\(#azurermPrefix)_recovery_services_vault": data.#azurerm_recovery_services_vault
	_#ds: "\(#azurermPrefix)_redis_cache": data.#azurerm_redis_cache
	_#ds: "\(#azurermPrefix)_redis_enterprise_database": data.#azurerm_redis_enterprise_database
	_#ds: "\(#azurermPrefix)_resource_group": data.#azurerm_resource_group
	_#ds: "\(#azurermPrefix)_resource_group_template_deployment": data.#azurerm_resource_group_template_deployment
	_#ds: "\(#azurermPrefix)_resources": data.#azurerm_resources
	_#ds: "\(#azurermPrefix)_role_assignments": data.#azurerm_role_assignments
	_#ds: "\(#azurermPrefix)_role_definition": data.#azurerm_role_definition
	_#ds: "\(#azurermPrefix)_role_management_policy": data.#azurerm_role_management_policy
	_#ds: "\(#azurermPrefix)_route_filter": data.#azurerm_route_filter
	_#ds: "\(#azurermPrefix)_route_table": data.#azurerm_route_table
	_#ds: "\(#azurermPrefix)_search_service": data.#azurerm_search_service
	_#ds: "\(#azurermPrefix)_sentinel_alert_rule_anomaly": data.#azurerm_sentinel_alert_rule_anomaly
	_#ds: "\(#azurermPrefix)_sentinel_alert_rule": data.#azurerm_sentinel_alert_rule
	_#ds: "\(#azurermPrefix)_sentinel_alert_rule_template": data.#azurerm_sentinel_alert_rule_template
	_#ds: "\(#azurermPrefix)_service_plan": data.#azurerm_service_plan
	_#ds: "\(#azurermPrefix)_servicebus_namespace_authorization_rule": data.#azurerm_servicebus_namespace_authorization_rule
	_#ds: "\(#azurermPrefix)_servicebus_namespace_disaster_recovery_config": data.#azurerm_servicebus_namespace_disaster_recovery_config
	_#ds: "\(#azurermPrefix)_servicebus_namespace": data.#azurerm_servicebus_namespace
	_#ds: "\(#azurermPrefix)_servicebus_queue_authorization_rule": data.#azurerm_servicebus_queue_authorization_rule
	_#ds: "\(#azurermPrefix)_servicebus_queue": data.#azurerm_servicebus_queue
	_#ds: "\(#azurermPrefix)_servicebus_subscription": data.#azurerm_servicebus_subscription
	_#ds: "\(#azurermPrefix)_servicebus_topic_authorization_rule": data.#azurerm_servicebus_topic_authorization_rule
	_#ds: "\(#azurermPrefix)_servicebus_topic": data.#azurerm_servicebus_topic
	_#ds: "\(#azurermPrefix)_shared_image_gallery": data.#azurerm_shared_image_gallery
	_#ds: "\(#azurermPrefix)_shared_image": data.#azurerm_shared_image
	_#ds: "\(#azurermPrefix)_shared_image_version": data.#azurerm_shared_image_version
	_#ds: "\(#azurermPrefix)_shared_image_versions": data.#azurerm_shared_image_versions
	_#ds: "\(#azurermPrefix)_signalr_service": data.#azurerm_signalr_service
	_#ds: "\(#azurermPrefix)_site_recovery_fabric": data.#azurerm_site_recovery_fabric
	_#ds: "\(#azurermPrefix)_site_recovery_protection_container": data.#azurerm_site_recovery_protection_container
	_#ds: "\(#azurermPrefix)_site_recovery_replication_policy": data.#azurerm_site_recovery_replication_policy
	_#ds: "\(#azurermPrefix)_site_recovery_replication_recovery_plan": data.#azurerm_site_recovery_replication_recovery_plan
	_#ds: "\(#azurermPrefix)_snapshot": data.#azurerm_snapshot
	_#ds: "\(#azurermPrefix)_source_control_token": data.#azurerm_source_control_token
	_#ds: "\(#azurermPrefix)_spatial_anchors_account": data.#azurerm_spatial_anchors_account
	_#ds: "\(#azurermPrefix)_spring_cloud_app": data.#azurerm_spring_cloud_app
	_#ds: "\(#azurermPrefix)_spring_cloud_service": data.#azurerm_spring_cloud_service
	_#ds: "\(#azurermPrefix)_ssh_public_key": data.#azurerm_ssh_public_key
	_#ds: "\(#azurermPrefix)_stack_hci_cluster": data.#azurerm_stack_hci_cluster
	_#ds: "\(#azurermPrefix)_stack_hci_storage_path": data.#azurerm_stack_hci_storage_path
	_#ds: "\(#azurermPrefix)_static_web_app": data.#azurerm_static_web_app
	_#ds: "\(#azurermPrefix)_storage_account_blob_container_sas": data.#azurerm_storage_account_blob_container_sas
	_#ds: "\(#azurermPrefix)_storage_account": data.#azurerm_storage_account
	_#ds: "\(#azurermPrefix)_storage_account_sas": data.#azurerm_storage_account_sas
	_#ds: "\(#azurermPrefix)_storage_blob": data.#azurerm_storage_blob
	_#ds: "\(#azurermPrefix)_storage_container": data.#azurerm_storage_container
	_#ds: "\(#azurermPrefix)_storage_containers": data.#azurerm_storage_containers
	_#ds: "\(#azurermPrefix)_storage_encryption_scope": data.#azurerm_storage_encryption_scope
	_#ds: "\(#azurermPrefix)_storage_management_policy": data.#azurerm_storage_management_policy
	_#ds: "\(#azurermPrefix)_storage_queue": data.#azurerm_storage_queue
	_#ds: "\(#azurermPrefix)_storage_share": data.#azurerm_storage_share
	_#ds: "\(#azurermPrefix)_storage_sync": data.#azurerm_storage_sync
	_#ds: "\(#azurermPrefix)_storage_sync_group": data.#azurerm_storage_sync_group
	_#ds: "\(#azurermPrefix)_storage_table_entities": data.#azurerm_storage_table_entities
	_#ds: "\(#azurermPrefix)_storage_table_entity": data.#azurerm_storage_table_entity
	_#ds: "\(#azurermPrefix)_storage_table": data.#azurerm_storage_table
	_#ds: "\(#azurermPrefix)_stream_analytics_job": data.#azurerm_stream_analytics_job
	_#ds: "\(#azurermPrefix)_subnet": data.#azurerm_subnet
	_#ds: "\(#azurermPrefix)_subscription": data.#azurerm_subscription
	_#ds: "\(#azurermPrefix)_subscription_template_deployment": data.#azurerm_subscription_template_deployment
	_#ds: "\(#azurermPrefix)_subscriptions": data.#azurerm_subscriptions
	_#ds: "\(#azurermPrefix)_synapse_workspace": data.#azurerm_synapse_workspace
	_#ds: "\(#azurermPrefix)_system_center_virtual_machine_manager_inventory_items": data.#azurerm_system_center_virtual_machine_manager_inventory_items
	_#ds: "\(#azurermPrefix)_template_spec_version": data.#azurerm_template_spec_version
	_#ds: "\(#azurermPrefix)_tenant_template_deployment": data.#azurerm_tenant_template_deployment
	_#ds: "\(#azurermPrefix)_traffic_manager_geographical_location": data.#azurerm_traffic_manager_geographical_location
	_#ds: "\(#azurermPrefix)_traffic_manager_profile": data.#azurerm_traffic_manager_profile
	_#ds: "\(#azurermPrefix)_trusted_signing_account": data.#azurerm_trusted_signing_account
	_#ds: "\(#azurermPrefix)_user_assigned_identity": data.#azurerm_user_assigned_identity
	_#ds: "\(#azurermPrefix)_virtual_desktop_application_group": data.#azurerm_virtual_desktop_application_group
	_#ds: "\(#azurermPrefix)_virtual_desktop_host_pool": data.#azurerm_virtual_desktop_host_pool
	_#ds: "\(#azurermPrefix)_virtual_desktop_workspace": data.#azurerm_virtual_desktop_workspace
	_#ds: "\(#azurermPrefix)_virtual_hub_connection": data.#azurerm_virtual_hub_connection
	_#ds: "\(#azurermPrefix)_virtual_hub": data.#azurerm_virtual_hub
	_#ds: "\(#azurermPrefix)_virtual_hub_route_table": data.#azurerm_virtual_hub_route_table
	_#ds: "\(#azurermPrefix)_virtual_machine": data.#azurerm_virtual_machine
	_#ds: "\(#azurermPrefix)_virtual_machine_scale_set": data.#azurerm_virtual_machine_scale_set
	_#ds: "\(#azurermPrefix)_virtual_network_gateway_connection": data.#azurerm_virtual_network_gateway_connection
	_#ds: "\(#azurermPrefix)_virtual_network_gateway": data.#azurerm_virtual_network_gateway
	_#ds: "\(#azurermPrefix)_virtual_network": data.#azurerm_virtual_network
	_#ds: "\(#azurermPrefix)_virtual_network_peering": data.#azurerm_virtual_network_peering
	_#ds: "\(#azurermPrefix)_virtual_wan": data.#azurerm_virtual_wan
	_#ds: "\(#azurermPrefix)_vmware_private_cloud": data.#azurerm_vmware_private_cloud
	_#ds: "\(#azurermPrefix)_vpn_gateway": data.#azurerm_vpn_gateway
	_#ds: "\(#azurermPrefix)_vpn_server_configuration": data.#azurerm_vpn_server_configuration
	_#ds: "\(#azurermPrefix)_web_application_firewall_policy": data.#azurerm_web_application_firewall_policy
	_#ds: "\(#azurermPrefix)_web_pubsub": data.#azurerm_web_pubsub
	_#ds: "\(#azurermPrefix)_web_pubsub_private_link_resource": data.#azurerm_web_pubsub_private_link_resource
	_#ds: "\(#azurermPrefix)_windows_function_app": data.#azurerm_windows_function_app
	_#ds: "\(#azurermPrefix)_windows_web_app": data.#azurerm_windows_web_app

}
