package aws

import "github.com/roman-mazur/cuetf/aws/data"

#Terraform: {
	#awsPrefix: string
	_#ds: "\(#awsPrefix)_account_primary_contact": data.#aws_account_primary_contact
	_#ds: "\(#awsPrefix)_acm_certificate": data.#aws_acm_certificate
	_#ds: "\(#awsPrefix)_acmpca_certificate_authority": data.#aws_acmpca_certificate_authority
	_#ds: "\(#awsPrefix)_acmpca_certificate": data.#aws_acmpca_certificate
	_#ds: "\(#awsPrefix)_alb": data.#aws_alb
	_#ds: "\(#awsPrefix)_alb_listener": data.#aws_alb_listener
	_#ds: "\(#awsPrefix)_alb_target_group": data.#aws_alb_target_group
	_#ds: "\(#awsPrefix)_ami": data.#aws_ami
	_#ds: "\(#awsPrefix)_ami_ids": data.#aws_ami_ids
	_#ds: "\(#awsPrefix)_api_gateway_api_key": data.#aws_api_gateway_api_key
	_#ds: "\(#awsPrefix)_api_gateway_api_keys": data.#aws_api_gateway_api_keys
	_#ds: "\(#awsPrefix)_api_gateway_authorizer": data.#aws_api_gateway_authorizer
	_#ds: "\(#awsPrefix)_api_gateway_authorizers": data.#aws_api_gateway_authorizers
	_#ds: "\(#awsPrefix)_api_gateway_domain_name": data.#aws_api_gateway_domain_name
	_#ds: "\(#awsPrefix)_api_gateway_export": data.#aws_api_gateway_export
	_#ds: "\(#awsPrefix)_api_gateway_resource": data.#aws_api_gateway_resource
	_#ds: "\(#awsPrefix)_api_gateway_rest_api": data.#aws_api_gateway_rest_api
	_#ds: "\(#awsPrefix)_api_gateway_sdk": data.#aws_api_gateway_sdk
	_#ds: "\(#awsPrefix)_api_gateway_vpc_link": data.#aws_api_gateway_vpc_link
	_#ds: "\(#awsPrefix)_apigatewayv2_api": data.#aws_apigatewayv2_api
	_#ds: "\(#awsPrefix)_apigatewayv2_apis": data.#aws_apigatewayv2_apis
	_#ds: "\(#awsPrefix)_apigatewayv2_export": data.#aws_apigatewayv2_export
	_#ds: "\(#awsPrefix)_apigatewayv2_vpc_link": data.#aws_apigatewayv2_vpc_link
	_#ds: "\(#awsPrefix)_appconfig_application": data.#aws_appconfig_application
	_#ds: "\(#awsPrefix)_appconfig_configuration_profile": data.#aws_appconfig_configuration_profile
	_#ds: "\(#awsPrefix)_appconfig_configuration_profiles": data.#aws_appconfig_configuration_profiles
	_#ds: "\(#awsPrefix)_appconfig_environment": data.#aws_appconfig_environment
	_#ds: "\(#awsPrefix)_appconfig_environments": data.#aws_appconfig_environments
	_#ds: "\(#awsPrefix)_appintegrations_event_integration": data.#aws_appintegrations_event_integration
	_#ds: "\(#awsPrefix)_appmesh_gateway_route": data.#aws_appmesh_gateway_route
	_#ds: "\(#awsPrefix)_appmesh_mesh": data.#aws_appmesh_mesh
	_#ds: "\(#awsPrefix)_appmesh_route": data.#aws_appmesh_route
	_#ds: "\(#awsPrefix)_appmesh_virtual_gateway": data.#aws_appmesh_virtual_gateway
	_#ds: "\(#awsPrefix)_appmesh_virtual_node": data.#aws_appmesh_virtual_node
	_#ds: "\(#awsPrefix)_appmesh_virtual_router": data.#aws_appmesh_virtual_router
	_#ds: "\(#awsPrefix)_appmesh_virtual_service": data.#aws_appmesh_virtual_service
	_#ds: "\(#awsPrefix)_apprunner_hosted_zone_id": data.#aws_apprunner_hosted_zone_id
	_#ds: "\(#awsPrefix)_appstream_image": data.#aws_appstream_image
	_#ds: "\(#awsPrefix)_arn": data.#aws_arn
	_#ds: "\(#awsPrefix)_athena_named_query": data.#aws_athena_named_query
	_#ds: "\(#awsPrefix)_auditmanager_control": data.#aws_auditmanager_control
	_#ds: "\(#awsPrefix)_auditmanager_framework": data.#aws_auditmanager_framework
	_#ds: "\(#awsPrefix)_autoscaling_group": data.#aws_autoscaling_group
	_#ds: "\(#awsPrefix)_autoscaling_groups": data.#aws_autoscaling_groups
	_#ds: "\(#awsPrefix)_availability_zone": data.#aws_availability_zone
	_#ds: "\(#awsPrefix)_availability_zones": data.#aws_availability_zones
	_#ds: "\(#awsPrefix)_backup_framework": data.#aws_backup_framework
	_#ds: "\(#awsPrefix)_backup_plan": data.#aws_backup_plan
	_#ds: "\(#awsPrefix)_backup_report_plan": data.#aws_backup_report_plan
	_#ds: "\(#awsPrefix)_backup_selection": data.#aws_backup_selection
	_#ds: "\(#awsPrefix)_backup_vault": data.#aws_backup_vault
	_#ds: "\(#awsPrefix)_batch_compute_environment": data.#aws_batch_compute_environment
	_#ds: "\(#awsPrefix)_batch_job_definition": data.#aws_batch_job_definition
	_#ds: "\(#awsPrefix)_batch_job_queue": data.#aws_batch_job_queue
	_#ds: "\(#awsPrefix)_batch_scheduling_policy": data.#aws_batch_scheduling_policy
	_#ds: "\(#awsPrefix)_bedrock_custom_model": data.#aws_bedrock_custom_model
	_#ds: "\(#awsPrefix)_bedrock_custom_models": data.#aws_bedrock_custom_models
	_#ds: "\(#awsPrefix)_bedrock_foundation_model": data.#aws_bedrock_foundation_model
	_#ds: "\(#awsPrefix)_bedrock_foundation_models": data.#aws_bedrock_foundation_models
	_#ds: "\(#awsPrefix)_bedrock_inference_profile": data.#aws_bedrock_inference_profile
	_#ds: "\(#awsPrefix)_bedrock_inference_profiles": data.#aws_bedrock_inference_profiles
	_#ds: "\(#awsPrefix)_bedrockagent_agent_versions": data.#aws_bedrockagent_agent_versions
	_#ds: "\(#awsPrefix)_billing_service_account": data.#aws_billing_service_account
	_#ds: "\(#awsPrefix)_billing_views": data.#aws_billing_views
	_#ds: "\(#awsPrefix)_budgets_budget": data.#aws_budgets_budget
	_#ds: "\(#awsPrefix)_caller_identity": data.#aws_caller_identity
	_#ds: "\(#awsPrefix)_canonical_user_id": data.#aws_canonical_user_id
	_#ds: "\(#awsPrefix)_ce_cost_category": data.#aws_ce_cost_category
	_#ds: "\(#awsPrefix)_ce_tags": data.#aws_ce_tags
	_#ds: "\(#awsPrefix)_chatbot_slack_workspace": data.#aws_chatbot_slack_workspace
	_#ds: "\(#awsPrefix)_cloudcontrolapi_resource": data.#aws_cloudcontrolapi_resource
	_#ds: "\(#awsPrefix)_cloudformation_export": data.#aws_cloudformation_export
	_#ds: "\(#awsPrefix)_cloudformation_stack": data.#aws_cloudformation_stack
	_#ds: "\(#awsPrefix)_cloudformation_type": data.#aws_cloudformation_type
	_#ds: "\(#awsPrefix)_cloudfront_cache_policy": data.#aws_cloudfront_cache_policy
	_#ds: "\(#awsPrefix)_cloudfront_distribution": data.#aws_cloudfront_distribution
	_#ds: "\(#awsPrefix)_cloudfront_function": data.#aws_cloudfront_function
	_#ds: "\(#awsPrefix)_cloudfront_log_delivery_canonical_user_id": data.#aws_cloudfront_log_delivery_canonical_user_id
	_#ds: "\(#awsPrefix)_cloudfront_origin_access_control": data.#aws_cloudfront_origin_access_control
	_#ds: "\(#awsPrefix)_cloudfront_origin_access_identities": data.#aws_cloudfront_origin_access_identities
	_#ds: "\(#awsPrefix)_cloudfront_origin_access_identity": data.#aws_cloudfront_origin_access_identity
	_#ds: "\(#awsPrefix)_cloudfront_origin_request_policy": data.#aws_cloudfront_origin_request_policy
	_#ds: "\(#awsPrefix)_cloudfront_realtime_log_config": data.#aws_cloudfront_realtime_log_config
	_#ds: "\(#awsPrefix)_cloudfront_response_headers_policy": data.#aws_cloudfront_response_headers_policy
	_#ds: "\(#awsPrefix)_cloudhsm_v2_cluster": data.#aws_cloudhsm_v2_cluster
	_#ds: "\(#awsPrefix)_cloudtrail_service_account": data.#aws_cloudtrail_service_account
	_#ds: "\(#awsPrefix)_cloudwatch_contributor_managed_insight_rules": data.#aws_cloudwatch_contributor_managed_insight_rules
	_#ds: "\(#awsPrefix)_cloudwatch_event_bus": data.#aws_cloudwatch_event_bus
	_#ds: "\(#awsPrefix)_cloudwatch_event_buses": data.#aws_cloudwatch_event_buses
	_#ds: "\(#awsPrefix)_cloudwatch_event_connection": data.#aws_cloudwatch_event_connection
	_#ds: "\(#awsPrefix)_cloudwatch_event_source": data.#aws_cloudwatch_event_source
	_#ds: "\(#awsPrefix)_cloudwatch_log_data_protection_policy_document": data.#aws_cloudwatch_log_data_protection_policy_document
	_#ds: "\(#awsPrefix)_cloudwatch_log_group": data.#aws_cloudwatch_log_group
	_#ds: "\(#awsPrefix)_cloudwatch_log_groups": data.#aws_cloudwatch_log_groups
	_#ds: "\(#awsPrefix)_codeartifact_authorization_token": data.#aws_codeartifact_authorization_token
	_#ds: "\(#awsPrefix)_codeartifact_repository_endpoint": data.#aws_codeartifact_repository_endpoint
	_#ds: "\(#awsPrefix)_codebuild_fleet": data.#aws_codebuild_fleet
	_#ds: "\(#awsPrefix)_codecatalyst_dev_environment": data.#aws_codecatalyst_dev_environment
	_#ds: "\(#awsPrefix)_codecommit_approval_rule_template": data.#aws_codecommit_approval_rule_template
	_#ds: "\(#awsPrefix)_codecommit_repository": data.#aws_codecommit_repository
	_#ds: "\(#awsPrefix)_codeguruprofiler_profiling_group": data.#aws_codeguruprofiler_profiling_group
	_#ds: "\(#awsPrefix)_codestarconnections_connection": data.#aws_codestarconnections_connection
	_#ds: "\(#awsPrefix)_cognito_identity_pool": data.#aws_cognito_identity_pool
	_#ds: "\(#awsPrefix)_cognito_user_group": data.#aws_cognito_user_group
	_#ds: "\(#awsPrefix)_cognito_user_groups": data.#aws_cognito_user_groups
	_#ds: "\(#awsPrefix)_cognito_user_pool_client": data.#aws_cognito_user_pool_client
	_#ds: "\(#awsPrefix)_cognito_user_pool_clients": data.#aws_cognito_user_pool_clients
	_#ds: "\(#awsPrefix)_cognito_user_pool": data.#aws_cognito_user_pool
	_#ds: "\(#awsPrefix)_cognito_user_pool_signing_certificate": data.#aws_cognito_user_pool_signing_certificate
	_#ds: "\(#awsPrefix)_cognito_user_pools": data.#aws_cognito_user_pools
	_#ds: "\(#awsPrefix)_connect_bot_association": data.#aws_connect_bot_association
	_#ds: "\(#awsPrefix)_connect_contact_flow": data.#aws_connect_contact_flow
	_#ds: "\(#awsPrefix)_connect_contact_flow_module": data.#aws_connect_contact_flow_module
	_#ds: "\(#awsPrefix)_connect_hours_of_operation": data.#aws_connect_hours_of_operation
	_#ds: "\(#awsPrefix)_connect_instance": data.#aws_connect_instance
	_#ds: "\(#awsPrefix)_connect_instance_storage_config": data.#aws_connect_instance_storage_config
	_#ds: "\(#awsPrefix)_connect_lambda_function_association": data.#aws_connect_lambda_function_association
	_#ds: "\(#awsPrefix)_connect_prompt": data.#aws_connect_prompt
	_#ds: "\(#awsPrefix)_connect_queue": data.#aws_connect_queue
	_#ds: "\(#awsPrefix)_connect_quick_connect": data.#aws_connect_quick_connect
	_#ds: "\(#awsPrefix)_connect_routing_profile": data.#aws_connect_routing_profile
	_#ds: "\(#awsPrefix)_connect_security_profile": data.#aws_connect_security_profile
	_#ds: "\(#awsPrefix)_connect_user": data.#aws_connect_user
	_#ds: "\(#awsPrefix)_connect_user_hierarchy_group": data.#aws_connect_user_hierarchy_group
	_#ds: "\(#awsPrefix)_connect_user_hierarchy_structure": data.#aws_connect_user_hierarchy_structure
	_#ds: "\(#awsPrefix)_connect_vocabulary": data.#aws_connect_vocabulary
	_#ds: "\(#awsPrefix)_controltower_controls": data.#aws_controltower_controls
	_#ds: "\(#awsPrefix)_cur_report_definition": data.#aws_cur_report_definition
	_#ds: "\(#awsPrefix)_customer_gateway": data.#aws_customer_gateway
	_#ds: "\(#awsPrefix)_datapipeline_pipeline_definition": data.#aws_datapipeline_pipeline_definition
	_#ds: "\(#awsPrefix)_datapipeline_pipeline": data.#aws_datapipeline_pipeline
	_#ds: "\(#awsPrefix)_datazone_domain": data.#aws_datazone_domain
	_#ds: "\(#awsPrefix)_datazone_environment_blueprint": data.#aws_datazone_environment_blueprint
	_#ds: "\(#awsPrefix)_db_cluster_snapshot": data.#aws_db_cluster_snapshot
	_#ds: "\(#awsPrefix)_db_event_categories": data.#aws_db_event_categories
	_#ds: "\(#awsPrefix)_db_instance": data.#aws_db_instance
	_#ds: "\(#awsPrefix)_db_instances": data.#aws_db_instances
	_#ds: "\(#awsPrefix)_db_parameter_group": data.#aws_db_parameter_group
	_#ds: "\(#awsPrefix)_db_proxy": data.#aws_db_proxy
	_#ds: "\(#awsPrefix)_db_snapshot": data.#aws_db_snapshot
	_#ds: "\(#awsPrefix)_db_subnet_group": data.#aws_db_subnet_group
	_#ds: "\(#awsPrefix)_default_tags": data.#aws_default_tags
	_#ds: "\(#awsPrefix)_devopsguru_notification_channel": data.#aws_devopsguru_notification_channel
	_#ds: "\(#awsPrefix)_devopsguru_resource_collection": data.#aws_devopsguru_resource_collection
	_#ds: "\(#awsPrefix)_directory_service_directory": data.#aws_directory_service_directory
	_#ds: "\(#awsPrefix)_dms_certificate": data.#aws_dms_certificate
	_#ds: "\(#awsPrefix)_dms_endpoint": data.#aws_dms_endpoint
	_#ds: "\(#awsPrefix)_dms_replication_instance": data.#aws_dms_replication_instance
	_#ds: "\(#awsPrefix)_dms_replication_subnet_group": data.#aws_dms_replication_subnet_group
	_#ds: "\(#awsPrefix)_dms_replication_task": data.#aws_dms_replication_task
	_#ds: "\(#awsPrefix)_docdb_engine_version": data.#aws_docdb_engine_version
	_#ds: "\(#awsPrefix)_docdb_orderable_db_instance": data.#aws_docdb_orderable_db_instance
	_#ds: "\(#awsPrefix)_dx_connection": data.#aws_dx_connection
	_#ds: "\(#awsPrefix)_dx_gateway": data.#aws_dx_gateway
	_#ds: "\(#awsPrefix)_dx_location": data.#aws_dx_location
	_#ds: "\(#awsPrefix)_dx_locations": data.#aws_dx_locations
	_#ds: "\(#awsPrefix)_dx_router_configuration": data.#aws_dx_router_configuration
	_#ds: "\(#awsPrefix)_dynamodb_table": data.#aws_dynamodb_table
	_#ds: "\(#awsPrefix)_dynamodb_table_item": data.#aws_dynamodb_table_item
	_#ds: "\(#awsPrefix)_dynamodb_tables": data.#aws_dynamodb_tables
	_#ds: "\(#awsPrefix)_ebs_default_kms_key": data.#aws_ebs_default_kms_key
	_#ds: "\(#awsPrefix)_ebs_encryption_by_default": data.#aws_ebs_encryption_by_default
	_#ds: "\(#awsPrefix)_ebs_snapshot": data.#aws_ebs_snapshot
	_#ds: "\(#awsPrefix)_ebs_snapshot_ids": data.#aws_ebs_snapshot_ids
	_#ds: "\(#awsPrefix)_ebs_volume": data.#aws_ebs_volume
	_#ds: "\(#awsPrefix)_ebs_volumes": data.#aws_ebs_volumes
	_#ds: "\(#awsPrefix)_ec2_capacity_block_offering": data.#aws_ec2_capacity_block_offering
	_#ds: "\(#awsPrefix)_ec2_client_vpn_endpoint": data.#aws_ec2_client_vpn_endpoint
	_#ds: "\(#awsPrefix)_ec2_coip_pool": data.#aws_ec2_coip_pool
	_#ds: "\(#awsPrefix)_ec2_coip_pools": data.#aws_ec2_coip_pools
	_#ds: "\(#awsPrefix)_ec2_host": data.#aws_ec2_host
	_#ds: "\(#awsPrefix)_ec2_instance_type": data.#aws_ec2_instance_type
	_#ds: "\(#awsPrefix)_ec2_instance_type_offering": data.#aws_ec2_instance_type_offering
	_#ds: "\(#awsPrefix)_ec2_instance_type_offerings": data.#aws_ec2_instance_type_offerings
	_#ds: "\(#awsPrefix)_ec2_instance_types": data.#aws_ec2_instance_types
	_#ds: "\(#awsPrefix)_ec2_local_gateway": data.#aws_ec2_local_gateway
	_#ds: "\(#awsPrefix)_ec2_local_gateway_route_table": data.#aws_ec2_local_gateway_route_table
	_#ds: "\(#awsPrefix)_ec2_local_gateway_route_tables": data.#aws_ec2_local_gateway_route_tables
	_#ds: "\(#awsPrefix)_ec2_local_gateway_virtual_interface": data.#aws_ec2_local_gateway_virtual_interface
	_#ds: "\(#awsPrefix)_ec2_local_gateway_virtual_interface_group": data.#aws_ec2_local_gateway_virtual_interface_group
	_#ds: "\(#awsPrefix)_ec2_local_gateway_virtual_interface_groups": data.#aws_ec2_local_gateway_virtual_interface_groups
	_#ds: "\(#awsPrefix)_ec2_local_gateways": data.#aws_ec2_local_gateways
	_#ds: "\(#awsPrefix)_ec2_managed_prefix_list": data.#aws_ec2_managed_prefix_list
	_#ds: "\(#awsPrefix)_ec2_managed_prefix_lists": data.#aws_ec2_managed_prefix_lists
	_#ds: "\(#awsPrefix)_ec2_network_insights_analysis": data.#aws_ec2_network_insights_analysis
	_#ds: "\(#awsPrefix)_ec2_network_insights_path": data.#aws_ec2_network_insights_path
	_#ds: "\(#awsPrefix)_ec2_public_ipv4_pool": data.#aws_ec2_public_ipv4_pool
	_#ds: "\(#awsPrefix)_ec2_public_ipv4_pools": data.#aws_ec2_public_ipv4_pools
	_#ds: "\(#awsPrefix)_ec2_serial_console_access": data.#aws_ec2_serial_console_access
	_#ds: "\(#awsPrefix)_ec2_spot_price": data.#aws_ec2_spot_price
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_attachment": data.#aws_ec2_transit_gateway_attachment
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_attachments": data.#aws_ec2_transit_gateway_attachments
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_connect": data.#aws_ec2_transit_gateway_connect
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_connect_peer": data.#aws_ec2_transit_gateway_connect_peer
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_dx_gateway_attachment": data.#aws_ec2_transit_gateway_dx_gateway_attachment
	_#ds: "\(#awsPrefix)_ec2_transit_gateway": data.#aws_ec2_transit_gateway
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_multicast_domain": data.#aws_ec2_transit_gateway_multicast_domain
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_peering_attachment": data.#aws_ec2_transit_gateway_peering_attachment
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_peering_attachments": data.#aws_ec2_transit_gateway_peering_attachments
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_route_table_associations": data.#aws_ec2_transit_gateway_route_table_associations
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_route_table": data.#aws_ec2_transit_gateway_route_table
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_route_table_propagations": data.#aws_ec2_transit_gateway_route_table_propagations
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_route_table_routes": data.#aws_ec2_transit_gateway_route_table_routes
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_route_tables": data.#aws_ec2_transit_gateway_route_tables
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_vpc_attachment": data.#aws_ec2_transit_gateway_vpc_attachment
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_vpc_attachments": data.#aws_ec2_transit_gateway_vpc_attachments
	_#ds: "\(#awsPrefix)_ec2_transit_gateway_vpn_attachment": data.#aws_ec2_transit_gateway_vpn_attachment
	_#ds: "\(#awsPrefix)_ecr_authorization_token": data.#aws_ecr_authorization_token
	_#ds: "\(#awsPrefix)_ecr_image": data.#aws_ecr_image
	_#ds: "\(#awsPrefix)_ecr_images": data.#aws_ecr_images
	_#ds: "\(#awsPrefix)_ecr_lifecycle_policy_document": data.#aws_ecr_lifecycle_policy_document
	_#ds: "\(#awsPrefix)_ecr_pull_through_cache_rule": data.#aws_ecr_pull_through_cache_rule
	_#ds: "\(#awsPrefix)_ecr_repositories": data.#aws_ecr_repositories
	_#ds: "\(#awsPrefix)_ecr_repository_creation_template": data.#aws_ecr_repository_creation_template
	_#ds: "\(#awsPrefix)_ecr_repository": data.#aws_ecr_repository
	_#ds: "\(#awsPrefix)_ecrpublic_authorization_token": data.#aws_ecrpublic_authorization_token
	_#ds: "\(#awsPrefix)_ecrpublic_images": data.#aws_ecrpublic_images
	_#ds: "\(#awsPrefix)_ecs_cluster": data.#aws_ecs_cluster
	_#ds: "\(#awsPrefix)_ecs_clusters": data.#aws_ecs_clusters
	_#ds: "\(#awsPrefix)_ecs_container_definition": data.#aws_ecs_container_definition
	_#ds: "\(#awsPrefix)_ecs_service": data.#aws_ecs_service
	_#ds: "\(#awsPrefix)_ecs_task_definition": data.#aws_ecs_task_definition
	_#ds: "\(#awsPrefix)_ecs_task_execution": data.#aws_ecs_task_execution
	_#ds: "\(#awsPrefix)_efs_access_point": data.#aws_efs_access_point
	_#ds: "\(#awsPrefix)_efs_access_points": data.#aws_efs_access_points
	_#ds: "\(#awsPrefix)_efs_file_system": data.#aws_efs_file_system
	_#ds: "\(#awsPrefix)_efs_mount_target": data.#aws_efs_mount_target
	_#ds: "\(#awsPrefix)_eip": data.#aws_eip
	_#ds: "\(#awsPrefix)_eips": data.#aws_eips
	_#ds: "\(#awsPrefix)_eks_access_entry": data.#aws_eks_access_entry
	_#ds: "\(#awsPrefix)_eks_addon": data.#aws_eks_addon
	_#ds: "\(#awsPrefix)_eks_addon_version": data.#aws_eks_addon_version
	_#ds: "\(#awsPrefix)_eks_cluster_auth": data.#aws_eks_cluster_auth
	_#ds: "\(#awsPrefix)_eks_cluster": data.#aws_eks_cluster
	_#ds: "\(#awsPrefix)_eks_cluster_versions": data.#aws_eks_cluster_versions
	_#ds: "\(#awsPrefix)_eks_clusters": data.#aws_eks_clusters
	_#ds: "\(#awsPrefix)_eks_node_group": data.#aws_eks_node_group
	_#ds: "\(#awsPrefix)_eks_node_groups": data.#aws_eks_node_groups
	_#ds: "\(#awsPrefix)_elastic_beanstalk_application": data.#aws_elastic_beanstalk_application
	_#ds: "\(#awsPrefix)_elastic_beanstalk_hosted_zone": data.#aws_elastic_beanstalk_hosted_zone
	_#ds: "\(#awsPrefix)_elastic_beanstalk_solution_stack": data.#aws_elastic_beanstalk_solution_stack
	_#ds: "\(#awsPrefix)_elasticache_cluster": data.#aws_elasticache_cluster
	_#ds: "\(#awsPrefix)_elasticache_replication_group": data.#aws_elasticache_replication_group
	_#ds: "\(#awsPrefix)_elasticache_reserved_cache_node_offering": data.#aws_elasticache_reserved_cache_node_offering
	_#ds: "\(#awsPrefix)_elasticache_serverless_cache": data.#aws_elasticache_serverless_cache
	_#ds: "\(#awsPrefix)_elasticache_subnet_group": data.#aws_elasticache_subnet_group
	_#ds: "\(#awsPrefix)_elasticache_user": data.#aws_elasticache_user
	_#ds: "\(#awsPrefix)_elasticsearch_domain": data.#aws_elasticsearch_domain
	_#ds: "\(#awsPrefix)_elb": data.#aws_elb
	_#ds: "\(#awsPrefix)_elb_hosted_zone_id": data.#aws_elb_hosted_zone_id
	_#ds: "\(#awsPrefix)_elb_service_account": data.#aws_elb_service_account
	_#ds: "\(#awsPrefix)_emr_release_labels": data.#aws_emr_release_labels
	_#ds: "\(#awsPrefix)_emr_supported_instance_types": data.#aws_emr_supported_instance_types
	_#ds: "\(#awsPrefix)_emrcontainers_virtual_cluster": data.#aws_emrcontainers_virtual_cluster
	_#ds: "\(#awsPrefix)_fis_experiment_templates": data.#aws_fis_experiment_templates
	_#ds: "\(#awsPrefix)_fsx_ontap_file_system": data.#aws_fsx_ontap_file_system
	_#ds: "\(#awsPrefix)_fsx_ontap_storage_virtual_machine": data.#aws_fsx_ontap_storage_virtual_machine
	_#ds: "\(#awsPrefix)_fsx_ontap_storage_virtual_machines": data.#aws_fsx_ontap_storage_virtual_machines
	_#ds: "\(#awsPrefix)_fsx_openzfs_snapshot": data.#aws_fsx_openzfs_snapshot
	_#ds: "\(#awsPrefix)_fsx_windows_file_system": data.#aws_fsx_windows_file_system
	_#ds: "\(#awsPrefix)_globalaccelerator_accelerator": data.#aws_globalaccelerator_accelerator
	_#ds: "\(#awsPrefix)_globalaccelerator_custom_routing_accelerator": data.#aws_globalaccelerator_custom_routing_accelerator
	_#ds: "\(#awsPrefix)_glue_catalog_table": data.#aws_glue_catalog_table
	_#ds: "\(#awsPrefix)_glue_connection": data.#aws_glue_connection
	_#ds: "\(#awsPrefix)_glue_data_catalog_encryption_settings": data.#aws_glue_data_catalog_encryption_settings
	_#ds: "\(#awsPrefix)_glue_registry": data.#aws_glue_registry
	_#ds: "\(#awsPrefix)_glue_script": data.#aws_glue_script
	_#ds: "\(#awsPrefix)_grafana_workspace": data.#aws_grafana_workspace
	_#ds: "\(#awsPrefix)_guardduty_detector": data.#aws_guardduty_detector
	_#ds: "\(#awsPrefix)_guardduty_finding_ids": data.#aws_guardduty_finding_ids
	_#ds: "\(#awsPrefix)_iam_access_keys": data.#aws_iam_access_keys
	_#ds: "\(#awsPrefix)_iam_account_alias": data.#aws_iam_account_alias
	_#ds: "\(#awsPrefix)_iam_group": data.#aws_iam_group
	_#ds: "\(#awsPrefix)_iam_instance_profile": data.#aws_iam_instance_profile
	_#ds: "\(#awsPrefix)_iam_instance_profiles": data.#aws_iam_instance_profiles
	_#ds: "\(#awsPrefix)_iam_openid_connect_provider": data.#aws_iam_openid_connect_provider
	_#ds: "\(#awsPrefix)_iam_policy_document": data.#aws_iam_policy_document
	_#ds: "\(#awsPrefix)_iam_policy": data.#aws_iam_policy
	_#ds: "\(#awsPrefix)_iam_principal_policy_simulation": data.#aws_iam_principal_policy_simulation
	_#ds: "\(#awsPrefix)_iam_role": data.#aws_iam_role
	_#ds: "\(#awsPrefix)_iam_roles": data.#aws_iam_roles
	_#ds: "\(#awsPrefix)_iam_saml_provider": data.#aws_iam_saml_provider
	_#ds: "\(#awsPrefix)_iam_server_certificate": data.#aws_iam_server_certificate
	_#ds: "\(#awsPrefix)_iam_session_context": data.#aws_iam_session_context
	_#ds: "\(#awsPrefix)_iam_user": data.#aws_iam_user
	_#ds: "\(#awsPrefix)_iam_user_ssh_key": data.#aws_iam_user_ssh_key
	_#ds: "\(#awsPrefix)_iam_users": data.#aws_iam_users
	_#ds: "\(#awsPrefix)_identitystore_group": data.#aws_identitystore_group
	_#ds: "\(#awsPrefix)_identitystore_group_memberships": data.#aws_identitystore_group_memberships
	_#ds: "\(#awsPrefix)_identitystore_groups": data.#aws_identitystore_groups
	_#ds: "\(#awsPrefix)_identitystore_user": data.#aws_identitystore_user
	_#ds: "\(#awsPrefix)_identitystore_users": data.#aws_identitystore_users
	_#ds: "\(#awsPrefix)_imagebuilder_component": data.#aws_imagebuilder_component
	_#ds: "\(#awsPrefix)_imagebuilder_components": data.#aws_imagebuilder_components
	_#ds: "\(#awsPrefix)_imagebuilder_container_recipe": data.#aws_imagebuilder_container_recipe
	_#ds: "\(#awsPrefix)_imagebuilder_container_recipes": data.#aws_imagebuilder_container_recipes
	_#ds: "\(#awsPrefix)_imagebuilder_distribution_configuration": data.#aws_imagebuilder_distribution_configuration
	_#ds: "\(#awsPrefix)_imagebuilder_distribution_configurations": data.#aws_imagebuilder_distribution_configurations
	_#ds: "\(#awsPrefix)_imagebuilder_image": data.#aws_imagebuilder_image
	_#ds: "\(#awsPrefix)_imagebuilder_image_pipeline": data.#aws_imagebuilder_image_pipeline
	_#ds: "\(#awsPrefix)_imagebuilder_image_pipelines": data.#aws_imagebuilder_image_pipelines
	_#ds: "\(#awsPrefix)_imagebuilder_image_recipe": data.#aws_imagebuilder_image_recipe
	_#ds: "\(#awsPrefix)_imagebuilder_image_recipes": data.#aws_imagebuilder_image_recipes
	_#ds: "\(#awsPrefix)_imagebuilder_infrastructure_configuration": data.#aws_imagebuilder_infrastructure_configuration
	_#ds: "\(#awsPrefix)_imagebuilder_infrastructure_configurations": data.#aws_imagebuilder_infrastructure_configurations
	_#ds: "\(#awsPrefix)_inspector_rules_packages": data.#aws_inspector_rules_packages
	_#ds: "\(#awsPrefix)_instance": data.#aws_instance
	_#ds: "\(#awsPrefix)_instances": data.#aws_instances
	_#ds: "\(#awsPrefix)_internet_gateway": data.#aws_internet_gateway
	_#ds: "\(#awsPrefix)_iot_endpoint": data.#aws_iot_endpoint
	_#ds: "\(#awsPrefix)_iot_registration_code": data.#aws_iot_registration_code
	_#ds: "\(#awsPrefix)_ip_ranges": data.#aws_ip_ranges
	_#ds: "\(#awsPrefix)_ivs_stream_key": data.#aws_ivs_stream_key
	_#ds: "\(#awsPrefix)_kendra_experience": data.#aws_kendra_experience
	_#ds: "\(#awsPrefix)_kendra_faq": data.#aws_kendra_faq
	_#ds: "\(#awsPrefix)_kendra_index": data.#aws_kendra_index
	_#ds: "\(#awsPrefix)_kendra_query_suggestions_block_list": data.#aws_kendra_query_suggestions_block_list
	_#ds: "\(#awsPrefix)_kendra_thesaurus": data.#aws_kendra_thesaurus
	_#ds: "\(#awsPrefix)_key_pair": data.#aws_key_pair
	_#ds: "\(#awsPrefix)_kinesis_firehose_delivery_stream": data.#aws_kinesis_firehose_delivery_stream
	_#ds: "\(#awsPrefix)_kinesis_stream_consumer": data.#aws_kinesis_stream_consumer
	_#ds: "\(#awsPrefix)_kinesis_stream": data.#aws_kinesis_stream
	_#ds: "\(#awsPrefix)_kms_alias": data.#aws_kms_alias
	_#ds: "\(#awsPrefix)_kms_ciphertext": data.#aws_kms_ciphertext
	_#ds: "\(#awsPrefix)_kms_custom_key_store": data.#aws_kms_custom_key_store
	_#ds: "\(#awsPrefix)_kms_key": data.#aws_kms_key
	_#ds: "\(#awsPrefix)_kms_public_key": data.#aws_kms_public_key
	_#ds: "\(#awsPrefix)_kms_secret": data.#aws_kms_secret
	_#ds: "\(#awsPrefix)_kms_secrets": data.#aws_kms_secrets
	_#ds: "\(#awsPrefix)_lakeformation_data_lake_settings": data.#aws_lakeformation_data_lake_settings
	_#ds: "\(#awsPrefix)_lakeformation_permissions": data.#aws_lakeformation_permissions
	_#ds: "\(#awsPrefix)_lakeformation_resource": data.#aws_lakeformation_resource
	_#ds: "\(#awsPrefix)_lambda_alias": data.#aws_lambda_alias
	_#ds: "\(#awsPrefix)_lambda_code_signing_config": data.#aws_lambda_code_signing_config
	_#ds: "\(#awsPrefix)_lambda_function": data.#aws_lambda_function
	_#ds: "\(#awsPrefix)_lambda_function_url": data.#aws_lambda_function_url
	_#ds: "\(#awsPrefix)_lambda_functions": data.#aws_lambda_functions
	_#ds: "\(#awsPrefix)_lambda_invocation": data.#aws_lambda_invocation
	_#ds: "\(#awsPrefix)_lambda_layer_version": data.#aws_lambda_layer_version
	_#ds: "\(#awsPrefix)_launch_configuration": data.#aws_launch_configuration
	_#ds: "\(#awsPrefix)_launch_template": data.#aws_launch_template
	_#ds: "\(#awsPrefix)_lb": data.#aws_lb
	_#ds: "\(#awsPrefix)_lb_hosted_zone_id": data.#aws_lb_hosted_zone_id
	_#ds: "\(#awsPrefix)_lb_listener": data.#aws_lb_listener
	_#ds: "\(#awsPrefix)_lb_listener_rule": data.#aws_lb_listener_rule
	_#ds: "\(#awsPrefix)_lb_target_group": data.#aws_lb_target_group
	_#ds: "\(#awsPrefix)_lb_trust_store": data.#aws_lb_trust_store
	_#ds: "\(#awsPrefix)_lbs": data.#aws_lbs
	_#ds: "\(#awsPrefix)_lex_bot_alias": data.#aws_lex_bot_alias
	_#ds: "\(#awsPrefix)_lex_bot": data.#aws_lex_bot
	_#ds: "\(#awsPrefix)_lex_intent": data.#aws_lex_intent
	_#ds: "\(#awsPrefix)_lex_slot_type": data.#aws_lex_slot_type
	_#ds: "\(#awsPrefix)_licensemanager_grants": data.#aws_licensemanager_grants
	_#ds: "\(#awsPrefix)_licensemanager_received_license": data.#aws_licensemanager_received_license
	_#ds: "\(#awsPrefix)_licensemanager_received_licenses": data.#aws_licensemanager_received_licenses
	_#ds: "\(#awsPrefix)_location_geofence_collection": data.#aws_location_geofence_collection
	_#ds: "\(#awsPrefix)_location_map": data.#aws_location_map
	_#ds: "\(#awsPrefix)_location_place_index": data.#aws_location_place_index
	_#ds: "\(#awsPrefix)_location_route_calculator": data.#aws_location_route_calculator
	_#ds: "\(#awsPrefix)_location_tracker_association": data.#aws_location_tracker_association
	_#ds: "\(#awsPrefix)_location_tracker_associations": data.#aws_location_tracker_associations
	_#ds: "\(#awsPrefix)_location_tracker": data.#aws_location_tracker
	_#ds: "\(#awsPrefix)_media_convert_queue": data.#aws_media_convert_queue
	_#ds: "\(#awsPrefix)_medialive_input": data.#aws_medialive_input
	_#ds: "\(#awsPrefix)_memorydb_acl": data.#aws_memorydb_acl
	_#ds: "\(#awsPrefix)_memorydb_cluster": data.#aws_memorydb_cluster
	_#ds: "\(#awsPrefix)_memorydb_parameter_group": data.#aws_memorydb_parameter_group
	_#ds: "\(#awsPrefix)_memorydb_snapshot": data.#aws_memorydb_snapshot
	_#ds: "\(#awsPrefix)_memorydb_subnet_group": data.#aws_memorydb_subnet_group
	_#ds: "\(#awsPrefix)_memorydb_user": data.#aws_memorydb_user
	_#ds: "\(#awsPrefix)_mq_broker_engine_types": data.#aws_mq_broker_engine_types
	_#ds: "\(#awsPrefix)_mq_broker": data.#aws_mq_broker
	_#ds: "\(#awsPrefix)_mq_broker_instance_type_offerings": data.#aws_mq_broker_instance_type_offerings
	_#ds: "\(#awsPrefix)_msk_bootstrap_brokers": data.#aws_msk_bootstrap_brokers
	_#ds: "\(#awsPrefix)_msk_broker_nodes": data.#aws_msk_broker_nodes
	_#ds: "\(#awsPrefix)_msk_cluster": data.#aws_msk_cluster
	_#ds: "\(#awsPrefix)_msk_configuration": data.#aws_msk_configuration
	_#ds: "\(#awsPrefix)_msk_kafka_version": data.#aws_msk_kafka_version
	_#ds: "\(#awsPrefix)_msk_vpc_connection": data.#aws_msk_vpc_connection
	_#ds: "\(#awsPrefix)_mskconnect_connector": data.#aws_mskconnect_connector
	_#ds: "\(#awsPrefix)_mskconnect_custom_plugin": data.#aws_mskconnect_custom_plugin
	_#ds: "\(#awsPrefix)_mskconnect_worker_configuration": data.#aws_mskconnect_worker_configuration
	_#ds: "\(#awsPrefix)_nat_gateway": data.#aws_nat_gateway
	_#ds: "\(#awsPrefix)_nat_gateways": data.#aws_nat_gateways
	_#ds: "\(#awsPrefix)_neptune_engine_version": data.#aws_neptune_engine_version
	_#ds: "\(#awsPrefix)_neptune_orderable_db_instance": data.#aws_neptune_orderable_db_instance
	_#ds: "\(#awsPrefix)_network_acls": data.#aws_network_acls
	_#ds: "\(#awsPrefix)_network_interface": data.#aws_network_interface
	_#ds: "\(#awsPrefix)_network_interfaces": data.#aws_network_interfaces
	_#ds: "\(#awsPrefix)_networkfirewall_firewall": data.#aws_networkfirewall_firewall
	_#ds: "\(#awsPrefix)_networkfirewall_firewall_policy": data.#aws_networkfirewall_firewall_policy
	_#ds: "\(#awsPrefix)_networkfirewall_resource_policy": data.#aws_networkfirewall_resource_policy
	_#ds: "\(#awsPrefix)_networkmanager_connection": data.#aws_networkmanager_connection
	_#ds: "\(#awsPrefix)_networkmanager_connections": data.#aws_networkmanager_connections
	_#ds: "\(#awsPrefix)_networkmanager_core_network_policy_document": data.#aws_networkmanager_core_network_policy_document
	_#ds: "\(#awsPrefix)_networkmanager_device": data.#aws_networkmanager_device
	_#ds: "\(#awsPrefix)_networkmanager_devices": data.#aws_networkmanager_devices
	_#ds: "\(#awsPrefix)_networkmanager_global_network": data.#aws_networkmanager_global_network
	_#ds: "\(#awsPrefix)_networkmanager_global_networks": data.#aws_networkmanager_global_networks
	_#ds: "\(#awsPrefix)_networkmanager_link": data.#aws_networkmanager_link
	_#ds: "\(#awsPrefix)_networkmanager_links": data.#aws_networkmanager_links
	_#ds: "\(#awsPrefix)_networkmanager_site": data.#aws_networkmanager_site
	_#ds: "\(#awsPrefix)_networkmanager_sites": data.#aws_networkmanager_sites
	_#ds: "\(#awsPrefix)_oam_link": data.#aws_oam_link
	_#ds: "\(#awsPrefix)_oam_links": data.#aws_oam_links
	_#ds: "\(#awsPrefix)_oam_sink": data.#aws_oam_sink
	_#ds: "\(#awsPrefix)_oam_sinks": data.#aws_oam_sinks
	_#ds: "\(#awsPrefix)_odb_cloud_autonomous_vm_cluster": data.#aws_odb_cloud_autonomous_vm_cluster
	_#ds: "\(#awsPrefix)_odb_cloud_autonomous_vm_clusters": data.#aws_odb_cloud_autonomous_vm_clusters
	_#ds: "\(#awsPrefix)_odb_cloud_exadata_infrastructure": data.#aws_odb_cloud_exadata_infrastructure
	_#ds: "\(#awsPrefix)_odb_cloud_exadata_infrastructures": data.#aws_odb_cloud_exadata_infrastructures
	_#ds: "\(#awsPrefix)_odb_cloud_vm_cluster": data.#aws_odb_cloud_vm_cluster
	_#ds: "\(#awsPrefix)_odb_cloud_vm_clusters": data.#aws_odb_cloud_vm_clusters
	_#ds: "\(#awsPrefix)_odb_db_node": data.#aws_odb_db_node
	_#ds: "\(#awsPrefix)_odb_db_nodes": data.#aws_odb_db_nodes
	_#ds: "\(#awsPrefix)_odb_db_server": data.#aws_odb_db_server
	_#ds: "\(#awsPrefix)_odb_db_servers": data.#aws_odb_db_servers
	_#ds: "\(#awsPrefix)_odb_db_system_shapes": data.#aws_odb_db_system_shapes
	_#ds: "\(#awsPrefix)_odb_gi_versions": data.#aws_odb_gi_versions
	_#ds: "\(#awsPrefix)_odb_network": data.#aws_odb_network
	_#ds: "\(#awsPrefix)_odb_network_peering_connection": data.#aws_odb_network_peering_connection
	_#ds: "\(#awsPrefix)_odb_network_peering_connections": data.#aws_odb_network_peering_connections
	_#ds: "\(#awsPrefix)_odb_networks": data.#aws_odb_networks
	_#ds: "\(#awsPrefix)_opensearch_domain": data.#aws_opensearch_domain
	_#ds: "\(#awsPrefix)_opensearchserverless_access_policy": data.#aws_opensearchserverless_access_policy
	_#ds: "\(#awsPrefix)_opensearchserverless_collection": data.#aws_opensearchserverless_collection
	_#ds: "\(#awsPrefix)_opensearchserverless_lifecycle_policy": data.#aws_opensearchserverless_lifecycle_policy
	_#ds: "\(#awsPrefix)_opensearchserverless_security_config": data.#aws_opensearchserverless_security_config
	_#ds: "\(#awsPrefix)_opensearchserverless_security_policy": data.#aws_opensearchserverless_security_policy
	_#ds: "\(#awsPrefix)_opensearchserverless_vpc_endpoint": data.#aws_opensearchserverless_vpc_endpoint
	_#ds: "\(#awsPrefix)_organizations_delegated_administrators": data.#aws_organizations_delegated_administrators
	_#ds: "\(#awsPrefix)_organizations_delegated_services": data.#aws_organizations_delegated_services
	_#ds: "\(#awsPrefix)_organizations_organization": data.#aws_organizations_organization
	_#ds: "\(#awsPrefix)_organizations_organizational_unit_child_accounts": data.#aws_organizations_organizational_unit_child_accounts
	_#ds: "\(#awsPrefix)_organizations_organizational_unit_descendant_accounts": data.#aws_organizations_organizational_unit_descendant_accounts
	_#ds: "\(#awsPrefix)_organizations_organizational_unit_descendant_organizational_units": data.#aws_organizations_organizational_unit_descendant_organizational_units
	_#ds: "\(#awsPrefix)_organizations_organizational_unit": data.#aws_organizations_organizational_unit
	_#ds: "\(#awsPrefix)_organizations_organizational_units": data.#aws_organizations_organizational_units
	_#ds: "\(#awsPrefix)_organizations_policies_for_target": data.#aws_organizations_policies_for_target
	_#ds: "\(#awsPrefix)_organizations_policies": data.#aws_organizations_policies
	_#ds: "\(#awsPrefix)_organizations_policy": data.#aws_organizations_policy
	_#ds: "\(#awsPrefix)_organizations_resource_tags": data.#aws_organizations_resource_tags
	_#ds: "\(#awsPrefix)_outposts_asset": data.#aws_outposts_asset
	_#ds: "\(#awsPrefix)_outposts_assets": data.#aws_outposts_assets
	_#ds: "\(#awsPrefix)_outposts_outpost": data.#aws_outposts_outpost
	_#ds: "\(#awsPrefix)_outposts_outpost_instance_type": data.#aws_outposts_outpost_instance_type
	_#ds: "\(#awsPrefix)_outposts_outpost_instance_types": data.#aws_outposts_outpost_instance_types
	_#ds: "\(#awsPrefix)_outposts_outposts": data.#aws_outposts_outposts
	_#ds: "\(#awsPrefix)_outposts_site": data.#aws_outposts_site
	_#ds: "\(#awsPrefix)_outposts_sites": data.#aws_outposts_sites
	_#ds: "\(#awsPrefix)_partition": data.#aws_partition
	_#ds: "\(#awsPrefix)_polly_voices": data.#aws_polly_voices
	_#ds: "\(#awsPrefix)_prefix_list": data.#aws_prefix_list
	_#ds: "\(#awsPrefix)_pricing_product": data.#aws_pricing_product
	_#ds: "\(#awsPrefix)_prometheus_default_scraper_configuration": data.#aws_prometheus_default_scraper_configuration
	_#ds: "\(#awsPrefix)_prometheus_workspace": data.#aws_prometheus_workspace
	_#ds: "\(#awsPrefix)_prometheus_workspaces": data.#aws_prometheus_workspaces
	_#ds: "\(#awsPrefix)_qldb_ledger": data.#aws_qldb_ledger
	_#ds: "\(#awsPrefix)_quicksight_analysis": data.#aws_quicksight_analysis
	_#ds: "\(#awsPrefix)_quicksight_data_set": data.#aws_quicksight_data_set
	_#ds: "\(#awsPrefix)_quicksight_group": data.#aws_quicksight_group
	_#ds: "\(#awsPrefix)_quicksight_theme": data.#aws_quicksight_theme
	_#ds: "\(#awsPrefix)_quicksight_user": data.#aws_quicksight_user
	_#ds: "\(#awsPrefix)_ram_resource_share": data.#aws_ram_resource_share
	_#ds: "\(#awsPrefix)_rds_certificate": data.#aws_rds_certificate
	_#ds: "\(#awsPrefix)_rds_cluster": data.#aws_rds_cluster
	_#ds: "\(#awsPrefix)_rds_cluster_parameter_group": data.#aws_rds_cluster_parameter_group
	_#ds: "\(#awsPrefix)_rds_clusters": data.#aws_rds_clusters
	_#ds: "\(#awsPrefix)_rds_engine_version": data.#aws_rds_engine_version
	_#ds: "\(#awsPrefix)_rds_global_cluster": data.#aws_rds_global_cluster
	_#ds: "\(#awsPrefix)_rds_orderable_db_instance": data.#aws_rds_orderable_db_instance
	_#ds: "\(#awsPrefix)_rds_reserved_instance_offering": data.#aws_rds_reserved_instance_offering
	_#ds: "\(#awsPrefix)_redshift_cluster_credentials": data.#aws_redshift_cluster_credentials
	_#ds: "\(#awsPrefix)_redshift_cluster": data.#aws_redshift_cluster
	_#ds: "\(#awsPrefix)_redshift_data_shares": data.#aws_redshift_data_shares
	_#ds: "\(#awsPrefix)_redshift_orderable_cluster": data.#aws_redshift_orderable_cluster
	_#ds: "\(#awsPrefix)_redshift_producer_data_shares": data.#aws_redshift_producer_data_shares
	_#ds: "\(#awsPrefix)_redshift_subnet_group": data.#aws_redshift_subnet_group
	_#ds: "\(#awsPrefix)_redshiftserverless_credentials": data.#aws_redshiftserverless_credentials
	_#ds: "\(#awsPrefix)_redshiftserverless_namespace": data.#aws_redshiftserverless_namespace
	_#ds: "\(#awsPrefix)_redshiftserverless_workgroup": data.#aws_redshiftserverless_workgroup
	_#ds: "\(#awsPrefix)_region": data.#aws_region
	_#ds: "\(#awsPrefix)_regions": data.#aws_regions
	_#ds: "\(#awsPrefix)_resourceexplorer2_search": data.#aws_resourceexplorer2_search
	_#ds: "\(#awsPrefix)_resourcegroupstaggingapi_resources": data.#aws_resourcegroupstaggingapi_resources
	_#ds: "\(#awsPrefix)_route53_delegation_set": data.#aws_route53_delegation_set
	_#ds: "\(#awsPrefix)_route53_records": data.#aws_route53_records
	_#ds: "\(#awsPrefix)_route53_resolver_endpoint": data.#aws_route53_resolver_endpoint
	_#ds: "\(#awsPrefix)_route53_resolver_firewall_config": data.#aws_route53_resolver_firewall_config
	_#ds: "\(#awsPrefix)_route53_resolver_firewall_domain_list": data.#aws_route53_resolver_firewall_domain_list
	_#ds: "\(#awsPrefix)_route53_resolver_firewall_rule_group_association": data.#aws_route53_resolver_firewall_rule_group_association
	_#ds: "\(#awsPrefix)_route53_resolver_firewall_rule_group": data.#aws_route53_resolver_firewall_rule_group
	_#ds: "\(#awsPrefix)_route53_resolver_firewall_rules": data.#aws_route53_resolver_firewall_rules
	_#ds: "\(#awsPrefix)_route53_resolver_query_log_config": data.#aws_route53_resolver_query_log_config
	_#ds: "\(#awsPrefix)_route53_resolver_rule": data.#aws_route53_resolver_rule
	_#ds: "\(#awsPrefix)_route53_resolver_rules": data.#aws_route53_resolver_rules
	_#ds: "\(#awsPrefix)_route53_traffic_policy_document": data.#aws_route53_traffic_policy_document
	_#ds: "\(#awsPrefix)_route53_zone": data.#aws_route53_zone
	_#ds: "\(#awsPrefix)_route53_zones": data.#aws_route53_zones
	_#ds: "\(#awsPrefix)_route53profiles_profiles": data.#aws_route53profiles_profiles
	_#ds: "\(#awsPrefix)_route": data.#aws_route
	_#ds: "\(#awsPrefix)_route_table": data.#aws_route_table
	_#ds: "\(#awsPrefix)_route_tables": data.#aws_route_tables
	_#ds: "\(#awsPrefix)_s3_access_point": data.#aws_s3_access_point
	_#ds: "\(#awsPrefix)_s3_account_public_access_block": data.#aws_s3_account_public_access_block
	_#ds: "\(#awsPrefix)_s3_bucket": data.#aws_s3_bucket
	_#ds: "\(#awsPrefix)_s3_bucket_object": data.#aws_s3_bucket_object
	_#ds: "\(#awsPrefix)_s3_bucket_objects": data.#aws_s3_bucket_objects
	_#ds: "\(#awsPrefix)_s3_bucket_policy": data.#aws_s3_bucket_policy
	_#ds: "\(#awsPrefix)_s3_directory_buckets": data.#aws_s3_directory_buckets
	_#ds: "\(#awsPrefix)_s3_object": data.#aws_s3_object
	_#ds: "\(#awsPrefix)_s3_objects": data.#aws_s3_objects
	_#ds: "\(#awsPrefix)_s3control_multi_region_access_point": data.#aws_s3control_multi_region_access_point
	_#ds: "\(#awsPrefix)_sagemaker_prebuilt_ecr_image": data.#aws_sagemaker_prebuilt_ecr_image
	_#ds: "\(#awsPrefix)_secretsmanager_random_password": data.#aws_secretsmanager_random_password
	_#ds: "\(#awsPrefix)_secretsmanager_secret": data.#aws_secretsmanager_secret
	_#ds: "\(#awsPrefix)_secretsmanager_secret_rotation": data.#aws_secretsmanager_secret_rotation
	_#ds: "\(#awsPrefix)_secretsmanager_secret_version": data.#aws_secretsmanager_secret_version
	_#ds: "\(#awsPrefix)_secretsmanager_secret_versions": data.#aws_secretsmanager_secret_versions
	_#ds: "\(#awsPrefix)_secretsmanager_secrets": data.#aws_secretsmanager_secrets
	_#ds: "\(#awsPrefix)_security_group": data.#aws_security_group
	_#ds: "\(#awsPrefix)_security_groups": data.#aws_security_groups
	_#ds: "\(#awsPrefix)_securityhub_standards_control_associations": data.#aws_securityhub_standards_control_associations
	_#ds: "\(#awsPrefix)_serverlessapplicationrepository_application": data.#aws_serverlessapplicationrepository_application
	_#ds: "\(#awsPrefix)_service_discovery_dns_namespace": data.#aws_service_discovery_dns_namespace
	_#ds: "\(#awsPrefix)_service_discovery_http_namespace": data.#aws_service_discovery_http_namespace
	_#ds: "\(#awsPrefix)_service_discovery_service": data.#aws_service_discovery_service
	_#ds: "\(#awsPrefix)_service": data.#aws_service
	_#ds: "\(#awsPrefix)_service_principal": data.#aws_service_principal
	_#ds: "\(#awsPrefix)_servicecatalog_constraint": data.#aws_servicecatalog_constraint
	_#ds: "\(#awsPrefix)_servicecatalog_launch_paths": data.#aws_servicecatalog_launch_paths
	_#ds: "\(#awsPrefix)_servicecatalog_portfolio_constraints": data.#aws_servicecatalog_portfolio_constraints
	_#ds: "\(#awsPrefix)_servicecatalog_portfolio": data.#aws_servicecatalog_portfolio
	_#ds: "\(#awsPrefix)_servicecatalog_product": data.#aws_servicecatalog_product
	_#ds: "\(#awsPrefix)_servicecatalog_provisioning_artifacts": data.#aws_servicecatalog_provisioning_artifacts
	_#ds: "\(#awsPrefix)_servicecatalogappregistry_application": data.#aws_servicecatalogappregistry_application
	_#ds: "\(#awsPrefix)_servicecatalogappregistry_attribute_group_associations": data.#aws_servicecatalogappregistry_attribute_group_associations
	_#ds: "\(#awsPrefix)_servicecatalogappregistry_attribute_group": data.#aws_servicecatalogappregistry_attribute_group
	_#ds: "\(#awsPrefix)_servicequotas_service": data.#aws_servicequotas_service
	_#ds: "\(#awsPrefix)_servicequotas_service_quota": data.#aws_servicequotas_service_quota
	_#ds: "\(#awsPrefix)_servicequotas_templates": data.#aws_servicequotas_templates
	_#ds: "\(#awsPrefix)_ses_active_receipt_rule_set": data.#aws_ses_active_receipt_rule_set
	_#ds: "\(#awsPrefix)_ses_domain_identity": data.#aws_ses_domain_identity
	_#ds: "\(#awsPrefix)_ses_email_identity": data.#aws_ses_email_identity
	_#ds: "\(#awsPrefix)_sesv2_configuration_set": data.#aws_sesv2_configuration_set
	_#ds: "\(#awsPrefix)_sesv2_dedicated_ip_pool": data.#aws_sesv2_dedicated_ip_pool
	_#ds: "\(#awsPrefix)_sesv2_email_identity": data.#aws_sesv2_email_identity
	_#ds: "\(#awsPrefix)_sesv2_email_identity_mail_from_attributes": data.#aws_sesv2_email_identity_mail_from_attributes
	_#ds: "\(#awsPrefix)_sfn_activity": data.#aws_sfn_activity
	_#ds: "\(#awsPrefix)_sfn_alias": data.#aws_sfn_alias
	_#ds: "\(#awsPrefix)_sfn_state_machine": data.#aws_sfn_state_machine
	_#ds: "\(#awsPrefix)_sfn_state_machine_versions": data.#aws_sfn_state_machine_versions
	_#ds: "\(#awsPrefix)_shield_protection": data.#aws_shield_protection
	_#ds: "\(#awsPrefix)_signer_signing_job": data.#aws_signer_signing_job
	_#ds: "\(#awsPrefix)_signer_signing_profile": data.#aws_signer_signing_profile
	_#ds: "\(#awsPrefix)_sns_topic": data.#aws_sns_topic
	_#ds: "\(#awsPrefix)_spot_datafeed_subscription": data.#aws_spot_datafeed_subscription
	_#ds: "\(#awsPrefix)_sqs_queue": data.#aws_sqs_queue
	_#ds: "\(#awsPrefix)_sqs_queues": data.#aws_sqs_queues
	_#ds: "\(#awsPrefix)_ssm_document": data.#aws_ssm_document
	_#ds: "\(#awsPrefix)_ssm_instances": data.#aws_ssm_instances
	_#ds: "\(#awsPrefix)_ssm_maintenance_windows": data.#aws_ssm_maintenance_windows
	_#ds: "\(#awsPrefix)_ssm_parameter": data.#aws_ssm_parameter
	_#ds: "\(#awsPrefix)_ssm_parameters_by_path": data.#aws_ssm_parameters_by_path
	_#ds: "\(#awsPrefix)_ssm_patch_baseline": data.#aws_ssm_patch_baseline
	_#ds: "\(#awsPrefix)_ssm_patch_baselines": data.#aws_ssm_patch_baselines
	_#ds: "\(#awsPrefix)_ssmcontacts_contact_channel": data.#aws_ssmcontacts_contact_channel
	_#ds: "\(#awsPrefix)_ssmcontacts_contact": data.#aws_ssmcontacts_contact
	_#ds: "\(#awsPrefix)_ssmcontacts_plan": data.#aws_ssmcontacts_plan
	_#ds: "\(#awsPrefix)_ssmcontacts_rotation": data.#aws_ssmcontacts_rotation
	_#ds: "\(#awsPrefix)_ssmincidents_replication_set": data.#aws_ssmincidents_replication_set
	_#ds: "\(#awsPrefix)_ssmincidents_response_plan": data.#aws_ssmincidents_response_plan
	_#ds: "\(#awsPrefix)_ssoadmin_application_assignments": data.#aws_ssoadmin_application_assignments
	_#ds: "\(#awsPrefix)_ssoadmin_application": data.#aws_ssoadmin_application
	_#ds: "\(#awsPrefix)_ssoadmin_application_providers": data.#aws_ssoadmin_application_providers
	_#ds: "\(#awsPrefix)_ssoadmin_instances": data.#aws_ssoadmin_instances
	_#ds: "\(#awsPrefix)_ssoadmin_permission_set": data.#aws_ssoadmin_permission_set
	_#ds: "\(#awsPrefix)_ssoadmin_permission_sets": data.#aws_ssoadmin_permission_sets
	_#ds: "\(#awsPrefix)_ssoadmin_principal_application_assignments": data.#aws_ssoadmin_principal_application_assignments
	_#ds: "\(#awsPrefix)_storagegateway_local_disk": data.#aws_storagegateway_local_disk
	_#ds: "\(#awsPrefix)_subnet": data.#aws_subnet
	_#ds: "\(#awsPrefix)_subnets": data.#aws_subnets
	_#ds: "\(#awsPrefix)_synthetics_runtime_version": data.#aws_synthetics_runtime_version
	_#ds: "\(#awsPrefix)_synthetics_runtime_versions": data.#aws_synthetics_runtime_versions
	_#ds: "\(#awsPrefix)_timestreamwrite_database": data.#aws_timestreamwrite_database
	_#ds: "\(#awsPrefix)_timestreamwrite_table": data.#aws_timestreamwrite_table
	_#ds: "\(#awsPrefix)_transfer_connector": data.#aws_transfer_connector
	_#ds: "\(#awsPrefix)_transfer_server": data.#aws_transfer_server
	_#ds: "\(#awsPrefix)_verifiedpermissions_policy_store": data.#aws_verifiedpermissions_policy_store
	_#ds: "\(#awsPrefix)_vpc_dhcp_options": data.#aws_vpc_dhcp_options
	_#ds: "\(#awsPrefix)_vpc_endpoint_associations": data.#aws_vpc_endpoint_associations
	_#ds: "\(#awsPrefix)_vpc_endpoint": data.#aws_vpc_endpoint
	_#ds: "\(#awsPrefix)_vpc_endpoint_service": data.#aws_vpc_endpoint_service
	_#ds: "\(#awsPrefix)_vpc": data.#aws_vpc
	_#ds: "\(#awsPrefix)_vpc_ipam": data.#aws_vpc_ipam
	_#ds: "\(#awsPrefix)_vpc_ipam_pool_cidrs": data.#aws_vpc_ipam_pool_cidrs
	_#ds: "\(#awsPrefix)_vpc_ipam_pool": data.#aws_vpc_ipam_pool
	_#ds: "\(#awsPrefix)_vpc_ipam_pools": data.#aws_vpc_ipam_pools
	_#ds: "\(#awsPrefix)_vpc_ipam_preview_next_cidr": data.#aws_vpc_ipam_preview_next_cidr
	_#ds: "\(#awsPrefix)_vpc_ipams": data.#aws_vpc_ipams
	_#ds: "\(#awsPrefix)_vpc_peering_connection": data.#aws_vpc_peering_connection
	_#ds: "\(#awsPrefix)_vpc_peering_connections": data.#aws_vpc_peering_connections
	_#ds: "\(#awsPrefix)_vpc_security_group_rule": data.#aws_vpc_security_group_rule
	_#ds: "\(#awsPrefix)_vpc_security_group_rules": data.#aws_vpc_security_group_rules
	_#ds: "\(#awsPrefix)_vpclattice_auth_policy": data.#aws_vpclattice_auth_policy
	_#ds: "\(#awsPrefix)_vpclattice_listener": data.#aws_vpclattice_listener
	_#ds: "\(#awsPrefix)_vpclattice_resource_policy": data.#aws_vpclattice_resource_policy
	_#ds: "\(#awsPrefix)_vpclattice_service": data.#aws_vpclattice_service
	_#ds: "\(#awsPrefix)_vpclattice_service_network": data.#aws_vpclattice_service_network
	_#ds: "\(#awsPrefix)_vpcs": data.#aws_vpcs
	_#ds: "\(#awsPrefix)_vpn_connection": data.#aws_vpn_connection
	_#ds: "\(#awsPrefix)_vpn_gateway": data.#aws_vpn_gateway
	_#ds: "\(#awsPrefix)_waf_ipset": data.#aws_waf_ipset
	_#ds: "\(#awsPrefix)_waf_rate_based_rule": data.#aws_waf_rate_based_rule
	_#ds: "\(#awsPrefix)_waf_rule": data.#aws_waf_rule
	_#ds: "\(#awsPrefix)_waf_subscribed_rule_group": data.#aws_waf_subscribed_rule_group
	_#ds: "\(#awsPrefix)_waf_web_acl": data.#aws_waf_web_acl
	_#ds: "\(#awsPrefix)_wafregional_ipset": data.#aws_wafregional_ipset
	_#ds: "\(#awsPrefix)_wafregional_rate_based_rule": data.#aws_wafregional_rate_based_rule
	_#ds: "\(#awsPrefix)_wafregional_rule": data.#aws_wafregional_rule
	_#ds: "\(#awsPrefix)_wafregional_subscribed_rule_group": data.#aws_wafregional_subscribed_rule_group
	_#ds: "\(#awsPrefix)_wafregional_web_acl": data.#aws_wafregional_web_acl
	_#ds: "\(#awsPrefix)_wafv2_ip_set": data.#aws_wafv2_ip_set
	_#ds: "\(#awsPrefix)_wafv2_regex_pattern_set": data.#aws_wafv2_regex_pattern_set
	_#ds: "\(#awsPrefix)_wafv2_rule_group": data.#aws_wafv2_rule_group
	_#ds: "\(#awsPrefix)_wafv2_web_acl": data.#aws_wafv2_web_acl
	_#ds: "\(#awsPrefix)_workspaces_bundle": data.#aws_workspaces_bundle
	_#ds: "\(#awsPrefix)_workspaces_directory": data.#aws_workspaces_directory
	_#ds: "\(#awsPrefix)_workspaces_image": data.#aws_workspaces_image
	_#ds: "\(#awsPrefix)_workspaces_workspace": data.#aws_workspaces_workspace

}
