package aws

#provider: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/provider")
	close({
		access_key?: string
		allowed_account_ids?: [...string]
		custom_ca_bundle?:                   string
		ec2_metadata_service_endpoint?:      string
		ec2_metadata_service_endpoint_mode?: string
		forbidden_account_ids?: [...string]
		http_proxy?:                     string
		https_proxy?:                    string
		insecure?:                       bool
		max_retries?:                    number
		no_proxy?:                       string
		profile?:                        string
		region?:                         string
		retry_mode?:                     string
		s3_us_east_1_regional_endpoint?: string
		s3_use_path_style?:              bool
		secret_key?:                     string
		shared_config_files?: [...string]
		shared_credentials_files?: [...string]
		skip_credentials_validation?: bool
		skip_metadata_api_check?:     string
		skip_region_validation?:      bool
		skip_requesting_account_id?:  bool
		assume_role?: matchN(1, [#assume_role, [...#assume_role]])
		sts_region?:                         string
		token?:                              string
		token_bucket_rate_limiter_capacity?: number
		use_dualstack_endpoint?:             bool
		assume_role_with_web_identity?: matchN(1, [#assume_role_with_web_identity, [...#assume_role_with_web_identity]])
		default_tags?: matchN(1, [#default_tags, [...#default_tags]])
		endpoints?: matchN(1, [#endpoints, [...#endpoints]])
		ignore_tags?: matchN(1, [#ignore_tags, [...#ignore_tags]])
		use_fips_endpoint?: bool
	})

	#assume_role: close({
		duration?:    string
		external_id?: string
		policy?:      string
		policy_arns?: [...string]
		role_arn?:        string
		session_name?:    string
		source_identity?: string
		tags?: [string]: string
		transitive_tag_keys?: [...string]
	})

	#assume_role_with_web_identity: close({
		duration?: string
		policy?:   string
		policy_arns?: [...string]
		role_arn?:                string
		session_name?:            string
		web_identity_token?:      string
		web_identity_token_file?: string
	})

	#default_tags: close({
		tags?: [string]: string
	})

	#endpoints: close({
		accessanalyzer?:                       string
		account?:                              string
		acm?:                                  string
		acmpca?:                               string
		amg?:                                  string
		amp?:                                  string
		amplify?:                              string
		apigateway?:                           string
		apigatewayv2?:                         string
		appautoscaling?:                       string
		appconfig?:                            string
		appfabric?:                            string
		appflow?:                              string
		appintegrations?:                      string
		appintegrationsservice?:               string
		applicationautoscaling?:               string
		applicationinsights?:                  string
		applicationsignals?:                   string
		appmesh?:                              string
		appregistry?:                          string
		apprunner?:                            string
		appstream?:                            string
		appsync?:                              string
		athena?:                               string
		auditmanager?:                         string
		autoscaling?:                          string
		autoscalingplans?:                     string
		backup?:                               string
		batch?:                                string
		bcmdataexports?:                       string
		beanstalk?:                            string
		bedrock?:                              string
		bedrockagent?:                         string
		billing?:                              string
		budgets?:                              string
		ce?:                                   string
		chatbot?:                              string
		chime?:                                string
		chimesdkmediapipelines?:               string
		chimesdkvoice?:                        string
		cleanrooms?:                           string
		cloud9?:                               string
		cloudcontrol?:                         string
		cloudcontrolapi?:                      string
		cloudformation?:                       string
		cloudfront?:                           string
		cloudfrontkeyvaluestore?:              string
		cloudhsm?:                             string
		cloudhsmv2?:                           string
		cloudsearch?:                          string
		cloudtrail?:                           string
		cloudwatch?:                           string
		cloudwatchevents?:                     string
		cloudwatchevidently?:                  string
		cloudwatchlog?:                        string
		cloudwatchlogs?:                       string
		cloudwatchobservabilityaccessmanager?: string
		cloudwatchrum?:                        string
		codeartifact?:                         string
		codebuild?:                            string
		codecatalyst?:                         string
		codecommit?:                           string
		codeconnections?:                      string
		codedeploy?:                           string
		codeguruprofiler?:                     string
		codegurureviewer?:                     string
		codepipeline?:                         string
		codestarconnections?:                  string
		codestarnotifications?:                string
		cognitoidentity?:                      string
		cognitoidentityprovider?:              string
		cognitoidp?:                           string
		comprehend?:                           string
		computeoptimizer?:                     string
		config?:                               string
		configservice?:                        string
		connect?:                              string
		connectcases?:                         string
		controltower?:                         string
		costandusagereportservice?:            string
		costexplorer?:                         string
		costoptimizationhub?:                  string
		cur?:                                  string
		customerprofiles?:                     string
		databasemigration?:                    string
		databasemigrationservice?:             string
		databrew?:                             string
		dataexchange?:                         string
		datapipeline?:                         string
		datasync?:                             string
		datazone?:                             string
		dax?:                                  string
		deploy?:                               string
		detective?:                            string
		devicefarm?:                           string
		devopsguru?:                           string
		directconnect?:                        string
		directoryservice?:                     string
		dlm?:                                  string
		dms?:                                  string
		docdb?:                                string
		docdbelastic?:                         string
		drs?:                                  string
		ds?:                                   string
		dsql?:                                 string
		dynamodb?:                             string
		ec2?:                                  string
		ecr?:                                  string
		ecrpublic?:                            string
		ecs?:                                  string
		efs?:                                  string
		eks?:                                  string
		elasticache?:                          string
		elasticbeanstalk?:                     string
		elasticloadbalancing?:                 string
		elasticloadbalancingv2?:               string
		elasticsearch?:                        string
		elasticsearchservice?:                 string
		elastictranscoder?:                    string
		elb?:                                  string
		elbv2?:                                string
		emr?:                                  string
		emrcontainers?:                        string
		emrserverless?:                        string
		es?:                                   string
		eventbridge?:                          string
		events?:                               string
		evidently?:                            string
		evs?:                                  string
		finspace?:                             string
		firehose?:                             string
		fis?:                                  string
		fms?:                                  string
		fsx?:                                  string
		gamelift?:                             string
		glacier?:                              string
		globalaccelerator?:                    string
		glue?:                                 string
		gluedatabrew?:                         string
		grafana?:                              string
		greengrass?:                           string
		groundstation?:                        string
		guardduty?:                            string
		healthlake?:                           string
		iam?:                                  string
		identitystore?:                        string
		imagebuilder?:                         string
		inspector?:                            string
		inspector2?:                           string
		inspectorv2?:                          string
		internetmonitor?:                      string
		invoicing?:                            string
		iot?:                                  string
		ivs?:                                  string
		ivschat?:                              string
		kafka?:                                string
		kafkaconnect?:                         string
		kendra?:                               string
		keyspaces?:                            string
		kinesis?:                              string
		kinesisanalytics?:                     string
		kinesisanalyticsv2?:                   string
		kinesisvideo?:                         string
		kms?:                                  string
		lakeformation?:                        string
		lambda?:                               string
		launchwizard?:                         string
		lex?:                                  string
		lexmodelbuilding?:                     string
		lexmodelbuildingservice?:              string
		lexmodels?:                            string
		lexmodelsv2?:                          string
		lexv2models?:                          string
		licensemanager?:                       string
		lightsail?:                            string
		location?:                             string
		locationservice?:                      string
		logs?:                                 string
		lookoutmetrics?:                       string
		m2?:                                   string
		macie2?:                               string
		managedgrafana?:                       string
		mediaconnect?:                         string
		mediaconvert?:                         string
		medialive?:                            string
		mediapackage?:                         string
		mediapackagev2?:                       string
		mediapackagevod?:                      string
		mediastore?:                           string
		memorydb?:                             string
		mgn?:                                  string
		mq?:                                   string
		msk?:                                  string
		mwaa?:                                 string
		neptune?:                              string
		neptunegraph?:                         string
		networkfirewall?:                      string
		networkmanager?:                       string
		networkmonitor?:                       string
		notifications?:                        string
		notificationscontacts?:                string
		oam?:                                  string
		opensearch?:                           string
		opensearchingestion?:                  string
		opensearchserverless?:                 string
		opensearchservice?:                    string
		organizations?:                        string
		osis?:                                 string
		outposts?:                             string
		paymentcryptography?:                  string
		pcaconnectorad?:                       string
		pcs?:                                  string
		pinpoint?:                             string
		pinpointsmsvoicev2?:                   string
		pipes?:                                string
		polly?:                                string
		pricing?:                              string
		prometheus?:                           string
		prometheusservice?:                    string
		qbusiness?:                            string
		qldb?:                                 string
		quicksight?:                           string
		ram?:                                  string
		rbin?:                                 string
		rds?:                                  string
		recyclebin?:                           string
		redshift?:                             string
		redshiftdata?:                         string
		redshiftdataapiservice?:               string
		redshiftserverless?:                   string
		rekognition?:                          string
		resiliencehub?:                        string
		resourceexplorer2?:                    string
		resourcegroups?:                       string
		resourcegroupstagging?:                string
		resourcegroupstaggingapi?:             string
		rolesanywhere?:                        string
		route53?:                              string
		route53domains?:                       string
		route53profiles?:                      string
		route53recoverycontrolconfig?:         string
		route53recoveryreadiness?:             string
		route53resolver?:                      string
		rum?:                                  string
		s3?:                                   string
		s3api?:                                string
		s3control?:                            string
		s3outposts?:                           string
		s3tables?:                             string
		sagemaker?:                            string
		scheduler?:                            string
		schemas?:                              string
		secretsmanager?:                       string
		securityhub?:                          string
		securitylake?:                         string
		serverlessapplicationrepository?:      string
		serverlessapprepo?:                    string
		serverlessrepo?:                       string
		servicecatalog?:                       string
		servicecatalogappregistry?:            string
		servicediscovery?:                     string
		servicequotas?:                        string
		ses?:                                  string
		sesv2?:                                string
		sfn?:                                  string
		shield?:                               string
		signer?:                               string
		sns?:                                  string
		sqs?:                                  string
		ssm?:                                  string
		ssmcontacts?:                          string
		ssmincidents?:                         string
		ssmquicksetup?:                        string
		ssmsap?:                               string
		sso?:                                  string
		ssoadmin?:                             string
		stepfunctions?:                        string
		storagegateway?:                       string
		sts?:                                  string
		swf?:                                  string
		synthetics?:                           string
		taxsettings?:                          string
		timestreaminfluxdb?:                   string
		timestreamquery?:                      string
		timestreamwrite?:                      string
		transcribe?:                           string
		transcribeservice?:                    string
		transfer?:                             string
		verifiedpermissions?:                  string
		vpclattice?:                           string
		waf?:                                  string
		wafregional?:                          string
		wafv2?:                                string
		wellarchitected?:                      string
		workspaces?:                           string
		workspacesweb?:                        string
		xray?:                                 string
	})

	#ignore_tags: close({
		key_prefixes?: [...string]
		keys?: [...string]
	})
}
