package aws

#provider: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://rmazur.io/cuetf/schema/provider")
	access_key?: string
	allowed_account_ids?: [...string]
	custom_ca_bundle?:                   string
	ec2_metadata_service_endpoint?:      string
	ec2_metadata_service_endpoint_mode?: string
	forbidden_account_ids?: [...string]
	http_proxy?:                     string
	insecure?:                       bool
	max_retries?:                    number
	profile?:                        string
	region?:                         string
	retry_mode?:                     string
	s3_us_east_1_regional_endpoint?: string
	s3_use_path_style?:              bool
	secret_key?:                     string
	shared_config_files?: [...string]
	shared_credentials_files?: [...string]
	skip_credentials_validation?:   bool
	skip_metadata_api_check?:       string
	skip_region_validation?:        bool
	skip_requesting_account_id?:    bool
	sts_region?:                    string
	token?:                         string
	use_dualstack_endpoint?:        bool
	use_fips_endpoint?:             bool
	assume_role?:                   #assume_role | [...#assume_role]
	assume_role_with_web_identity?: #assume_role_with_web_identity | [...#assume_role_with_web_identity]
	default_tags?:                  #default_tags | [...#default_tags]
	endpoints?:                     #endpoints | [...#endpoints]
	ignore_tags?:                   #ignore_tags | [...#ignore_tags]

	#assume_role: {
		duration?:    string
		external_id?: string
		policy?:      string
		policy_arns?: [...string]
		role_arn?:        string
		session_name?:    string
		source_identity?: string
		tags?: [string]: string
		transitive_tag_keys?: [...string]
	}

	#assume_role_with_web_identity: {
		duration?: string
		policy?:   string
		policy_arns?: [...string]
		role_arn?:                string
		session_name?:            string
		web_identity_token?:      string
		web_identity_token_file?: string
	}

	#default_tags: tags?: [string]: string

	#endpoints: {
		accessanalyzer?:                       string
		account?:                              string
		acm?:                                  string
		acmpca?:                               string
		amg?:                                  string
		amp?:                                  string
		amplify?:                              string
		apigateway?:                           string
		apigatewayv2?:                         string
		appautoscaling?:                       string
		appconfig?:                            string
		appflow?:                              string
		appintegrations?:                      string
		appintegrationsservice?:               string
		applicationautoscaling?:               string
		applicationinsights?:                  string
		appmesh?:                              string
		apprunner?:                            string
		appstream?:                            string
		appsync?:                              string
		athena?:                               string
		auditmanager?:                         string
		autoscaling?:                          string
		autoscalingplans?:                     string
		backup?:                               string
		batch?:                                string
		beanstalk?:                            string
		bedrock?:                              string
		budgets?:                              string
		ce?:                                   string
		chime?:                                string
		chimesdkmediapipelines?:               string
		chimesdkvoice?:                        string
		cleanrooms?:                           string
		cloud9?:                               string
		cloudcontrol?:                         string
		cloudcontrolapi?:                      string
		cloudformation?:                       string
		cloudfront?:                           string
		cloudhsm?:                             string
		cloudhsmv2?:                           string
		cloudsearch?:                          string
		cloudtrail?:                           string
		cloudwatch?:                           string
		cloudwatchevents?:                     string
		cloudwatchevidently?:                  string
		cloudwatchlog?:                        string
		cloudwatchlogs?:                       string
		cloudwatchobservabilityaccessmanager?: string
		cloudwatchrum?:                        string
		codeartifact?:                         string
		codebuild?:                            string
		codecatalyst?:                         string
		codecommit?:                           string
		codedeploy?:                           string
		codegurureviewer?:                     string
		codepipeline?:                         string
		codestarconnections?:                  string
		codestarnotifications?:                string
		cognitoidentity?:                      string
		cognitoidentityprovider?:              string
		cognitoidp?:                           string
		comprehend?:                           string
		computeoptimizer?:                     string
		config?:                               string
		configservice?:                        string
		connect?:                              string
		controltower?:                         string
		costandusagereportservice?:            string
		costexplorer?:                         string
		cur?:                                  string
		databasemigration?:                    string
		databasemigrationservice?:             string
		dataexchange?:                         string
		datapipeline?:                         string
		datasync?:                             string
		dax?:                                  string
		deploy?:                               string
		detective?:                            string
		devicefarm?:                           string
		directconnect?:                        string
		directoryservice?:                     string
		dlm?:                                  string
		dms?:                                  string
		docdb?:                                string
		docdbelastic?:                         string
		ds?:                                   string
		dynamodb?:                             string
		ec2?:                                  string
		ecr?:                                  string
		ecrpublic?:                            string
		ecs?:                                  string
		efs?:                                  string
		eks?:                                  string
		elasticache?:                          string
		elasticbeanstalk?:                     string
		elasticloadbalancing?:                 string
		elasticloadbalancingv2?:               string
		elasticsearch?:                        string
		elasticsearchservice?:                 string
		elastictranscoder?:                    string
		elb?:                                  string
		elbv2?:                                string
		emr?:                                  string
		emrcontainers?:                        string
		emrserverless?:                        string
		es?:                                   string
		eventbridge?:                          string
		events?:                               string
		evidently?:                            string
		finspace?:                             string
		firehose?:                             string
		fis?:                                  string
		fms?:                                  string
		fsx?:                                  string
		gamelift?:                             string
		glacier?:                              string
		globalaccelerator?:                    string
		glue?:                                 string
		grafana?:                              string
		greengrass?:                           string
		guardduty?:                            string
		healthlake?:                           string
		iam?:                                  string
		identitystore?:                        string
		imagebuilder?:                         string
		inspector?:                            string
		inspector2?:                           string
		inspectorv2?:                          string
		internetmonitor?:                      string
		iot?:                                  string
		iotanalytics?:                         string
		iotevents?:                            string
		ivs?:                                  string
		ivschat?:                              string
		kafka?:                                string
		kafkaconnect?:                         string
		kendra?:                               string
		keyspaces?:                            string
		kinesis?:                              string
		kinesisanalytics?:                     string
		kinesisanalyticsv2?:                   string
		kinesisvideo?:                         string
		kms?:                                  string
		lakeformation?:                        string
		lambda?:                               string
		lex?:                                  string
		lexmodelbuilding?:                     string
		lexmodelbuildingservice?:              string
		lexmodels?:                            string
		lexmodelsv2?:                          string
		lexv2models?:                          string
		licensemanager?:                       string
		lightsail?:                            string
		location?:                             string
		locationservice?:                      string
		logs?:                                 string
		macie2?:                               string
		managedgrafana?:                       string
		mediaconnect?:                         string
		mediaconvert?:                         string
		medialive?:                            string
		mediapackage?:                         string
		mediastore?:                           string
		memorydb?:                             string
		mq?:                                   string
		msk?:                                  string
		mwaa?:                                 string
		neptune?:                              string
		networkfirewall?:                      string
		networkmanager?:                       string
		oam?:                                  string
		opensearch?:                           string
		opensearchserverless?:                 string
		opensearchservice?:                    string
		opsworks?:                             string
		organizations?:                        string
		outposts?:                             string
		pinpoint?:                             string
		pipes?:                                string
		pricing?:                              string
		prometheus?:                           string
		prometheusservice?:                    string
		qldb?:                                 string
		quicksight?:                           string
		ram?:                                  string
		rbin?:                                 string
		rds?:                                  string
		recyclebin?:                           string
		redshift?:                             string
		redshiftdata?:                         string
		redshiftdataapiservice?:               string
		redshiftserverless?:                   string
		resourceexplorer2?:                    string
		resourcegroups?:                       string
		resourcegroupstagging?:                string
		resourcegroupstaggingapi?:             string
		rolesanywhere?:                        string
		route53?:                              string
		route53domains?:                       string
		route53recoverycontrolconfig?:         string
		route53recoveryreadiness?:             string
		route53resolver?:                      string
		rum?:                                  string
		s3?:                                   string
		s3api?:                                string
		s3control?:                            string
		s3outposts?:                           string
		sagemaker?:                            string
		scheduler?:                            string
		schemas?:                              string
		sdb?:                                  string
		secretsmanager?:                       string
		securityhub?:                          string
		securitylake?:                         string
		serverlessapplicationrepository?:      string
		serverlessapprepo?:                    string
		serverlessrepo?:                       string
		servicecatalog?:                       string
		servicediscovery?:                     string
		servicequotas?:                        string
		ses?:                                  string
		sesv2?:                                string
		sfn?:                                  string
		shield?:                               string
		signer?:                               string
		simpledb?:                             string
		sns?:                                  string
		sqs?:                                  string
		ssm?:                                  string
		ssmcontacts?:                          string
		ssmincidents?:                         string
		ssoadmin?:                             string
		stepfunctions?:                        string
		storagegateway?:                       string
		sts?:                                  string
		swf?:                                  string
		synthetics?:                           string
		timestreamwrite?:                      string
		transcribe?:                           string
		transcribeservice?:                    string
		transfer?:                             string
		verifiedpermissions?:                  string
		vpclattice?:                           string
		waf?:                                  string
		wafregional?:                          string
		wafv2?:                                string
		worklink?:                             string
		workspaces?:                           string
		xray?:                                 string
	}

	#ignore_tags: {
		key_prefixes?: [...string]
		keys?: [...string]
	}
}
