package res

import "list"

#google_ces_agent: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_ces_agent")
	close({
		// The ID to use for the agent, which will become the final
		// component of
		// the agent's resource name. If not provided, a unique ID will be
		// automatically assigned for the agent.
		agent_id?: string
		after_agent_callbacks?: matchN(1, [#after_agent_callbacks, [...#after_agent_callbacks]])

		// Resource ID segment making up resource 'name'. It identifies
		// the resource within its parent collection as described in
		// https://google.aip.dev/122.
		app!: string

		// List of child agents in the agent tree.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/agents/{agent}'
		child_agents?: [...string]

		// Timestamp when the agent was created.
		create_time?: string

		// Human-readable description of the agent.
		description?: string

		// Display name of the agent.
		display_name!: string

		// Etag used to ensure the object hasn't changed during a
		// read-modify-write
		// operation. If the etag is empty, the update will overwrite any
		// concurrent
		// changes.
		etag?: string

		// If the agent is generated by the LLM assistant, this field
		// contains a
		// descriptive summary of the generation.
		generated_summary?: string

		// List of guardrails for the agent.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/guardrails/{guardrail}'
		guardrails?: [...string]
		id?: string
		after_model_callbacks?: matchN(1, [#after_model_callbacks, [...#after_model_callbacks]])
		after_tool_callbacks?: matchN(1, [#after_tool_callbacks, [...#after_tool_callbacks]])

		// Instructions for the LLM model to guide the agent's behavior.
		instruction?: string
		before_agent_callbacks?: matchN(1, [#before_agent_callbacks, [...#before_agent_callbacks]])
		before_model_callbacks?: matchN(1, [#before_model_callbacks, [...#before_model_callbacks]])
		before_tool_callbacks?: matchN(1, [#before_tool_callbacks, [...#before_tool_callbacks]])
		llm_agent?: matchN(1, [#llm_agent, list.MaxItems(1) & [...#llm_agent]])
		model_settings?: matchN(1, [#model_settings, list.MaxItems(1) & [...#model_settings]])
		remote_dialogflow_agent?: matchN(1, [#remote_dialogflow_agent, list.MaxItems(1) & [...#remote_dialogflow_agent]])
		timeouts?: #timeouts

		// Resource ID segment making up resource 'name'. It identifies
		// the resource within its parent collection as described in
		// https://google.aip.dev/122.
		location!: string

		// Identifier. The unique identifier of the agent.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/agents/{agent}'
		name?: string

		// List of available tools for the agent.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/tools/{tool}'
		tools?: [...string]
		project?: string

		// Timestamp when the agent was last updated.
		update_time?: string
		toolsets?: matchN(1, [#toolsets, [...#toolsets]])
	})

	#after_agent_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are
		// ignored by the
		// agent.
		disabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#after_model_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are
		// ignored by the
		// agent.
		disabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#after_tool_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are
		// ignored by the
		// agent.
		disabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#before_agent_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are
		// ignored by the
		// agent.
		disabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#before_model_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are
		// ignored by the
		// agent.
		disabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#before_tool_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are
		// ignored by the
		// agent.
		disabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#llm_agent: close({})

	#model_settings: close({
		// The LLM model that the agent should use.
		// If not set, the agent will inherit the model from its parent
		// agent.
		model?: string

		// If set, this temperature will be used for the LLM model.
		// Temperature
		// controls the randomness of the model's responses. Lower
		// temperatures
		// produce responses that are more predictable. Higher
		// temperatures produce
		// responses that are more creative.
		temperature?: number
	})

	#remote_dialogflow_agent: close({
		// The
		// [Dialogflow](https://cloud.google.com/dialogflow/cx/docs/concept/console-conversational-agents
		// agent resource name.
		// Format:
		// 'projects/{project}/locations/{location}/agents/{agent}'
		agent!: string

		// The environment ID of the Dialogflow agent be used for the
		// agent
		// execution. If not specified, the draft environment will be
		// used.
		environment_id?: string

		// The flow ID of the flow in the Dialogflow agent.
		flow_id!: string

		// The mapping of the app variables names to the Dialogflow
		// session
		// parameters names to be sent to the Dialogflow agent as input.
		input_variable_mapping?: [string]: string

		// The mapping of the Dialogflow session parameters names to the
		// app
		// variables names to be sent back to the CES agent after the
		// Dialogflow
		// agent execution ends.
		output_variable_mapping?: [string]: string
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})

	#toolsets: close({
		// The tools IDs to filter the toolset.
		tool_ids?: [...string]

		// The resource name of the toolset.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/toolsets/{toolset}'
		toolset!: string
	})
}
