package res

import "list"

#google_cloud_security_compliance_cloud_control: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_cloud_security_compliance_cloud_control")
	close({
		// The categories of the cloud control.
		categories?: [...string]

		// ID of the CloudControl.
		// This is the last segment of the CloudControl resource name.
		// Format: '^a-zA-Z{0,61}[a-zA-Z0-9]$'.
		cloud_control_id!: string

		// The last updated time of the cloud control.
		// The create_time is used because a new CC is created whenever we
		// update an
		// existing CC.
		create_time?: string

		// A description of the cloud control. The maximum length is 2000
		// characters.
		description?: string

		// The display name of the cloud control. The maximum length is
		// 200
		// characters.
		display_name?: string

		// The finding_category of the cloud control. The maximum length
		// is 255
		// characters.
		finding_category?: string
		id?:               string

		// Resource ID segment making up resource 'name'. It identifies
		// the resource within its parent collection as described in
		// https://google.aip.dev/122. Currently, only "global" is
		// supported as a location.
		location!: string

		// Major revision of the cloud control incremented in ascending
		// order.
		major_revision_id?: string

		// Identifier. The resource name of the cloud control.
		// Format:
		// organizations/{organization}/locations/{location}/cloudControls/{cloud_control_id}
		name?: string

		// Resource ID segment making up resource 'name'. It identifies
		// the resource within its parent collection as described in
		// https://google.aip.dev/122.
		organization!: string

		// The Frameworks that include this CloudControl
		related_frameworks?: [...string]
		parameter_spec?: matchN(1, [#parameter_spec, [...#parameter_spec]])
		rules?: matchN(1, [#rules, [...#rules]])
		timeouts?: #timeouts

		// The remediation steps for the findings generated by the cloud
		// control. The
		// maximum length is 400 characters.
		remediation_steps?: string

		// Possible values:
		// CRITICAL
		// HIGH
		// MEDIUM
		// LOW
		severity?: string

		// cloud providers supported
		supported_cloud_providers?: [...string]

		// The supported enforcement mode of the cloud control. Default is
		// DETECTIVE.
		supported_enforcement_modes?: [...string]

		// target resource types supported by the CloudControl.
		supported_target_resource_types?: [...string]
	})

	#parameter_spec: close({
		// The description of the parameter. The maximum length is 2000
		// characters.
		description?: string

		// The display name of the parameter. The maximum length is 200
		// characters.
		display_name?: string

		// if the parameter is required
		is_required!: bool

		// The name of the parameter.
		name!: string
		default_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/default_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/default_value"]])
		sub_parameters?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters", [..._#defs."/$defs/parameter_spec/$defs/sub_parameters"]])

		// Parameter value type.
		// Possible values:
		// STRING
		// BOOLEAN
		// STRINGLIST
		// NUMBER
		// ONEOF
		value_type!: string
		substitution_rules?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/substitution_rules", [..._#defs."/$defs/parameter_spec/$defs/substitution_rules"]])
		validation?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation"]])
	})

	#rules: close({
		cel_expression?: matchN(1, [_#defs."/$defs/rules/$defs/cel_expression", list.MaxItems(1) & [..._#defs."/$defs/rules/$defs/cel_expression"]])

		// Description of the Rule. The maximum length is 2000 characters.
		description?: string

		// The functionality enabled by the Rule.
		rule_action_types!: [...string]
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/default_value": close({
		// Represents a boolean value.
		bool_value?: bool

		// Represents a double value.
		number_value?: number
		oneof_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/default_value/$defs/oneof_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/default_value/$defs/oneof_value"]])

		// Represents a string value.
		string_value?: string
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/default_value/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/default_value/$defs/string_list_value"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/default_value/$defs/oneof_value": close({
		parameter_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/default_value/$defs/oneof_value/$defs/parameter_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/default_value/$defs/oneof_value/$defs/parameter_value"]])

		// The name of the parameter.
		name?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/default_value/$defs/oneof_value/$defs/parameter_value": close({
		// Represents a boolean value.
		bool_value?: bool
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/default_value/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/default_value/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value"]])

		// Represents a double value.
		number_value?: number

		// Represents a string value.
		string_value?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/default_value/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/default_value/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters": close({
		// The description of the parameter. The maximum length is 2000
		// characters.
		description?: string

		// The display name of the parameter. The maximum length is 200
		// characters.
		display_name?: string

		// if the parameter is required
		is_required!: bool

		// The name of the parameter.
		name!: string

		// Parameter value type.
		// Possible values:
		// STRING
		// BOOLEAN
		// STRINGLIST
		// NUMBER
		// ONEOF
		value_type!: string
		default_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value"]])
		substitution_rules?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules", [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules"]])
		validation?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value": close({
		// Represents a boolean value.
		bool_value?: bool

		// Represents a double value.
		number_value?: number
		oneof_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value"]])

		// Represents a string value.
		string_value?: string
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/string_list_value"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value": close({
		parameter_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value/$defs/parameter_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value/$defs/parameter_value"]])

		// The name of the parameter.
		name?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value/$defs/parameter_value": close({
		// Represents a boolean value.
		bool_value?: bool
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value"]])

		// Represents a double value.
		number_value?: number

		// Represents a string value.
		string_value?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/default_value/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules": close({
		attribute_substitution_rule?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules/$defs/attribute_substitution_rule", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules/$defs/attribute_substitution_rule"]])
		placeholder_substitution_rule?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules/$defs/placeholder_substitution_rule", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules/$defs/placeholder_substitution_rule"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules/$defs/attribute_substitution_rule": close({
		// Fully qualified proto attribute path (in dot notation).
		// Example: rules[0].cel_expression.resource_types_values
		attribute?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/substitution_rules/$defs/placeholder_substitution_rule": close({
		// Fully qualified proto attribute path (e.g., dot notation)
		attribute?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation": close({
		allowed_values?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values"]])
		int_range?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/int_range", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/int_range"]])
		regexp_pattern?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/regexp_pattern", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/regexp_pattern"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values": close({
		values!: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values", [_, ...] & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values": close({
		// Represents a boolean value.
		bool_value?: bool

		// Represents a double value.
		number_value?: number
		oneof_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value"]])

		// Represents a string value.
		string_value?: string
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/string_list_value"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value": close({
		parameter_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value"]])

		// The name of the parameter.
		name?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value": close({
		// Represents a boolean value.
		bool_value?: bool
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value"]])

		// Represents a double value.
		number_value?: number

		// Represents a string value.
		string_value?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/allowed_values/$defs/values/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/int_range": close({
		// Maximum allowed value for the numeric parameter (inclusive).
		max!: string

		// Minimum allowed value for the numeric parameter (inclusive).
		min!: string
	})

	_#defs: "/$defs/parameter_spec/$defs/sub_parameters/$defs/validation/$defs/regexp_pattern": close({
		// Regex Pattern to match the value(s) of parameter.
		pattern!: string
	})

	_#defs: "/$defs/parameter_spec/$defs/substitution_rules": close({
		attribute_substitution_rule?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/substitution_rules/$defs/attribute_substitution_rule", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/substitution_rules/$defs/attribute_substitution_rule"]])
		placeholder_substitution_rule?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/substitution_rules/$defs/placeholder_substitution_rule", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/substitution_rules/$defs/placeholder_substitution_rule"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/substitution_rules/$defs/attribute_substitution_rule": close({
		// Fully qualified proto attribute path (in dot notation).
		// Example: rules[0].cel_expression.resource_types_values
		attribute?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/substitution_rules/$defs/placeholder_substitution_rule": close({
		// Fully qualified proto attribute path (e.g., dot notation)
		attribute?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/validation": close({
		allowed_values?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values"]])
		int_range?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/int_range", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/int_range"]])
		regexp_pattern?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/regexp_pattern", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/regexp_pattern"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/allowed_values": close({
		values!: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values", [_, ...] & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values": close({
		// Represents a boolean value.
		bool_value?: bool

		// Represents a double value.
		number_value?: number
		oneof_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value"]])

		// Represents a string value.
		string_value?: string
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/string_list_value"]])
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value": close({
		parameter_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value"]])

		// The name of the parameter.
		name?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value": close({
		// Represents a boolean value.
		bool_value?: bool
		string_list_value?: matchN(1, [_#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value", list.MaxItems(1) & [..._#defs."/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value"]])

		// Represents a double value.
		number_value?: number

		// Represents a string value.
		string_value?: string
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/oneof_value/$defs/parameter_value/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/allowed_values/$defs/values/$defs/string_list_value": close({
		// The strings in the list.
		values!: [...string]
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/int_range": close({
		// Maximum allowed value for the numeric parameter (inclusive).
		max!: string

		// Minimum allowed value for the numeric parameter (inclusive).
		min!: string
	})

	_#defs: "/$defs/parameter_spec/$defs/validation/$defs/regexp_pattern": close({
		// Regex Pattern to match the value(s) of parameter.
		pattern!: string
	})

	_#defs: "/$defs/rules/$defs/cel_expression": close({
		resource_types_values?: matchN(1, [_#defs."/$defs/rules/$defs/cel_expression/$defs/resource_types_values", list.MaxItems(1) & [..._#defs."/$defs/rules/$defs/cel_expression/$defs/resource_types_values"]])

		// Logic expression in CEL language.
		// The max length of the condition is 1000 characters.
		expression!: string
	})

	_#defs: "/$defs/rules/$defs/cel_expression/$defs/resource_types_values": close({
		// The strings in the list.
		values!: [...string]
	})
}
