package res

#google_endpoints_service: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_endpoints_service")
	close({
		// A list of API objects.
		apis?: [...close({
			methods?: [...close({
				name?:          string
				request_type?:  string
				response_type?: string
				syntax?:        string
			})]
			name?:    string
			syntax?:  string
			version?: string
		})]

		// The autogenerated ID for the configuration that is rolled out
		// as part of the creation of this resource. Must be provided to
		// compute engine instances as a tag.
		config_id?: string

		// The address at which the service can be found - usually the
		// same as the service name.
		dns_address?: string

		// A list of Endpoint objects.
		endpoints?: [...close({
			address?: string
			name?:    string
		})]

		// The full text of the Service Config YAML file (Example located
		// here). If provided, must also provide protoc_output_base64.
		// open_api config must not be provided.
		grpc_config?: string
		id?:          string

		// The full text of the OpenAPI YAML configuration as described
		// here. Either this, or both of grpc_config and
		// protoc_output_base64 must be specified.
		openapi_config?: string
		timeouts?:       #timeouts

		// The project ID that the service belongs to. If not provided,
		// provider project is used.
		project?: string

		// The full contents of the Service Descriptor File generated by
		// protoc. This should be a compiled .pb file, base64-encoded.
		protoc_output_base64?: string

		// The name of the service. Usually of the form
		// $apiname.endpoints.$projectid.cloud.goog.
		service_name!: string
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})
}
