package res

import "list"

#google_ces_tool: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_ces_tool")
	close({
		// Resource ID segment making up resource 'name'. It identifies
		// the resource within its parent collection as described in
		// https://google.aip.dev/122.
		app!: string
		client_function?: matchN(1, [#client_function, list.MaxItems(1) & [...#client_function]])

		// Timestamp when the tool was created.
		create_time?: string

		// The display name of the tool, derived based on the tool's type.
		// For
		// example, display name of a ClientFunction is derived
		// from its 'name' property.
		display_name?: string

		// Etag used to ensure the object hasn't changed during a
		// read-modify-write
		// operation. If the etag is empty, the update will overwrite any
		// concurrent
		// changes.
		etag?: string

		// Possible values:
		// SYNCHRONOUS
		// ASYNCHRONOUS
		execution_type?: string

		// If the tool is generated by the LLM assistant, this field
		// contains a
		// descriptive summary of the generation.
		generated_summary?: string
		id?:                string

		// Resource ID segment making up resource 'name'. It identifies
		// the resource within its parent collection as described in
		// https://google.aip.dev/122.
		location!: string

		// Identifier. The unique identifier of the tool.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/tools/{tool}'
		name?: string
		data_store_tool?: matchN(1, [#data_store_tool, list.MaxItems(1) & [...#data_store_tool]])
		google_search_tool?: matchN(1, [#google_search_tool, list.MaxItems(1) & [...#google_search_tool]])
		python_function?: matchN(1, [#python_function, list.MaxItems(1) & [...#python_function]])
		timeouts?: #timeouts

		// A remote API tool defined by an OpenAPI schema.
		open_api_tool?: [...close({
			api_authentication?: [...close({
				api_key_config?: [...close({
					api_key_secret_version?: string
					key_name?:               string
					request_location?:       string
				})]
				oauth_config?: [...close({
					client_id?:             string
					client_secret_version?: string
					oauth_grant_type?:      string
					scopes?: [...string]
					token_endpoint?: string
				})]
				service_account_auth_config?: [...close({
					service_account?: string
				})]
				service_agent_id_token_auth_config?: [...close({})]
			})]
			description?:           string
			ignore_unknown_fields?: bool
			name?:                  string
			open_api_schema?:       string
			service_directory_config?: [...close({
				service?: string
			})]
			tls_config?: [...close({
				ca_certs?: [...close({
					cert?:         string
					display_name?: string
				})]
			})]
			url?: string
		})]
		project?: string

		// The system tool.
		system_tool?: [...close({
			description?: string
			name?:        string
		})]

		// The ID to use for the tool, which will become the final
		// component of
		// the tool's resource name. If not provided, a unique ID will be
		// automatically assigned for the tool.
		tool_id!: string

		// Timestamp when the tool was last updated.
		update_time?: string
	})

	#client_function: close({
		parameters?: matchN(1, [_#defs."/$defs/client_function/$defs/parameters", list.MaxItems(1) & [..._#defs."/$defs/client_function/$defs/parameters"]])
		response?: matchN(1, [_#defs."/$defs/client_function/$defs/response", list.MaxItems(1) & [..._#defs."/$defs/client_function/$defs/response"]])

		// The function description.
		description?: string

		// The function name.
		name!: string
	})

	#data_store_tool: close({
		// The tool description.
		description?: string
		boost_specs?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/boost_specs", [..._#defs."/$defs/data_store_tool/$defs/boost_specs"]])

		// Number of search results to return per query.
		// The default value is 10. The maximum allowed value is 10.
		max_results?: number

		// The data store tool name.
		name!: string
		engine_source?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/engine_source", list.MaxItems(1) & [..._#defs."/$defs/data_store_tool/$defs/engine_source"]])
		modality_configs?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/modality_configs", [..._#defs."/$defs/data_store_tool/$defs/modality_configs"]])
	})

	#google_search_tool: close({
		// Description of the tool's purpose.
		description?: string

		// List of domains to be excluded from the search results.
		// Example: "example.com".
		// A maximum of 2000 domains can be excluded.
		exclude_domains?: [...string]

		// The name of the tool.
		name!: string
	})

	#python_function: close({
		// The description of the Python function, parsed from the python
		// code's
		// docstring.
		description?: string

		// The name of the Python function to execute. Must match a Python
		// function
		// name defined in the python code. Case sensitive. If the name is
		// not
		// provided, the first function defined in the python code will be
		// used.
		name?: string

		// The Python code to execute for the tool.
		python_code?: string
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})

	_#defs: "/$defs/client_function/$defs/parameters": close({
		// Optional. Defines the schema for additional properties allowed
		// in an object.
		// The value must be a valid JSON string representing the Schema
		// object.
		// (Note: OpenAPI also allows a boolean, this definition expects a
		// Schema JSON).
		additional_properties?: string

		// Optional. The instance value should be valid against at least
		// one of the schemas in this list.
		any_of?: string

		// Optional. Default value of the data. Represents a dynamically
		// typed value
		// which can be either null, a number, a string, a boolean, a
		// struct,
		// or a list of values. The provided default value must be
		// compatible
		// with the defined 'type' and other schema constraints.
		default?: string

		// A map of definitions for use by ref. Only allowed at the root
		// of the schema.
		defs?: string

		// The description of the data.
		description?: string

		// Possible values of the element of primitive type with enum
		// format.
		// Examples:
		// 1. We can define direction as :
		// {type:STRING, format:enum, enum:["EAST", NORTH", "SOUTH",
		// "WEST"]}
		// 2. We can define apartment number as :
		// {type:INTEGER, format:enum, enum:["101", "201", "301"]}
		enum?: [...string]

		// Schema of the elements of Type.ARRAY.
		items?: string

		// Indicates if the value may be null.
		nullable?: bool

		// Optional. Schemas of initial elements of Type.ARRAY.
		prefix_items?: string

		// Properties of Type.OBJECT.
		properties?: string

		// Allows indirect references between schema nodes. The value
		// should be a
		// valid reference to a child of the root 'defs'.
		// For example, the following schema defines a reference to a
		// schema node
		// named "Pet":
		// type: object
		// properties:
		// pet:
		// ref: #/defs/Pet
		// defs:
		// Pet:
		// type: object
		// properties:
		// name:
		// type: string
		// The value of the "pet" property is a reference to the schema
		// node
		// named "Pet".
		// See details in
		// https://json-schema.org/understanding-json-schema/structuring.
		ref?: string

		// Required properties of Type.OBJECT.
		required?: [...string]

		// The type of the data.
		// Possible values:
		// STRING
		// INTEGER
		// NUMBER
		// BOOLEAN
		// OBJECT
		// ARRAY
		type!: string

		// Indicate the items in the array must be unique. Only applies to
		// TYPE.ARRAY.
		unique_items?: bool
	})

	_#defs: "/$defs/client_function/$defs/response": close({
		// Optional. Defines the schema for additional properties allowed
		// in an object.
		// The value must be a valid JSON string representing the Schema
		// object.
		// (Note: OpenAPI also allows a boolean, this definition expects a
		// Schema JSON).
		additional_properties?: string

		// Optional. The instance value should be valid against at least
		// one of the schemas in this list.
		any_of?: string

		// Optional. Default value of the data. Represents a dynamically
		// typed value
		// which can be either null, a number, a string, a boolean, a
		// struct,
		// or a list of values. The provided default value must be
		// compatible
		// with the defined 'type' and other schema constraints.
		default?: string

		// A map of definitions for use by ref. Only allowed at the root
		// of the schema.
		defs?: string

		// The description of the data.
		description?: string

		// Possible values of the element of primitive type with enum
		// format.
		// Examples:
		// 1. We can define direction as :
		// {type:STRING, format:enum, enum:["EAST", NORTH", "SOUTH",
		// "WEST"]}
		// 2. We can define apartment number as :
		// {type:INTEGER, format:enum, enum:["101", "201", "301"]}
		enum?: [...string]

		// Schema of the elements of Type.ARRAY.
		items?: string

		// Indicates if the value may be null.
		nullable?: bool

		// Optional. Schemas of initial elements of Type.ARRAY.
		prefix_items?: string

		// Properties of Type.OBJECT.
		properties?: string

		// Allows indirect references between schema nodes. The value
		// should be a
		// valid reference to a child of the root 'defs'.
		// For example, the following schema defines a reference to a
		// schema node
		// named "Pet":
		// type: object
		// properties:
		// pet:
		// ref: #/defs/Pet
		// defs:
		// Pet:
		// type: object
		// properties:
		// name:
		// type: string
		// The value of the "pet" property is a reference to the schema
		// node
		// named "Pet".
		// See details in
		// https://json-schema.org/understanding-json-schema/structuring.
		ref?: string

		// Required properties of Type.OBJECT.
		required?: [...string]

		// The type of the data.
		// Possible values:
		// STRING
		// INTEGER
		// NUMBER
		// BOOLEAN
		// OBJECT
		// ARRAY
		type!: string

		// Indicate the items in the array must be unique. Only applies to
		// TYPE.ARRAY.
		unique_items?: bool
	})

	_#defs: "/$defs/data_store_tool/$defs/boost_specs": close({
		spec!: matchN(1, [_#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec", [_, ...] & [..._#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec"]])

		// The Data Store where the boosting configuration is applied.
		// Full resource
		// name of DataStore, such as
		// projects/{project}/locations/{location}/collections/{collection}/dataStores/{dataStore}.
		data_stores!: [...string]
	})

	_#defs: "/$defs/data_store_tool/$defs/boost_specs/$defs/spec": close({
		condition_boost_specs!: matchN(1, [_#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs", [_, ...] & [..._#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs"]])
	})

	_#defs: "/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs": close({
		boost_control_spec?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs/$defs/boost_control_spec", list.MaxItems(1) & [..._#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs/$defs/boost_control_spec"]])

		// Strength of the boost, which should be in [-1, 1]. Negative
		// boost means
		// demotion. Default is 0.0.
		// Setting to 1.0 gives the suggestions a big promotion. However,
		// it does
		// not necessarily mean that the top result will be a boosted
		// suggestion.
		// Setting to -1.0 gives the suggestions a big demotion. However,
		// other
		// suggestions that are relevant might still be shown.
		// Setting to 0.0 means no boost applied. The boosting condition
		// is
		// ignored.
		boost?: number

		// An expression which specifies a boost condition. The syntax is
		// the same
		// as filter expression syntax. Currently, the only supported
		// condition is
		// a list of BCP-47 lang codes.
		// Example: To boost suggestions in languages en or fr:
		// (lang_code: ANY("en", "fr"))
		condition!: string
	})

	_#defs: "/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs/$defs/boost_control_spec": close({
		// The attribute type to be used to determine the boost amount.
		// The
		// attribute value can be derived from the field value of the
		// specified
		// field_name. In the case of numerical it is straightforward i.e.
		// attribute_value = numerical_field_value. In the case of
		// freshness
		// however, attribute_value = (time.now() - datetime_field_value).
		// Possible values:
		// NUMERICAL
		// FRESHNESS
		attribute_type?: string
		control_points?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs/$defs/boost_control_spec/$defs/control_points", [..._#defs."/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs/$defs/boost_control_spec/$defs/control_points"]])

		// The name of the field whose value will be used to determine the
		// boost amount.
		field_name?: string

		// The interpolation type to be applied to connect the control
		// points
		// listed below.
		// Possible values:
		// LINEAR
		interpolation_type?: string
	})

	_#defs: "/$defs/data_store_tool/$defs/boost_specs/$defs/spec/$defs/condition_boost_specs/$defs/boost_control_spec/$defs/control_points": close({
		// Can be one of:
		// 1. The numerical field value.
		// 2. The duration spec for freshness:
		// The value must be formatted as an XSD 'dayTimeDuration' value
		// (a
		// restricted subset of an ISO 8601 duration value). The pattern
		// for
		// this is: 'nDnM]'.
		attribute_value?: string

		// The value between -1 to 1 by which to boost the score if the
		// attribute_value evaluates to the value specified above.
		boost_amount?: number
	})

	_#defs: "/$defs/data_store_tool/$defs/engine_source": close({
		data_store_sources?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/engine_source/$defs/data_store_sources", [..._#defs."/$defs/data_store_tool/$defs/engine_source/$defs/data_store_sources"]])

		// Full resource name of the Engine.
		// Format:
		// 'projects/{project}/locations/{location}/collections/{collection}/engines/{engine}'
		engine!: string

		// A filter applied to the search across the Engine. Not relevant
		// and not
		// used if 'data_store_sources' is provided.
		// See:
		// https://cloud.google.com/generative-ai-app-builder/docs/filter-search-metadata
		filter?: string
	})

	_#defs: "/$defs/data_store_tool/$defs/engine_source/$defs/data_store_sources": close({
		data_store?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/engine_source/$defs/data_store_sources/$defs/data_store", list.MaxItems(1) & [..._#defs."/$defs/data_store_tool/$defs/engine_source/$defs/data_store_sources/$defs/data_store"]])

		// Filter specification for the DataStore.
		// See:
		// https://cloud.google.com/generative-ai-app-builder/docs/filter-search-metadata
		filter?: string
	})

	_#defs: "/$defs/data_store_tool/$defs/engine_source/$defs/data_store_sources/$defs/data_store": close({
		// The connector config for the data store connection.
		connector_config?: [...close({
			collection?:              string
			collection_display_name?: string
			data_source?:             string
		})]

		// Timestamp when the data store was created.
		create_time?: string

		// The display name of the data store.
		display_name?: string

		// The document processing mode for the data store connection.
		// Only set for PUBLIC_WEB and UNSTRUCTURED data stores.
		// Possible values:
		// DOCUMENTS
		// CHUNKS
		document_processing_mode?: string

		// Full resource name of the DataStore.
		// Format:
		// 'projects/{project}/locations/{location}/collections/{collection}/dataStores/{dataStore}'
		name!: string

		// The type of the data store. This field is readonly and
		// populated by the
		// server.
		// Possible values:
		// PUBLIC_WEB
		// UNSTRUCTURED
		// FAQ
		// CONNECTOR
		type?: string
	})

	_#defs: "/$defs/data_store_tool/$defs/modality_configs": close({
		grounding_config?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/grounding_config", list.MaxItems(1) & [..._#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/grounding_config"]])
		rewriter_config?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/rewriter_config", list.MaxItems(1) & [..._#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/rewriter_config"]])
		summarization_config?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/summarization_config", list.MaxItems(1) & [..._#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/summarization_config"]])

		// The modality type.
		// Possible values:
		// TEXT
		// AUDIO
		modality_type!: string
	})

	_#defs: "/$defs/data_store_tool/$defs/modality_configs/$defs/grounding_config": close({
		// Whether grounding is disabled.
		disabled?: bool

		// The groundedness threshold of the answer based on the retrieved
		// sources.
		// The value has a configurable range of [1, 5]. The level is used
		// to
		// threshold the groundedness of the answer, meaning that all
		// responses with
		// a groundedness score below the threshold will fall back to
		// returning
		// relevant snippets only.
		// For example, a level of 3 means that the groundedness score
		// must be
		// 3 or higher for the response to be returned.
		grounding_level?: number
	})

	_#defs: "/$defs/data_store_tool/$defs/modality_configs/$defs/rewriter_config": close({
		model_settings!: matchN(1, [_#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/rewriter_config/$defs/model_settings", list.MaxItems(1) & [_, ...] & [..._#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/rewriter_config/$defs/model_settings"]])

		// Whether the rewriter is disabled.
		disabled?: bool

		// The prompt definition. If not set, default prompt will be used.
		prompt?: string
	})

	_#defs: "/$defs/data_store_tool/$defs/modality_configs/$defs/rewriter_config/$defs/model_settings": close({
		// The LLM model that the agent should use.
		// If not set, the agent will inherit the model from its parent
		// agent.
		model?: string

		// If set, this temperature will be used for the LLM model.
		// Temperature
		// controls the randomness of the model's responses. Lower
		// temperatures
		// produce responses that are more predictable. Higher
		// temperatures produce
		// responses that are more creative.
		temperature?: number
	})

	_#defs: "/$defs/data_store_tool/$defs/modality_configs/$defs/summarization_config": close({
		model_settings?: matchN(1, [_#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/summarization_config/$defs/model_settings", list.MaxItems(1) & [..._#defs."/$defs/data_store_tool/$defs/modality_configs/$defs/summarization_config/$defs/model_settings"]])

		// Whether summarization is disabled.
		disabled?: bool

		// The prompt definition. If not set, default prompt will be used.
		prompt?: string
	})

	_#defs: "/$defs/data_store_tool/$defs/modality_configs/$defs/summarization_config/$defs/model_settings": close({
		// The LLM model that the agent should use.
		// If not set, the agent will inherit the model from its parent
		// agent.
		model?: string

		// If set, this temperature will be used for the LLM model.
		// Temperature
		// controls the randomness of the model's responses. Lower
		// temperatures
		// produce responses that are more predictable. Higher
		// temperatures produce
		// responses that are more creative.
		temperature?: number
	})
}
