package res

#google_contact_center_insights_view: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_contact_center_insights_view")
	close({
		// Output only. The time at which this view was created.
		create_time?: string

		// The human-readable display name of the view.
		display_name?: string

		// Location of the resource.
		location!: string

		// The resource name of the view. Randomly generated by Insights.
		name?: string
		id?:   string

		// Output only. The most recent time at which the view was
		// updated.
		update_time?: string
		project?:     string
		timeouts?:    #timeouts

		// A filter to reduce conversation results to a specific subset.
		// Refer to
		// https://cloud.google.com/contact-center/insights/docs/filtering
		// for details.
		value?: string
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})
}
