package res

import "list"

#google_scc_management_folder_security_health_analytics_custom_module: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/google_scc_management_folder_security_health_analytics_custom_module")
	close({
		// If empty, indicates that the custom module was created in the
		// organization, folder,
		// or project in which you are viewing the custom module.
		// Otherwise, ancestor_module
		// specifies the organization or folder from which the custom
		// module is inherited.
		ancestor_module?: string

		// The display name of the Security Health Analytics custom
		// module. This
		// display name becomes the finding category for all findings that
		// are
		// returned by this custom module. The display name must be
		// between 1 and
		// 128 characters, start with a lowercase letter, and contain
		// alphanumeric
		// characters or underscores only.
		display_name?: string

		// The enablement state of the custom module. Possible values:
		// ["ENABLED", "DISABLED"]
		enablement_state?: string

		// Numerical ID of the parent folder.
		folder!: string

		// The editor that last updated the custom module.
		last_editor?: string
		id?:          string

		// Location ID of the parent organization. If not provided,
		// 'global' will be used as the default location.
		location?: string
		custom_config?: matchN(1, [#custom_config, list.MaxItems(1) & [...#custom_config]])
		timeouts?: #timeouts

		// The resource name of the custom module. Its format is
		// "folders/{folder}/locations/{location}/securityHealthAnalyticsCustomModules/{securityHealthAnalyticsCustomModule}".
		// The id {securityHealthAnalyticsCustomModule} is
		// server-generated and is not user settable. It will be a
		// numeric id containing 1-20 digits.
		name?: string

		// The time at which the custom module was last updated.
		//
		// A timestamp in RFC3339 UTC "Zulu" format, with nanosecond
		// resolution and
		// up to nine fractional digits. Examples: "2014-10-02T15:01:23Z"
		// and "2014-10-02T15:01:23.045123456Z".
		update_time?: string
	})

	#custom_config: close({
		// Text that describes the vulnerability or misconfiguration that
		// the custom
		// module detects. This explanation is returned with each finding
		// instance to
		// help investigators understand the detected issue. The text must
		// be enclosed in quotation marks.
		description?: string
		custom_output?: matchN(1, [_#defs."/$defs/custom_config/$defs/custom_output", list.MaxItems(1) & [..._#defs."/$defs/custom_config/$defs/custom_output"]])

		// An explanation of the recommended steps that security teams can
		// take to resolve
		// the detected issue. This explanation is returned with each
		// finding generated by
		// this module in the nextSteps property of the finding JSON.
		recommendation?: string

		// The severity to assign to findings generated by the module.
		// Possible values: ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
		severity?: string
		predicate?: matchN(1, [_#defs."/$defs/custom_config/$defs/predicate", list.MaxItems(1) & [..._#defs."/$defs/custom_config/$defs/predicate"]])
		resource_selector?: matchN(1, [_#defs."/$defs/custom_config/$defs/resource_selector", list.MaxItems(1) & [..._#defs."/$defs/custom_config/$defs/resource_selector"]])
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})

	_#defs: "/$defs/custom_config/$defs/custom_output": close({
		properties?: matchN(1, [_#defs."/$defs/custom_config/$defs/custom_output/$defs/properties", [..._#defs."/$defs/custom_config/$defs/custom_output/$defs/properties"]])
	})

	_#defs: "/$defs/custom_config/$defs/custom_output/$defs/properties": close({
		value_expression?: matchN(1, [_#defs."/$defs/custom_config/$defs/custom_output/$defs/properties/$defs/value_expression", list.MaxItems(1) & [..._#defs."/$defs/custom_config/$defs/custom_output/$defs/properties/$defs/value_expression"]])

		// Name of the property for the custom output.
		name?: string
	})

	_#defs: "/$defs/custom_config/$defs/custom_output/$defs/properties/$defs/value_expression": close({
		// Description of the expression. This is a longer text which
		// describes the
		// expression, e.g. when hovered over it in a UI.
		description?: string

		// Textual representation of an expression in Common Expression
		// Language syntax.
		expression!: string

		// String indicating the location of the expression for error
		// reporting, e.g. a
		// file name and a position in the file.
		location?: string

		// Title for the expression, i.e. a short string describing its
		// purpose. This can
		// be used e.g. in UIs which allow to enter the expression.
		title?: string
	})

	_#defs: "/$defs/custom_config/$defs/predicate": close({
		// Description of the expression. This is a longer text which
		// describes the
		// expression, e.g. when hovered over it in a UI.
		description?: string

		// Textual representation of an expression in Common Expression
		// Language syntax.
		expression!: string

		// String indicating the location of the expression for error
		// reporting, e.g. a
		// file name and a position in the file.
		location?: string

		// Title for the expression, i.e. a short string describing its
		// purpose. This can
		// be used e.g. in UIs which allow to enter the expression.
		title?: string
	})

	_#defs: "/$defs/custom_config/$defs/resource_selector": close({
		// The resource types to run the detector on.
		resource_types!: [...string]
	})
}
