package res

import "list"

#google_identity_platform_tenant: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/google_identity_platform_tenant")
	close({
		// Whether to allow email/password user authentication.
		allow_password_signup?: bool

		// Whether authentication is disabled for the tenant. If true, the
		// users under
		// the disabled tenant are not allowed to sign-in. Admins of the
		// disabled tenant
		// are not able to manage its users.
		disable_auth?: bool

		// Human friendly display name of the tenant.
		display_name!: string

		// Whether to enable email link user authentication.
		enable_email_link_signin?: bool
		id?:                       string
		client?: matchN(1, [#client, list.MaxItems(1) & [...#client]])
		timeouts?: #timeouts

		// The name of the tenant that is generated by the server
		name?:    string
		project?: string
	})

	#client: close({
		permissions?: matchN(1, [_#defs."/$defs/client/$defs/permissions", list.MaxItems(1) & [..._#defs."/$defs/client/$defs/permissions"]])
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})

	_#defs: "/$defs/client/$defs/permissions": close({
		// When true, end users cannot delete their account on the
		// associated project through any of our API methods.
		disabled_user_deletion?: bool

		// When true, end users cannot sign up for a new account on the
		// associated project through any of our API methods.
		disabled_user_signup?: bool
	})
}
