package cloudflare

import "github.com/roman-mazur/cuetf/cloudflare/data"

#Terraform: {
	#cloudflarePrefix: string
	_#ds: "\(#cloudflarePrefix)_access_rule": data.#cloudflare_access_rule
	_#ds: "\(#cloudflarePrefix)_access_rules": data.#cloudflare_access_rules
	_#ds: "\(#cloudflarePrefix)_account_api_token_permission_groups": data.#cloudflare_account_api_token_permission_groups
	_#ds: "\(#cloudflarePrefix)_account_api_token_permission_groups_list": data.#cloudflare_account_api_token_permission_groups_list
	_#ds: "\(#cloudflarePrefix)_account_dns_settings": data.#cloudflare_account_dns_settings
	_#ds: "\(#cloudflarePrefix)_account_dns_settings_internal_view": data.#cloudflare_account_dns_settings_internal_view
	_#ds: "\(#cloudflarePrefix)_account_dns_settings_internal_views": data.#cloudflare_account_dns_settings_internal_views
	_#ds: "\(#cloudflarePrefix)_account": data.#cloudflare_account
	_#ds: "\(#cloudflarePrefix)_account_member": data.#cloudflare_account_member
	_#ds: "\(#cloudflarePrefix)_account_members": data.#cloudflare_account_members
	_#ds: "\(#cloudflarePrefix)_account_permission_group": data.#cloudflare_account_permission_group
	_#ds: "\(#cloudflarePrefix)_account_permission_groups": data.#cloudflare_account_permission_groups
	_#ds: "\(#cloudflarePrefix)_account_role": data.#cloudflare_account_role
	_#ds: "\(#cloudflarePrefix)_account_roles": data.#cloudflare_account_roles
	_#ds: "\(#cloudflarePrefix)_account_subscription": data.#cloudflare_account_subscription
	_#ds: "\(#cloudflarePrefix)_account_token": data.#cloudflare_account_token
	_#ds: "\(#cloudflarePrefix)_account_tokens": data.#cloudflare_account_tokens
	_#ds: "\(#cloudflarePrefix)_accounts": data.#cloudflare_accounts
	_#ds: "\(#cloudflarePrefix)_address_map": data.#cloudflare_address_map
	_#ds: "\(#cloudflarePrefix)_address_maps": data.#cloudflare_address_maps
	_#ds: "\(#cloudflarePrefix)_api_shield_discovery_operations": data.#cloudflare_api_shield_discovery_operations
	_#ds: "\(#cloudflarePrefix)_api_shield": data.#cloudflare_api_shield
	_#ds: "\(#cloudflarePrefix)_api_shield_operation": data.#cloudflare_api_shield_operation
	_#ds: "\(#cloudflarePrefix)_api_shield_operation_schema_validation_settings": data.#cloudflare_api_shield_operation_schema_validation_settings
	_#ds: "\(#cloudflarePrefix)_api_shield_operations": data.#cloudflare_api_shield_operations
	_#ds: "\(#cloudflarePrefix)_api_shield_schema": data.#cloudflare_api_shield_schema
	_#ds: "\(#cloudflarePrefix)_api_shield_schema_validation_settings": data.#cloudflare_api_shield_schema_validation_settings
	_#ds: "\(#cloudflarePrefix)_api_shield_schemas": data.#cloudflare_api_shield_schemas
	_#ds: "\(#cloudflarePrefix)_api_token": data.#cloudflare_api_token
	_#ds: "\(#cloudflarePrefix)_api_token_permission_groups_list": data.#cloudflare_api_token_permission_groups_list
	_#ds: "\(#cloudflarePrefix)_api_tokens": data.#cloudflare_api_tokens
	_#ds: "\(#cloudflarePrefix)_argo_smart_routing": data.#cloudflare_argo_smart_routing
	_#ds: "\(#cloudflarePrefix)_argo_tiered_caching": data.#cloudflare_argo_tiered_caching
	_#ds: "\(#cloudflarePrefix)_authenticated_origin_pulls_certificate": data.#cloudflare_authenticated_origin_pulls_certificate
	_#ds: "\(#cloudflarePrefix)_authenticated_origin_pulls_certificates": data.#cloudflare_authenticated_origin_pulls_certificates
	_#ds: "\(#cloudflarePrefix)_authenticated_origin_pulls": data.#cloudflare_authenticated_origin_pulls
	_#ds: "\(#cloudflarePrefix)_authenticated_origin_pulls_settings": data.#cloudflare_authenticated_origin_pulls_settings
	_#ds: "\(#cloudflarePrefix)_bot_management": data.#cloudflare_bot_management
	_#ds: "\(#cloudflarePrefix)_botnet_feed_config_asn": data.#cloudflare_botnet_feed_config_asn
	_#ds: "\(#cloudflarePrefix)_byo_ip_prefix": data.#cloudflare_byo_ip_prefix
	_#ds: "\(#cloudflarePrefix)_byo_ip_prefixes": data.#cloudflare_byo_ip_prefixes
	_#ds: "\(#cloudflarePrefix)_calls_sfu_app": data.#cloudflare_calls_sfu_app
	_#ds: "\(#cloudflarePrefix)_calls_sfu_apps": data.#cloudflare_calls_sfu_apps
	_#ds: "\(#cloudflarePrefix)_calls_turn_app": data.#cloudflare_calls_turn_app
	_#ds: "\(#cloudflarePrefix)_calls_turn_apps": data.#cloudflare_calls_turn_apps
	_#ds: "\(#cloudflarePrefix)_certificate_pack": data.#cloudflare_certificate_pack
	_#ds: "\(#cloudflarePrefix)_certificate_packs": data.#cloudflare_certificate_packs
	_#ds: "\(#cloudflarePrefix)_cloud_connector_rules": data.#cloudflare_cloud_connector_rules
	_#ds: "\(#cloudflarePrefix)_cloudforce_one_request_asset": data.#cloudflare_cloudforce_one_request_asset
	_#ds: "\(#cloudflarePrefix)_cloudforce_one_request": data.#cloudflare_cloudforce_one_request
	_#ds: "\(#cloudflarePrefix)_cloudforce_one_request_message": data.#cloudflare_cloudforce_one_request_message
	_#ds: "\(#cloudflarePrefix)_cloudforce_one_request_priority": data.#cloudflare_cloudforce_one_request_priority
	_#ds: "\(#cloudflarePrefix)_cloudforce_one_requests": data.#cloudflare_cloudforce_one_requests
	_#ds: "\(#cloudflarePrefix)_connectivity_directory_service": data.#cloudflare_connectivity_directory_service
	_#ds: "\(#cloudflarePrefix)_connectivity_directory_services": data.#cloudflare_connectivity_directory_services
	_#ds: "\(#cloudflarePrefix)_content_scanning_expressions": data.#cloudflare_content_scanning_expressions
	_#ds: "\(#cloudflarePrefix)_content_scanning": data.#cloudflare_content_scanning
	_#ds: "\(#cloudflarePrefix)_custom_hostname_fallback_origin": data.#cloudflare_custom_hostname_fallback_origin
	_#ds: "\(#cloudflarePrefix)_custom_hostname": data.#cloudflare_custom_hostname
	_#ds: "\(#cloudflarePrefix)_custom_hostnames": data.#cloudflare_custom_hostnames
	_#ds: "\(#cloudflarePrefix)_custom_pages": data.#cloudflare_custom_pages
	_#ds: "\(#cloudflarePrefix)_custom_pages_list": data.#cloudflare_custom_pages_list
	_#ds: "\(#cloudflarePrefix)_custom_ssl": data.#cloudflare_custom_ssl
	_#ds: "\(#cloudflarePrefix)_custom_ssls": data.#cloudflare_custom_ssls
	_#ds: "\(#cloudflarePrefix)_d1_database": data.#cloudflare_d1_database
	_#ds: "\(#cloudflarePrefix)_d1_databases": data.#cloudflare_d1_databases
	_#ds: "\(#cloudflarePrefix)_dcv_delegation": data.#cloudflare_dcv_delegation
	_#ds: "\(#cloudflarePrefix)_dns_firewall": data.#cloudflare_dns_firewall
	_#ds: "\(#cloudflarePrefix)_dns_firewalls": data.#cloudflare_dns_firewalls
	_#ds: "\(#cloudflarePrefix)_dns_record": data.#cloudflare_dns_record
	_#ds: "\(#cloudflarePrefix)_dns_records": data.#cloudflare_dns_records
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_acl": data.#cloudflare_dns_zone_transfers_acl
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_acls": data.#cloudflare_dns_zone_transfers_acls
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_incoming": data.#cloudflare_dns_zone_transfers_incoming
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_outgoing": data.#cloudflare_dns_zone_transfers_outgoing
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_peer": data.#cloudflare_dns_zone_transfers_peer
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_peers": data.#cloudflare_dns_zone_transfers_peers
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_tsig": data.#cloudflare_dns_zone_transfers_tsig
	_#ds: "\(#cloudflarePrefix)_dns_zone_transfers_tsigs": data.#cloudflare_dns_zone_transfers_tsigs
	_#ds: "\(#cloudflarePrefix)_email_routing_address": data.#cloudflare_email_routing_address
	_#ds: "\(#cloudflarePrefix)_email_routing_addresses": data.#cloudflare_email_routing_addresses
	_#ds: "\(#cloudflarePrefix)_email_routing_catch_all": data.#cloudflare_email_routing_catch_all
	_#ds: "\(#cloudflarePrefix)_email_routing_dns": data.#cloudflare_email_routing_dns
	_#ds: "\(#cloudflarePrefix)_email_routing_rule": data.#cloudflare_email_routing_rule
	_#ds: "\(#cloudflarePrefix)_email_routing_rules": data.#cloudflare_email_routing_rules
	_#ds: "\(#cloudflarePrefix)_email_routing_settings": data.#cloudflare_email_routing_settings
	_#ds: "\(#cloudflarePrefix)_email_security_block_sender": data.#cloudflare_email_security_block_sender
	_#ds: "\(#cloudflarePrefix)_email_security_block_senders": data.#cloudflare_email_security_block_senders
	_#ds: "\(#cloudflarePrefix)_email_security_impersonation_registries": data.#cloudflare_email_security_impersonation_registries
	_#ds: "\(#cloudflarePrefix)_email_security_impersonation_registry": data.#cloudflare_email_security_impersonation_registry
	_#ds: "\(#cloudflarePrefix)_email_security_trusted_domains": data.#cloudflare_email_security_trusted_domains
	_#ds: "\(#cloudflarePrefix)_email_security_trusted_domains_list": data.#cloudflare_email_security_trusted_domains_list
	_#ds: "\(#cloudflarePrefix)_filter": data.#cloudflare_filter
	_#ds: "\(#cloudflarePrefix)_filters": data.#cloudflare_filters
	_#ds: "\(#cloudflarePrefix)_firewall_rule": data.#cloudflare_firewall_rule
	_#ds: "\(#cloudflarePrefix)_firewall_rules": data.#cloudflare_firewall_rules
	_#ds: "\(#cloudflarePrefix)_healthcheck": data.#cloudflare_healthcheck
	_#ds: "\(#cloudflarePrefix)_healthchecks": data.#cloudflare_healthchecks
	_#ds: "\(#cloudflarePrefix)_hostname_tls_setting": data.#cloudflare_hostname_tls_setting
	_#ds: "\(#cloudflarePrefix)_hyperdrive_config": data.#cloudflare_hyperdrive_config
	_#ds: "\(#cloudflarePrefix)_hyperdrive_configs": data.#cloudflare_hyperdrive_configs
	_#ds: "\(#cloudflarePrefix)_image": data.#cloudflare_image
	_#ds: "\(#cloudflarePrefix)_image_variant": data.#cloudflare_image_variant
	_#ds: "\(#cloudflarePrefix)_images": data.#cloudflare_images
	_#ds: "\(#cloudflarePrefix)_ip_ranges": data.#cloudflare_ip_ranges
	_#ds: "\(#cloudflarePrefix)_keyless_certificate": data.#cloudflare_keyless_certificate
	_#ds: "\(#cloudflarePrefix)_keyless_certificates": data.#cloudflare_keyless_certificates
	_#ds: "\(#cloudflarePrefix)_leaked_credential_check": data.#cloudflare_leaked_credential_check
	_#ds: "\(#cloudflarePrefix)_leaked_credential_check_rule": data.#cloudflare_leaked_credential_check_rule
	_#ds: "\(#cloudflarePrefix)_leaked_credential_check_rules": data.#cloudflare_leaked_credential_check_rules
	_#ds: "\(#cloudflarePrefix)_list": data.#cloudflare_list
	_#ds: "\(#cloudflarePrefix)_list_item": data.#cloudflare_list_item
	_#ds: "\(#cloudflarePrefix)_list_items": data.#cloudflare_list_items
	_#ds: "\(#cloudflarePrefix)_lists": data.#cloudflare_lists
	_#ds: "\(#cloudflarePrefix)_load_balancer": data.#cloudflare_load_balancer
	_#ds: "\(#cloudflarePrefix)_load_balancer_monitor": data.#cloudflare_load_balancer_monitor
	_#ds: "\(#cloudflarePrefix)_load_balancer_monitors": data.#cloudflare_load_balancer_monitors
	_#ds: "\(#cloudflarePrefix)_load_balancer_pool": data.#cloudflare_load_balancer_pool
	_#ds: "\(#cloudflarePrefix)_load_balancer_pools": data.#cloudflare_load_balancer_pools
	_#ds: "\(#cloudflarePrefix)_load_balancers": data.#cloudflare_load_balancers
	_#ds: "\(#cloudflarePrefix)_logpull_retention": data.#cloudflare_logpull_retention
	_#ds: "\(#cloudflarePrefix)_logpush_dataset_field": data.#cloudflare_logpush_dataset_field
	_#ds: "\(#cloudflarePrefix)_logpush_dataset_job": data.#cloudflare_logpush_dataset_job
	_#ds: "\(#cloudflarePrefix)_logpush_job": data.#cloudflare_logpush_job
	_#ds: "\(#cloudflarePrefix)_logpush_jobs": data.#cloudflare_logpush_jobs
	_#ds: "\(#cloudflarePrefix)_magic_network_monitoring_configuration": data.#cloudflare_magic_network_monitoring_configuration
	_#ds: "\(#cloudflarePrefix)_magic_network_monitoring_rule": data.#cloudflare_magic_network_monitoring_rule
	_#ds: "\(#cloudflarePrefix)_magic_network_monitoring_rules": data.#cloudflare_magic_network_monitoring_rules
	_#ds: "\(#cloudflarePrefix)_magic_transit_connector": data.#cloudflare_magic_transit_connector
	_#ds: "\(#cloudflarePrefix)_magic_transit_connectors": data.#cloudflare_magic_transit_connectors
	_#ds: "\(#cloudflarePrefix)_magic_transit_site_acl": data.#cloudflare_magic_transit_site_acl
	_#ds: "\(#cloudflarePrefix)_magic_transit_site_acls": data.#cloudflare_magic_transit_site_acls
	_#ds: "\(#cloudflarePrefix)_magic_transit_site": data.#cloudflare_magic_transit_site
	_#ds: "\(#cloudflarePrefix)_magic_transit_site_lan": data.#cloudflare_magic_transit_site_lan
	_#ds: "\(#cloudflarePrefix)_magic_transit_site_lans": data.#cloudflare_magic_transit_site_lans
	_#ds: "\(#cloudflarePrefix)_magic_transit_site_wan": data.#cloudflare_magic_transit_site_wan
	_#ds: "\(#cloudflarePrefix)_magic_transit_site_wans": data.#cloudflare_magic_transit_site_wans
	_#ds: "\(#cloudflarePrefix)_magic_transit_sites": data.#cloudflare_magic_transit_sites
	_#ds: "\(#cloudflarePrefix)_magic_wan_gre_tunnel": data.#cloudflare_magic_wan_gre_tunnel
	_#ds: "\(#cloudflarePrefix)_magic_wan_ipsec_tunnel": data.#cloudflare_magic_wan_ipsec_tunnel
	_#ds: "\(#cloudflarePrefix)_magic_wan_static_route": data.#cloudflare_magic_wan_static_route
	_#ds: "\(#cloudflarePrefix)_managed_transforms": data.#cloudflare_managed_transforms
	_#ds: "\(#cloudflarePrefix)_mtls_certificate": data.#cloudflare_mtls_certificate
	_#ds: "\(#cloudflarePrefix)_mtls_certificates": data.#cloudflare_mtls_certificates
	_#ds: "\(#cloudflarePrefix)_notification_policies": data.#cloudflare_notification_policies
	_#ds: "\(#cloudflarePrefix)_notification_policy": data.#cloudflare_notification_policy
	_#ds: "\(#cloudflarePrefix)_notification_policy_webhooks": data.#cloudflare_notification_policy_webhooks
	_#ds: "\(#cloudflarePrefix)_notification_policy_webhooks_list": data.#cloudflare_notification_policy_webhooks_list
	_#ds: "\(#cloudflarePrefix)_observatory_scheduled_test": data.#cloudflare_observatory_scheduled_test
	_#ds: "\(#cloudflarePrefix)_organization": data.#cloudflare_organization
	_#ds: "\(#cloudflarePrefix)_organization_profile": data.#cloudflare_organization_profile
	_#ds: "\(#cloudflarePrefix)_organizations": data.#cloudflare_organizations
	_#ds: "\(#cloudflarePrefix)_origin_ca_certificate": data.#cloudflare_origin_ca_certificate
	_#ds: "\(#cloudflarePrefix)_origin_ca_certificates": data.#cloudflare_origin_ca_certificates
	_#ds: "\(#cloudflarePrefix)_page_rule": data.#cloudflare_page_rule
	_#ds: "\(#cloudflarePrefix)_page_shield_connections": data.#cloudflare_page_shield_connections
	_#ds: "\(#cloudflarePrefix)_page_shield_connections_list": data.#cloudflare_page_shield_connections_list
	_#ds: "\(#cloudflarePrefix)_page_shield_cookies": data.#cloudflare_page_shield_cookies
	_#ds: "\(#cloudflarePrefix)_page_shield_cookies_list": data.#cloudflare_page_shield_cookies_list
	_#ds: "\(#cloudflarePrefix)_page_shield_policies": data.#cloudflare_page_shield_policies
	_#ds: "\(#cloudflarePrefix)_page_shield_policy": data.#cloudflare_page_shield_policy
	_#ds: "\(#cloudflarePrefix)_page_shield_scripts": data.#cloudflare_page_shield_scripts
	_#ds: "\(#cloudflarePrefix)_page_shield_scripts_list": data.#cloudflare_page_shield_scripts_list
	_#ds: "\(#cloudflarePrefix)_pages_domain": data.#cloudflare_pages_domain
	_#ds: "\(#cloudflarePrefix)_pages_domains": data.#cloudflare_pages_domains
	_#ds: "\(#cloudflarePrefix)_pages_project": data.#cloudflare_pages_project
	_#ds: "\(#cloudflarePrefix)_pages_projects": data.#cloudflare_pages_projects
	_#ds: "\(#cloudflarePrefix)_queue_consumer": data.#cloudflare_queue_consumer
	_#ds: "\(#cloudflarePrefix)_queue_consumers": data.#cloudflare_queue_consumers
	_#ds: "\(#cloudflarePrefix)_queue": data.#cloudflare_queue
	_#ds: "\(#cloudflarePrefix)_queues": data.#cloudflare_queues
	_#ds: "\(#cloudflarePrefix)_r2_bucket_cors": data.#cloudflare_r2_bucket_cors
	_#ds: "\(#cloudflarePrefix)_r2_bucket_event_notification": data.#cloudflare_r2_bucket_event_notification
	_#ds: "\(#cloudflarePrefix)_r2_bucket": data.#cloudflare_r2_bucket
	_#ds: "\(#cloudflarePrefix)_r2_bucket_lifecycle": data.#cloudflare_r2_bucket_lifecycle
	_#ds: "\(#cloudflarePrefix)_r2_bucket_lock": data.#cloudflare_r2_bucket_lock
	_#ds: "\(#cloudflarePrefix)_r2_bucket_sippy": data.#cloudflare_r2_bucket_sippy
	_#ds: "\(#cloudflarePrefix)_r2_custom_domain": data.#cloudflare_r2_custom_domain
	_#ds: "\(#cloudflarePrefix)_rate_limit": data.#cloudflare_rate_limit
	_#ds: "\(#cloudflarePrefix)_rate_limits": data.#cloudflare_rate_limits
	_#ds: "\(#cloudflarePrefix)_regional_hostname": data.#cloudflare_regional_hostname
	_#ds: "\(#cloudflarePrefix)_regional_hostnames": data.#cloudflare_regional_hostnames
	_#ds: "\(#cloudflarePrefix)_regional_tiered_cache": data.#cloudflare_regional_tiered_cache
	_#ds: "\(#cloudflarePrefix)_registrar_domain": data.#cloudflare_registrar_domain
	_#ds: "\(#cloudflarePrefix)_registrar_domains": data.#cloudflare_registrar_domains
	_#ds: "\(#cloudflarePrefix)_resource_group": data.#cloudflare_resource_group
	_#ds: "\(#cloudflarePrefix)_resource_groups": data.#cloudflare_resource_groups
	_#ds: "\(#cloudflarePrefix)_ruleset": data.#cloudflare_ruleset
	_#ds: "\(#cloudflarePrefix)_rulesets": data.#cloudflare_rulesets
	_#ds: "\(#cloudflarePrefix)_schema_validation_operation_settings": data.#cloudflare_schema_validation_operation_settings
	_#ds: "\(#cloudflarePrefix)_schema_validation_operation_settings_list": data.#cloudflare_schema_validation_operation_settings_list
	_#ds: "\(#cloudflarePrefix)_schema_validation_schemas": data.#cloudflare_schema_validation_schemas
	_#ds: "\(#cloudflarePrefix)_schema_validation_schemas_list": data.#cloudflare_schema_validation_schemas_list
	_#ds: "\(#cloudflarePrefix)_schema_validation_settings": data.#cloudflare_schema_validation_settings
	_#ds: "\(#cloudflarePrefix)_snippet": data.#cloudflare_snippet
	_#ds: "\(#cloudflarePrefix)_snippet_list": data.#cloudflare_snippet_list
	_#ds: "\(#cloudflarePrefix)_snippet_rules_list": data.#cloudflare_snippet_rules_list
	_#ds: "\(#cloudflarePrefix)_snippets": data.#cloudflare_snippets
	_#ds: "\(#cloudflarePrefix)_snippets_list": data.#cloudflare_snippets_list
	_#ds: "\(#cloudflarePrefix)_spectrum_application": data.#cloudflare_spectrum_application
	_#ds: "\(#cloudflarePrefix)_spectrum_applications": data.#cloudflare_spectrum_applications
	_#ds: "\(#cloudflarePrefix)_sso_connector": data.#cloudflare_sso_connector
	_#ds: "\(#cloudflarePrefix)_sso_connectors": data.#cloudflare_sso_connectors
	_#ds: "\(#cloudflarePrefix)_stream_audio_track": data.#cloudflare_stream_audio_track
	_#ds: "\(#cloudflarePrefix)_stream_caption_language": data.#cloudflare_stream_caption_language
	_#ds: "\(#cloudflarePrefix)_stream_download": data.#cloudflare_stream_download
	_#ds: "\(#cloudflarePrefix)_stream": data.#cloudflare_stream
	_#ds: "\(#cloudflarePrefix)_stream_key": data.#cloudflare_stream_key
	_#ds: "\(#cloudflarePrefix)_stream_live_input": data.#cloudflare_stream_live_input
	_#ds: "\(#cloudflarePrefix)_stream_watermark": data.#cloudflare_stream_watermark
	_#ds: "\(#cloudflarePrefix)_stream_watermarks": data.#cloudflare_stream_watermarks
	_#ds: "\(#cloudflarePrefix)_stream_webhook": data.#cloudflare_stream_webhook
	_#ds: "\(#cloudflarePrefix)_streams": data.#cloudflare_streams
	_#ds: "\(#cloudflarePrefix)_tiered_cache": data.#cloudflare_tiered_cache
	_#ds: "\(#cloudflarePrefix)_token_validation_config": data.#cloudflare_token_validation_config
	_#ds: "\(#cloudflarePrefix)_token_validation_configs": data.#cloudflare_token_validation_configs
	_#ds: "\(#cloudflarePrefix)_token_validation_rules": data.#cloudflare_token_validation_rules
	_#ds: "\(#cloudflarePrefix)_token_validation_rules_list": data.#cloudflare_token_validation_rules_list
	_#ds: "\(#cloudflarePrefix)_total_tls": data.#cloudflare_total_tls
	_#ds: "\(#cloudflarePrefix)_turnstile_widget": data.#cloudflare_turnstile_widget
	_#ds: "\(#cloudflarePrefix)_turnstile_widgets": data.#cloudflare_turnstile_widgets
	_#ds: "\(#cloudflarePrefix)_universal_ssl_setting": data.#cloudflare_universal_ssl_setting
	_#ds: "\(#cloudflarePrefix)_url_normalization_settings": data.#cloudflare_url_normalization_settings
	_#ds: "\(#cloudflarePrefix)_user_agent_blocking_rule": data.#cloudflare_user_agent_blocking_rule
	_#ds: "\(#cloudflarePrefix)_user_agent_blocking_rules": data.#cloudflare_user_agent_blocking_rules
	_#ds: "\(#cloudflarePrefix)_user": data.#cloudflare_user
	_#ds: "\(#cloudflarePrefix)_waiting_room_event": data.#cloudflare_waiting_room_event
	_#ds: "\(#cloudflarePrefix)_waiting_room_events": data.#cloudflare_waiting_room_events
	_#ds: "\(#cloudflarePrefix)_waiting_room": data.#cloudflare_waiting_room
	_#ds: "\(#cloudflarePrefix)_waiting_room_rules": data.#cloudflare_waiting_room_rules
	_#ds: "\(#cloudflarePrefix)_waiting_room_settings": data.#cloudflare_waiting_room_settings
	_#ds: "\(#cloudflarePrefix)_waiting_rooms": data.#cloudflare_waiting_rooms
	_#ds: "\(#cloudflarePrefix)_web3_hostname": data.#cloudflare_web3_hostname
	_#ds: "\(#cloudflarePrefix)_web3_hostnames": data.#cloudflare_web3_hostnames
	_#ds: "\(#cloudflarePrefix)_web_analytics_site": data.#cloudflare_web_analytics_site
	_#ds: "\(#cloudflarePrefix)_web_analytics_sites": data.#cloudflare_web_analytics_sites
	_#ds: "\(#cloudflarePrefix)_worker": data.#cloudflare_worker
	_#ds: "\(#cloudflarePrefix)_worker_version": data.#cloudflare_worker_version
	_#ds: "\(#cloudflarePrefix)_worker_versions": data.#cloudflare_worker_versions
	_#ds: "\(#cloudflarePrefix)_workers_cron_trigger": data.#cloudflare_workers_cron_trigger
	_#ds: "\(#cloudflarePrefix)_workers_custom_domain": data.#cloudflare_workers_custom_domain
	_#ds: "\(#cloudflarePrefix)_workers_custom_domains": data.#cloudflare_workers_custom_domains
	_#ds: "\(#cloudflarePrefix)_workers_deployment": data.#cloudflare_workers_deployment
	_#ds: "\(#cloudflarePrefix)_workers_for_platforms_dispatch_namespace": data.#cloudflare_workers_for_platforms_dispatch_namespace
	_#ds: "\(#cloudflarePrefix)_workers_for_platforms_dispatch_namespaces": data.#cloudflare_workers_for_platforms_dispatch_namespaces
	_#ds: "\(#cloudflarePrefix)_workers": data.#cloudflare_workers
	_#ds: "\(#cloudflarePrefix)_workers_kv": data.#cloudflare_workers_kv
	_#ds: "\(#cloudflarePrefix)_workers_kv_namespace": data.#cloudflare_workers_kv_namespace
	_#ds: "\(#cloudflarePrefix)_workers_kv_namespaces": data.#cloudflare_workers_kv_namespaces
	_#ds: "\(#cloudflarePrefix)_workers_route": data.#cloudflare_workers_route
	_#ds: "\(#cloudflarePrefix)_workers_routes": data.#cloudflare_workers_routes
	_#ds: "\(#cloudflarePrefix)_workers_script": data.#cloudflare_workers_script
	_#ds: "\(#cloudflarePrefix)_workers_script_subdomain": data.#cloudflare_workers_script_subdomain
	_#ds: "\(#cloudflarePrefix)_workers_scripts": data.#cloudflare_workers_scripts
	_#ds: "\(#cloudflarePrefix)_workflow": data.#cloudflare_workflow
	_#ds: "\(#cloudflarePrefix)_workflows": data.#cloudflare_workflows
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_ai_controls_mcp_portal": data.#cloudflare_zero_trust_access_ai_controls_mcp_portal
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_ai_controls_mcp_portals": data.#cloudflare_zero_trust_access_ai_controls_mcp_portals
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_ai_controls_mcp_server": data.#cloudflare_zero_trust_access_ai_controls_mcp_server
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_ai_controls_mcp_servers": data.#cloudflare_zero_trust_access_ai_controls_mcp_servers
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_application": data.#cloudflare_zero_trust_access_application
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_applications": data.#cloudflare_zero_trust_access_applications
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_custom_page": data.#cloudflare_zero_trust_access_custom_page
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_custom_pages": data.#cloudflare_zero_trust_access_custom_pages
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_group": data.#cloudflare_zero_trust_access_group
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_groups": data.#cloudflare_zero_trust_access_groups
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_identity_provider": data.#cloudflare_zero_trust_access_identity_provider
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_identity_providers": data.#cloudflare_zero_trust_access_identity_providers
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_infrastructure_target": data.#cloudflare_zero_trust_access_infrastructure_target
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_infrastructure_targets": data.#cloudflare_zero_trust_access_infrastructure_targets
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_key_configuration": data.#cloudflare_zero_trust_access_key_configuration
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_mtls_certificate": data.#cloudflare_zero_trust_access_mtls_certificate
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_mtls_certificates": data.#cloudflare_zero_trust_access_mtls_certificates
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_mtls_hostname_settings": data.#cloudflare_zero_trust_access_mtls_hostname_settings
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_policies": data.#cloudflare_zero_trust_access_policies
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_policy": data.#cloudflare_zero_trust_access_policy
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_service_token": data.#cloudflare_zero_trust_access_service_token
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_service_tokens": data.#cloudflare_zero_trust_access_service_tokens
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_short_lived_certificate": data.#cloudflare_zero_trust_access_short_lived_certificate
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_short_lived_certificates": data.#cloudflare_zero_trust_access_short_lived_certificates
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_tag": data.#cloudflare_zero_trust_access_tag
	_#ds: "\(#cloudflarePrefix)_zero_trust_access_tags": data.#cloudflare_zero_trust_access_tags
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_custom_profile": data.#cloudflare_zero_trust_device_custom_profile
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_custom_profile_local_domain_fallback": data.#cloudflare_zero_trust_device_custom_profile_local_domain_fallback
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_custom_profiles": data.#cloudflare_zero_trust_device_custom_profiles
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_default_profile_certificates": data.#cloudflare_zero_trust_device_default_profile_certificates
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_default_profile": data.#cloudflare_zero_trust_device_default_profile
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_default_profile_local_domain_fallback": data.#cloudflare_zero_trust_device_default_profile_local_domain_fallback
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_managed_networks": data.#cloudflare_zero_trust_device_managed_networks
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_managed_networks_list": data.#cloudflare_zero_trust_device_managed_networks_list
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_posture_integration": data.#cloudflare_zero_trust_device_posture_integration
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_posture_integrations": data.#cloudflare_zero_trust_device_posture_integrations
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_posture_rule": data.#cloudflare_zero_trust_device_posture_rule
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_posture_rules": data.#cloudflare_zero_trust_device_posture_rules
	_#ds: "\(#cloudflarePrefix)_zero_trust_device_settings": data.#cloudflare_zero_trust_device_settings
	_#ds: "\(#cloudflarePrefix)_zero_trust_dex_test": data.#cloudflare_zero_trust_dex_test
	_#ds: "\(#cloudflarePrefix)_zero_trust_dex_tests": data.#cloudflare_zero_trust_dex_tests
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_custom_entries": data.#cloudflare_zero_trust_dlp_custom_entries
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_custom_entry": data.#cloudflare_zero_trust_dlp_custom_entry
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_custom_profile": data.#cloudflare_zero_trust_dlp_custom_profile
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_dataset": data.#cloudflare_zero_trust_dlp_dataset
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_datasets": data.#cloudflare_zero_trust_dlp_datasets
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_entries": data.#cloudflare_zero_trust_dlp_entries
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_entry": data.#cloudflare_zero_trust_dlp_entry
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_integration_entries": data.#cloudflare_zero_trust_dlp_integration_entries
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_integration_entry": data.#cloudflare_zero_trust_dlp_integration_entry
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_predefined_entries": data.#cloudflare_zero_trust_dlp_predefined_entries
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_predefined_entry": data.#cloudflare_zero_trust_dlp_predefined_entry
	_#ds: "\(#cloudflarePrefix)_zero_trust_dlp_predefined_profile": data.#cloudflare_zero_trust_dlp_predefined_profile
	_#ds: "\(#cloudflarePrefix)_zero_trust_dns_location": data.#cloudflare_zero_trust_dns_location
	_#ds: "\(#cloudflarePrefix)_zero_trust_dns_locations": data.#cloudflare_zero_trust_dns_locations
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_app_types_list": data.#cloudflare_zero_trust_gateway_app_types_list
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_categories_list": data.#cloudflare_zero_trust_gateway_categories_list
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_certificate": data.#cloudflare_zero_trust_gateway_certificate
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_certificates": data.#cloudflare_zero_trust_gateway_certificates
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_logging": data.#cloudflare_zero_trust_gateway_logging
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_policies": data.#cloudflare_zero_trust_gateway_policies
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_policy": data.#cloudflare_zero_trust_gateway_policy
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_proxy_endpoint": data.#cloudflare_zero_trust_gateway_proxy_endpoint
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_proxy_endpoints": data.#cloudflare_zero_trust_gateway_proxy_endpoints
	_#ds: "\(#cloudflarePrefix)_zero_trust_gateway_settings": data.#cloudflare_zero_trust_gateway_settings
	_#ds: "\(#cloudflarePrefix)_zero_trust_list": data.#cloudflare_zero_trust_list
	_#ds: "\(#cloudflarePrefix)_zero_trust_lists": data.#cloudflare_zero_trust_lists
	_#ds: "\(#cloudflarePrefix)_zero_trust_network_hostname_route": data.#cloudflare_zero_trust_network_hostname_route
	_#ds: "\(#cloudflarePrefix)_zero_trust_network_hostname_routes": data.#cloudflare_zero_trust_network_hostname_routes
	_#ds: "\(#cloudflarePrefix)_zero_trust_organization": data.#cloudflare_zero_trust_organization
	_#ds: "\(#cloudflarePrefix)_zero_trust_risk_behavior": data.#cloudflare_zero_trust_risk_behavior
	_#ds: "\(#cloudflarePrefix)_zero_trust_risk_scoring_integration": data.#cloudflare_zero_trust_risk_scoring_integration
	_#ds: "\(#cloudflarePrefix)_zero_trust_risk_scoring_integrations": data.#cloudflare_zero_trust_risk_scoring_integrations
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflared_config": data.#cloudflare_zero_trust_tunnel_cloudflared_config
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflared": data.#cloudflare_zero_trust_tunnel_cloudflared
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflared_route": data.#cloudflare_zero_trust_tunnel_cloudflared_route
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflared_routes": data.#cloudflare_zero_trust_tunnel_cloudflared_routes
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflared_token": data.#cloudflare_zero_trust_tunnel_cloudflared_token
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflared_virtual_network": data.#cloudflare_zero_trust_tunnel_cloudflared_virtual_network
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflared_virtual_networks": data.#cloudflare_zero_trust_tunnel_cloudflared_virtual_networks
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_cloudflareds": data.#cloudflare_zero_trust_tunnel_cloudflareds
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_warp_connector": data.#cloudflare_zero_trust_tunnel_warp_connector
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_warp_connector_token": data.#cloudflare_zero_trust_tunnel_warp_connector_token
	_#ds: "\(#cloudflarePrefix)_zero_trust_tunnel_warp_connectors": data.#cloudflare_zero_trust_tunnel_warp_connectors
	_#ds: "\(#cloudflarePrefix)_zone_cache_reserve": data.#cloudflare_zone_cache_reserve
	_#ds: "\(#cloudflarePrefix)_zone_cache_variants": data.#cloudflare_zone_cache_variants
	_#ds: "\(#cloudflarePrefix)_zone_dns_settings": data.#cloudflare_zone_dns_settings
	_#ds: "\(#cloudflarePrefix)_zone_dnssec": data.#cloudflare_zone_dnssec
	_#ds: "\(#cloudflarePrefix)_zone": data.#cloudflare_zone
	_#ds: "\(#cloudflarePrefix)_zone_hold": data.#cloudflare_zone_hold
	_#ds: "\(#cloudflarePrefix)_zone_lockdown": data.#cloudflare_zone_lockdown
	_#ds: "\(#cloudflarePrefix)_zone_lockdowns": data.#cloudflare_zone_lockdowns
	_#ds: "\(#cloudflarePrefix)_zone_setting": data.#cloudflare_zone_setting
	_#ds: "\(#cloudflarePrefix)_zone_subscription": data.#cloudflare_zone_subscription
	_#ds: "\(#cloudflarePrefix)_zones": data.#cloudflare_zones

}
