package github

import "github.com/roman-mazur/cuetf/github/data"

_ds: github_actions_environment_secrets: data.#github_actions_environment_secrets
_ds: github_actions_environment_variables: data.#github_actions_environment_variables
_ds: github_actions_organization_oidc_subject_claim_customization_template: data.#github_actions_organization_oidc_subject_claim_customization_template
_ds: github_actions_organization_public_key: data.#github_actions_organization_public_key
_ds: github_actions_organization_registration_token: data.#github_actions_organization_registration_token
_ds: github_actions_organization_secrets: data.#github_actions_organization_secrets
_ds: github_actions_organization_variables: data.#github_actions_organization_variables
_ds: github_actions_public_key: data.#github_actions_public_key
_ds: github_actions_registration_token: data.#github_actions_registration_token
_ds: github_actions_repository_oidc_subject_claim_customization_template: data.#github_actions_repository_oidc_subject_claim_customization_template
_ds: github_actions_secrets: data.#github_actions_secrets
_ds: github_actions_variables: data.#github_actions_variables
_ds: github_app: data.#github_app
_ds: github_app_token: data.#github_app_token
_ds: github_branch: data.#github_branch
_ds: github_branch_protection_rules: data.#github_branch_protection_rules
_ds: github_codespaces_organization_public_key: data.#github_codespaces_organization_public_key
_ds: github_codespaces_organization_secrets: data.#github_codespaces_organization_secrets
_ds: github_codespaces_public_key: data.#github_codespaces_public_key
_ds: github_codespaces_secrets: data.#github_codespaces_secrets
_ds: github_codespaces_user_public_key: data.#github_codespaces_user_public_key
_ds: github_codespaces_user_secrets: data.#github_codespaces_user_secrets
_ds: github_collaborators: data.#github_collaborators
_ds: github_dependabot_organization_public_key: data.#github_dependabot_organization_public_key
_ds: github_dependabot_organization_secrets: data.#github_dependabot_organization_secrets
_ds: github_dependabot_public_key: data.#github_dependabot_public_key
_ds: github_dependabot_secrets: data.#github_dependabot_secrets
_ds: github_enterprise: data.#github_enterprise
_ds: github_external_groups: data.#github_external_groups
_ds: github_ip_ranges: data.#github_ip_ranges
_ds: github_issue_labels: data.#github_issue_labels
_ds: github_membership: data.#github_membership
_ds: github_organization_custom_role: data.#github_organization_custom_role
_ds: github_organization_external_identities: data.#github_organization_external_identities
_ds: github_organization: data.#github_organization
_ds: github_organization_ip_allow_list: data.#github_organization_ip_allow_list
_ds: github_organization_team_sync_groups: data.#github_organization_team_sync_groups
_ds: github_organization_teams: data.#github_organization_teams
_ds: github_organization_webhooks: data.#github_organization_webhooks
_ds: github_ref: data.#github_ref
_ds: github_release: data.#github_release
_ds: github_repositories: data.#github_repositories
_ds: github_repository_autolink_references: data.#github_repository_autolink_references
_ds: github_repository_branches: data.#github_repository_branches
_ds: github_repository_custom_properties: data.#github_repository_custom_properties
_ds: github_repository_deploy_keys: data.#github_repository_deploy_keys
_ds: github_repository_deployment_branch_policies: data.#github_repository_deployment_branch_policies
_ds: github_repository_environments: data.#github_repository_environments
_ds: github_repository_file: data.#github_repository_file
_ds: github_repository: data.#github_repository
_ds: github_repository_milestone: data.#github_repository_milestone
_ds: github_repository_pull_request: data.#github_repository_pull_request
_ds: github_repository_pull_requests: data.#github_repository_pull_requests
_ds: github_repository_teams: data.#github_repository_teams
_ds: github_repository_webhooks: data.#github_repository_webhooks
_ds: github_rest_api: data.#github_rest_api
_ds: github_ssh_keys: data.#github_ssh_keys
_ds: github_team: data.#github_team
_ds: github_tree: data.#github_tree
_ds: github_user_external_identity: data.#github_user_external_identity
_ds: github_user: data.#github_user
_ds: github_users: data.#github_users
