package github

import "github.com/roman-mazur/cuetf/github/res"

_res: github_actions_environment_secret:                                     res.#github_actions_environment_secret
_res: github_actions_environment_variable:                                   res.#github_actions_environment_variable
_res: github_actions_organization_oidc_subject_claim_customization_template: res.#github_actions_organization_oidc_subject_claim_customization_template
_res: github_actions_organization_permissions:                               res.#github_actions_organization_permissions
_res: github_actions_organization_secret:                                    res.#github_actions_organization_secret
_res: github_actions_organization_secret_repositories:                       res.#github_actions_organization_secret_repositories
_res: github_actions_organization_variable:                                  res.#github_actions_organization_variable
_res: github_actions_repository_access_level:                                res.#github_actions_repository_access_level
_res: github_actions_repository_oidc_subject_claim_customization_template:   res.#github_actions_repository_oidc_subject_claim_customization_template
_res: github_actions_repository_permissions:                                 res.#github_actions_repository_permissions
_res: github_actions_runner_group:                                           res.#github_actions_runner_group
_res: github_actions_secret:                                                 res.#github_actions_secret
_res: github_actions_variable:                                               res.#github_actions_variable
_res: github_app_installation_repositories:                                  res.#github_app_installation_repositories
_res: github_app_installation_repository:                                    res.#github_app_installation_repository
_res: github_branch_default:                                                 res.#github_branch_default
_res: github_branch:                                                         res.#github_branch
_res: github_branch_protection:                                              res.#github_branch_protection
_res: github_branch_protection_v3:                                           res.#github_branch_protection_v3
_res: github_codespaces_organization_secret:                                 res.#github_codespaces_organization_secret
_res: github_codespaces_organization_secret_repositories:                    res.#github_codespaces_organization_secret_repositories
_res: github_codespaces_secret:                                              res.#github_codespaces_secret
_res: github_codespaces_user_secret:                                         res.#github_codespaces_user_secret
_res: github_dependabot_organization_secret:                                 res.#github_dependabot_organization_secret
_res: github_dependabot_organization_secret_repositories:                    res.#github_dependabot_organization_secret_repositories
_res: github_dependabot_secret:                                              res.#github_dependabot_secret
_res: github_emu_group_mapping:                                              res.#github_emu_group_mapping
_res: github_enterprise_actions_permissions:                                 res.#github_enterprise_actions_permissions
_res: github_enterprise_actions_runner_group:                                res.#github_enterprise_actions_runner_group
_res: github_enterprise_organization:                                        res.#github_enterprise_organization
_res: github_issue:                                                          res.#github_issue
_res: github_issue_label:                                                    res.#github_issue_label
_res: github_issue_labels:                                                   res.#github_issue_labels
_res: github_membership:                                                     res.#github_membership
_res: github_organization_block:                                             res.#github_organization_block
_res: github_organization_custom_role:                                       res.#github_organization_custom_role
_res: github_organization_project:                                           res.#github_organization_project
_res: github_organization_security_manager:                                  res.#github_organization_security_manager
_res: github_organization_settings:                                          res.#github_organization_settings
_res: github_organization_webhook:                                           res.#github_organization_webhook
_res: github_project_card:                                                   res.#github_project_card
_res: github_project_column:                                                 res.#github_project_column
_res: github_release:                                                        res.#github_release
_res: github_repository_autolink_reference:                                  res.#github_repository_autolink_reference
_res: github_repository_collaborator:                                        res.#github_repository_collaborator
_res: github_repository_collaborators:                                       res.#github_repository_collaborators
_res: github_repository_dependabot_security_updates:                         res.#github_repository_dependabot_security_updates
_res: github_repository_deploy_key:                                          res.#github_repository_deploy_key
_res: github_repository_deployment_branch_policy:                            res.#github_repository_deployment_branch_policy
_res: github_repository_environment_deployment_policy:                       res.#github_repository_environment_deployment_policy
_res: github_repository_environment:                                         res.#github_repository_environment
_res: github_repository_file:                                                res.#github_repository_file
_res: github_repository:                                                     res.#github_repository
_res: github_repository_milestone:                                           res.#github_repository_milestone
_res: github_repository_project:                                             res.#github_repository_project
_res: github_repository_pull_request:                                        res.#github_repository_pull_request
_res: github_repository_tag_protection:                                      res.#github_repository_tag_protection
_res: github_repository_topics:                                              res.#github_repository_topics
_res: github_repository_webhook:                                             res.#github_repository_webhook
_res: github_team:                                                           res.#github_team
_res: github_team_members:                                                   res.#github_team_members
_res: github_team_membership:                                                res.#github_team_membership
_res: github_team_repository:                                                res.#github_team_repository
_res: github_team_settings:                                                  res.#github_team_settings
_res: github_team_sync_group_mapping:                                        res.#github_team_sync_group_mapping
_res: github_user_gpg_key:                                                   res.#github_user_gpg_key
_res: github_user_invitation_accepter:                                       res.#github_user_invitation_accepter
_res: github_user_ssh_key:                                                   res.#github_user_ssh_key
