package google

import "github.com/roman-mazur/cuetf/google/data"

#Terraform: {
	#prefix: string
	#ds: "\(#prefix)_access_approval_folder_service_account": data.#google_access_approval_folder_service_account
	#ds: "\(#prefix)_access_approval_organization_service_account": data.#google_access_approval_organization_service_account
	#ds: "\(#prefix)_access_approval_project_service_account": data.#google_access_approval_project_service_account
	#ds: "\(#prefix)_access_context_manager_access_policy": data.#google_access_context_manager_access_policy
	#ds: "\(#prefix)_access_context_manager_access_policy_iam_policy": data.#google_access_context_manager_access_policy_iam_policy
	#ds: "\(#prefix)_active_folder": data.#google_active_folder
	#ds: "\(#prefix)_alloydb_cluster": data.#google_alloydb_cluster
	#ds: "\(#prefix)_alloydb_instance": data.#google_alloydb_instance
	#ds: "\(#prefix)_alloydb_locations": data.#google_alloydb_locations
	#ds: "\(#prefix)_alloydb_supported_database_flags": data.#google_alloydb_supported_database_flags
	#ds: "\(#prefix)_apigee_environment_iam_policy": data.#google_apigee_environment_iam_policy
	#ds: "\(#prefix)_app_engine_default_service_account": data.#google_app_engine_default_service_account
	#ds: "\(#prefix)_apphub_application": data.#google_apphub_application
	#ds: "\(#prefix)_apphub_discovered_service": data.#google_apphub_discovered_service
	#ds: "\(#prefix)_apphub_discovered_workload": data.#google_apphub_discovered_workload
	#ds: "\(#prefix)_artifact_registry_docker_image": data.#google_artifact_registry_docker_image
	#ds: "\(#prefix)_artifact_registry_docker_images": data.#google_artifact_registry_docker_images
	#ds: "\(#prefix)_artifact_registry_locations": data.#google_artifact_registry_locations
	#ds: "\(#prefix)_artifact_registry_maven_artifact": data.#google_artifact_registry_maven_artifact
	#ds: "\(#prefix)_artifact_registry_maven_artifacts": data.#google_artifact_registry_maven_artifacts
	#ds: "\(#prefix)_artifact_registry_npm_package": data.#google_artifact_registry_npm_package
	#ds: "\(#prefix)_artifact_registry_npm_packages": data.#google_artifact_registry_npm_packages
	#ds: "\(#prefix)_artifact_registry_package": data.#google_artifact_registry_package
	#ds: "\(#prefix)_artifact_registry_packages": data.#google_artifact_registry_packages
	#ds: "\(#prefix)_artifact_registry_python_package": data.#google_artifact_registry_python_package
	#ds: "\(#prefix)_artifact_registry_repositories": data.#google_artifact_registry_repositories
	#ds: "\(#prefix)_artifact_registry_repository": data.#google_artifact_registry_repository
	#ds: "\(#prefix)_artifact_registry_repository_iam_policy": data.#google_artifact_registry_repository_iam_policy
	#ds: "\(#prefix)_artifact_registry_tag": data.#google_artifact_registry_tag
	#ds: "\(#prefix)_artifact_registry_tags": data.#google_artifact_registry_tags
	#ds: "\(#prefix)_artifact_registry_version": data.#google_artifact_registry_version
	#ds: "\(#prefix)_backup_dr_backup": data.#google_backup_dr_backup
	#ds: "\(#prefix)_backup_dr_backup_plan_association": data.#google_backup_dr_backup_plan_association
	#ds: "\(#prefix)_backup_dr_backup_plan_associations": data.#google_backup_dr_backup_plan_associations
	#ds: "\(#prefix)_backup_dr_backup_plan": data.#google_backup_dr_backup_plan
	#ds: "\(#prefix)_backup_dr_backup_vault": data.#google_backup_dr_backup_vault
	#ds: "\(#prefix)_backup_dr_data_source": data.#google_backup_dr_data_source
	#ds: "\(#prefix)_backup_dr_data_source_reference": data.#google_backup_dr_data_source_reference
	#ds: "\(#prefix)_backup_dr_data_source_references": data.#google_backup_dr_data_source_references
	#ds: "\(#prefix)_backup_dr_management_server": data.#google_backup_dr_management_server
	#ds: "\(#prefix)_beyondcorp_app_connection": data.#google_beyondcorp_app_connection
	#ds: "\(#prefix)_beyondcorp_app_connector": data.#google_beyondcorp_app_connector
	#ds: "\(#prefix)_beyondcorp_app_gateway": data.#google_beyondcorp_app_gateway
	#ds: "\(#prefix)_beyondcorp_security_gateway_application_iam_policy": data.#google_beyondcorp_security_gateway_application_iam_policy
	#ds: "\(#prefix)_beyondcorp_security_gateway": data.#google_beyondcorp_security_gateway
	#ds: "\(#prefix)_beyondcorp_security_gateway_iam_policy": data.#google_beyondcorp_security_gateway_iam_policy
	#ds: "\(#prefix)_bigquery_analytics_hub_data_exchange_iam_policy": data.#google_bigquery_analytics_hub_data_exchange_iam_policy
	#ds: "\(#prefix)_bigquery_analytics_hub_listing_iam_policy": data.#google_bigquery_analytics_hub_listing_iam_policy
	#ds: "\(#prefix)_bigquery_connection_iam_policy": data.#google_bigquery_connection_iam_policy
	#ds: "\(#prefix)_bigquery_datapolicy_data_policy_iam_policy": data.#google_bigquery_datapolicy_data_policy_iam_policy
	#ds: "\(#prefix)_bigquery_datapolicyv2_data_policy_iam_policy": data.#google_bigquery_datapolicyv2_data_policy_iam_policy
	#ds: "\(#prefix)_bigquery_dataset": data.#google_bigquery_dataset
	#ds: "\(#prefix)_bigquery_dataset_iam_policy": data.#google_bigquery_dataset_iam_policy
	#ds: "\(#prefix)_bigquery_datasets": data.#google_bigquery_datasets
	#ds: "\(#prefix)_bigquery_default_service_account": data.#google_bigquery_default_service_account
	#ds: "\(#prefix)_bigquery_table": data.#google_bigquery_table
	#ds: "\(#prefix)_bigquery_table_iam_policy": data.#google_bigquery_table_iam_policy
	#ds: "\(#prefix)_bigquery_tables": data.#google_bigquery_tables
	#ds: "\(#prefix)_bigtable_instance_iam_policy": data.#google_bigtable_instance_iam_policy
	#ds: "\(#prefix)_bigtable_table_iam_policy": data.#google_bigtable_table_iam_policy
	#ds: "\(#prefix)_billing_account": data.#google_billing_account
	#ds: "\(#prefix)_billing_account_iam_policy": data.#google_billing_account_iam_policy
	#ds: "\(#prefix)_binary_authorization_attestor_iam_policy": data.#google_binary_authorization_attestor_iam_policy
	#ds: "\(#prefix)_certificate_manager_certificate_map": data.#google_certificate_manager_certificate_map
	#ds: "\(#prefix)_certificate_manager_certificates": data.#google_certificate_manager_certificates
	#ds: "\(#prefix)_certificate_manager_dns_authorization": data.#google_certificate_manager_dns_authorization
	#ds: "\(#prefix)_client_config": data.#google_client_config
	#ds: "\(#prefix)_client_openid_userinfo": data.#google_client_openid_userinfo
	#ds: "\(#prefix)_cloud_asset_search_all_resources": data.#google_cloud_asset_search_all_resources
	#ds: "\(#prefix)_cloud_identity_group_lookup": data.#google_cloud_identity_group_lookup
	#ds: "\(#prefix)_cloud_identity_group_memberships": data.#google_cloud_identity_group_memberships
	#ds: "\(#prefix)_cloud_identity_group_transitive_memberships": data.#google_cloud_identity_group_transitive_memberships
	#ds: "\(#prefix)_cloud_identity_groups": data.#google_cloud_identity_groups
	#ds: "\(#prefix)_cloud_quotas_quota_info": data.#google_cloud_quotas_quota_info
	#ds: "\(#prefix)_cloud_quotas_quota_infos": data.#google_cloud_quotas_quota_infos
	#ds: "\(#prefix)_cloud_run_locations": data.#google_cloud_run_locations
	#ds: "\(#prefix)_cloud_run_service": data.#google_cloud_run_service
	#ds: "\(#prefix)_cloud_run_service_iam_policy": data.#google_cloud_run_service_iam_policy
	#ds: "\(#prefix)_cloud_run_v2_job": data.#google_cloud_run_v2_job
	#ds: "\(#prefix)_cloud_run_v2_job_iam_policy": data.#google_cloud_run_v2_job_iam_policy
	#ds: "\(#prefix)_cloud_run_v2_service": data.#google_cloud_run_v2_service
	#ds: "\(#prefix)_cloud_run_v2_service_iam_policy": data.#google_cloud_run_v2_service_iam_policy
	#ds: "\(#prefix)_cloud_run_v2_worker_pool": data.#google_cloud_run_v2_worker_pool
	#ds: "\(#prefix)_cloud_run_v2_worker_pool_iam_policy": data.#google_cloud_run_v2_worker_pool_iam_policy
	#ds: "\(#prefix)_cloud_tasks_queue_iam_policy": data.#google_cloud_tasks_queue_iam_policy
	#ds: "\(#prefix)_cloudbuild_trigger": data.#google_cloudbuild_trigger
	#ds: "\(#prefix)_cloudbuildv2_connection_iam_policy": data.#google_cloudbuildv2_connection_iam_policy
	#ds: "\(#prefix)_clouddeploy_custom_target_type_iam_policy": data.#google_clouddeploy_custom_target_type_iam_policy
	#ds: "\(#prefix)_clouddeploy_delivery_pipeline_iam_policy": data.#google_clouddeploy_delivery_pipeline_iam_policy
	#ds: "\(#prefix)_clouddeploy_target_iam_policy": data.#google_clouddeploy_target_iam_policy
	#ds: "\(#prefix)_cloudfunctions2_function": data.#google_cloudfunctions2_function
	#ds: "\(#prefix)_cloudfunctions2_function_iam_policy": data.#google_cloudfunctions2_function_iam_policy
	#ds: "\(#prefix)_cloudfunctions_function": data.#google_cloudfunctions_function
	#ds: "\(#prefix)_cloudfunctions_function_iam_policy": data.#google_cloudfunctions_function_iam_policy
	#ds: "\(#prefix)_colab_runtime_template_iam_policy": data.#google_colab_runtime_template_iam_policy
	#ds: "\(#prefix)_composer_environment": data.#google_composer_environment
	#ds: "\(#prefix)_composer_image_versions": data.#google_composer_image_versions
	#ds: "\(#prefix)_composer_user_workloads_config_map": data.#google_composer_user_workloads_config_map
	#ds: "\(#prefix)_composer_user_workloads_secret": data.#google_composer_user_workloads_secret
	#ds: "\(#prefix)_compute_address": data.#google_compute_address
	#ds: "\(#prefix)_compute_addresses": data.#google_compute_addresses
	#ds: "\(#prefix)_compute_backend_bucket": data.#google_compute_backend_bucket
	#ds: "\(#prefix)_compute_backend_service": data.#google_compute_backend_service
	#ds: "\(#prefix)_compute_default_service_account": data.#google_compute_default_service_account
	#ds: "\(#prefix)_compute_disk": data.#google_compute_disk
	#ds: "\(#prefix)_compute_disk_iam_policy": data.#google_compute_disk_iam_policy
	#ds: "\(#prefix)_compute_forwarding_rule": data.#google_compute_forwarding_rule
	#ds: "\(#prefix)_compute_forwarding_rules": data.#google_compute_forwarding_rules
	#ds: "\(#prefix)_compute_global_address": data.#google_compute_global_address
	#ds: "\(#prefix)_compute_global_forwarding_rule": data.#google_compute_global_forwarding_rule
	#ds: "\(#prefix)_compute_ha_vpn_gateway": data.#google_compute_ha_vpn_gateway
	#ds: "\(#prefix)_compute_health_check": data.#google_compute_health_check
	#ds: "\(#prefix)_compute_image": data.#google_compute_image
	#ds: "\(#prefix)_compute_image_iam_policy": data.#google_compute_image_iam_policy
	#ds: "\(#prefix)_compute_images": data.#google_compute_images
	#ds: "\(#prefix)_compute_instance": data.#google_compute_instance
	#ds: "\(#prefix)_compute_instance_group": data.#google_compute_instance_group
	#ds: "\(#prefix)_compute_instance_group_manager": data.#google_compute_instance_group_manager
	#ds: "\(#prefix)_compute_instance_guest_attributes": data.#google_compute_instance_guest_attributes
	#ds: "\(#prefix)_compute_instance_iam_policy": data.#google_compute_instance_iam_policy
	#ds: "\(#prefix)_compute_instance_serial_port": data.#google_compute_instance_serial_port
	#ds: "\(#prefix)_compute_instance_template": data.#google_compute_instance_template
	#ds: "\(#prefix)_compute_instance_template_iam_policy": data.#google_compute_instance_template_iam_policy
	#ds: "\(#prefix)_compute_instant_snapshot_iam_policy": data.#google_compute_instant_snapshot_iam_policy
	#ds: "\(#prefix)_compute_interconnect_location": data.#google_compute_interconnect_location
	#ds: "\(#prefix)_compute_interconnect_locations": data.#google_compute_interconnect_locations
	#ds: "\(#prefix)_compute_lb_ip_ranges": data.#google_compute_lb_ip_ranges
	#ds: "\(#prefix)_compute_machine_types": data.#google_compute_machine_types
	#ds: "\(#prefix)_compute_network_attachment": data.#google_compute_network_attachment
	#ds: "\(#prefix)_compute_network_endpoint_group": data.#google_compute_network_endpoint_group
	#ds: "\(#prefix)_compute_network": data.#google_compute_network
	#ds: "\(#prefix)_compute_network_peering": data.#google_compute_network_peering
	#ds: "\(#prefix)_compute_networks": data.#google_compute_networks
	#ds: "\(#prefix)_compute_node_types": data.#google_compute_node_types
	#ds: "\(#prefix)_compute_region_backend_service": data.#google_compute_region_backend_service
	#ds: "\(#prefix)_compute_region_disk": data.#google_compute_region_disk
	#ds: "\(#prefix)_compute_region_disk_iam_policy": data.#google_compute_region_disk_iam_policy
	#ds: "\(#prefix)_compute_region_instance_group": data.#google_compute_region_instance_group
	#ds: "\(#prefix)_compute_region_instance_group_manager": data.#google_compute_region_instance_group_manager
	#ds: "\(#prefix)_compute_region_instance_template": data.#google_compute_region_instance_template
	#ds: "\(#prefix)_compute_region_network_endpoint_group": data.#google_compute_region_network_endpoint_group
	#ds: "\(#prefix)_compute_region_ssl_certificate": data.#google_compute_region_ssl_certificate
	#ds: "\(#prefix)_compute_region_ssl_policy": data.#google_compute_region_ssl_policy
	#ds: "\(#prefix)_compute_regions": data.#google_compute_regions
	#ds: "\(#prefix)_compute_reservation": data.#google_compute_reservation
	#ds: "\(#prefix)_compute_resource_policy": data.#google_compute_resource_policy
	#ds: "\(#prefix)_compute_router": data.#google_compute_router
	#ds: "\(#prefix)_compute_router_nat": data.#google_compute_router_nat
	#ds: "\(#prefix)_compute_router_status": data.#google_compute_router_status
	#ds: "\(#prefix)_compute_security_policy": data.#google_compute_security_policy
	#ds: "\(#prefix)_compute_snapshot": data.#google_compute_snapshot
	#ds: "\(#prefix)_compute_snapshot_iam_policy": data.#google_compute_snapshot_iam_policy
	#ds: "\(#prefix)_compute_ssl_certificate": data.#google_compute_ssl_certificate
	#ds: "\(#prefix)_compute_ssl_policy": data.#google_compute_ssl_policy
	#ds: "\(#prefix)_compute_storage_pool_iam_policy": data.#google_compute_storage_pool_iam_policy
	#ds: "\(#prefix)_compute_storage_pool_types": data.#google_compute_storage_pool_types
	#ds: "\(#prefix)_compute_subnetwork": data.#google_compute_subnetwork
	#ds: "\(#prefix)_compute_subnetwork_iam_policy": data.#google_compute_subnetwork_iam_policy
	#ds: "\(#prefix)_compute_subnetworks": data.#google_compute_subnetworks
	#ds: "\(#prefix)_compute_vpn_gateway": data.#google_compute_vpn_gateway
	#ds: "\(#prefix)_compute_zones": data.#google_compute_zones
	#ds: "\(#prefix)_container_analysis_note_iam_policy": data.#google_container_analysis_note_iam_policy
	#ds: "\(#prefix)_container_attached_install_manifest": data.#google_container_attached_install_manifest
	#ds: "\(#prefix)_container_attached_versions": data.#google_container_attached_versions
	#ds: "\(#prefix)_container_aws_versions": data.#google_container_aws_versions
	#ds: "\(#prefix)_container_azure_versions": data.#google_container_azure_versions
	#ds: "\(#prefix)_container_cluster": data.#google_container_cluster
	#ds: "\(#prefix)_container_engine_versions": data.#google_container_engine_versions
	#ds: "\(#prefix)_container_registry_image": data.#google_container_registry_image
	#ds: "\(#prefix)_container_registry_repository": data.#google_container_registry_repository
	#ds: "\(#prefix)_data_catalog_entry_group_iam_policy": data.#google_data_catalog_entry_group_iam_policy
	#ds: "\(#prefix)_data_catalog_policy_tag_iam_policy": data.#google_data_catalog_policy_tag_iam_policy
	#ds: "\(#prefix)_data_catalog_tag_template_iam_policy": data.#google_data_catalog_tag_template_iam_policy
	#ds: "\(#prefix)_data_catalog_taxonomy_iam_policy": data.#google_data_catalog_taxonomy_iam_policy
	#ds: "\(#prefix)_data_fusion_instance_iam_policy": data.#google_data_fusion_instance_iam_policy
	#ds: "\(#prefix)_dataplex_aspect_type_iam_policy": data.#google_dataplex_aspect_type_iam_policy
	#ds: "\(#prefix)_dataplex_asset_iam_policy": data.#google_dataplex_asset_iam_policy
	#ds: "\(#prefix)_dataplex_data_quality_rules": data.#google_dataplex_data_quality_rules
	#ds: "\(#prefix)_dataplex_datascan_iam_policy": data.#google_dataplex_datascan_iam_policy
	#ds: "\(#prefix)_dataplex_entry_group_iam_policy": data.#google_dataplex_entry_group_iam_policy
	#ds: "\(#prefix)_dataplex_entry_type_iam_policy": data.#google_dataplex_entry_type_iam_policy
	#ds: "\(#prefix)_dataplex_glossary_iam_policy": data.#google_dataplex_glossary_iam_policy
	#ds: "\(#prefix)_dataplex_lake_iam_policy": data.#google_dataplex_lake_iam_policy
	#ds: "\(#prefix)_dataplex_task_iam_policy": data.#google_dataplex_task_iam_policy
	#ds: "\(#prefix)_dataplex_zone_iam_policy": data.#google_dataplex_zone_iam_policy
	#ds: "\(#prefix)_dataproc_autoscaling_policy_iam_policy": data.#google_dataproc_autoscaling_policy_iam_policy
	#ds: "\(#prefix)_dataproc_cluster_iam_policy": data.#google_dataproc_cluster_iam_policy
	#ds: "\(#prefix)_dataproc_job_iam_policy": data.#google_dataproc_job_iam_policy
	#ds: "\(#prefix)_dataproc_metastore_database_iam_policy": data.#google_dataproc_metastore_database_iam_policy
	#ds: "\(#prefix)_dataproc_metastore_federation_iam_policy": data.#google_dataproc_metastore_federation_iam_policy
	#ds: "\(#prefix)_dataproc_metastore_service": data.#google_dataproc_metastore_service
	#ds: "\(#prefix)_dataproc_metastore_service_iam_policy": data.#google_dataproc_metastore_service_iam_policy
	#ds: "\(#prefix)_dataproc_metastore_table_iam_policy": data.#google_dataproc_metastore_table_iam_policy
	#ds: "\(#prefix)_datastream_static_ips": data.#google_datastream_static_ips
	#ds: "\(#prefix)_dns_keys": data.#google_dns_keys
	#ds: "\(#prefix)_dns_managed_zone": data.#google_dns_managed_zone
	#ds: "\(#prefix)_dns_managed_zone_iam_policy": data.#google_dns_managed_zone_iam_policy
	#ds: "\(#prefix)_dns_managed_zones": data.#google_dns_managed_zones
	#ds: "\(#prefix)_dns_record_set": data.#google_dns_record_set
	#ds: "\(#prefix)_endpoints_service_consumers_iam_policy": data.#google_endpoints_service_consumers_iam_policy
	#ds: "\(#prefix)_endpoints_service_iam_policy": data.#google_endpoints_service_iam_policy
	#ds: "\(#prefix)_filestore_instance": data.#google_filestore_instance
	#ds: "\(#prefix)_firestore_document": data.#google_firestore_document
	#ds: "\(#prefix)_folder": data.#google_folder
	#ds: "\(#prefix)_folder_iam_policy": data.#google_folder_iam_policy
	#ds: "\(#prefix)_folder_organization_policy": data.#google_folder_organization_policy
	#ds: "\(#prefix)_folders": data.#google_folders
	#ds: "\(#prefix)_gemini_repository_group_iam_policy": data.#google_gemini_repository_group_iam_policy
	#ds: "\(#prefix)_gke_backup_backup_plan_iam_policy": data.#google_gke_backup_backup_plan_iam_policy
	#ds: "\(#prefix)_gke_backup_restore_plan_iam_policy": data.#google_gke_backup_restore_plan_iam_policy
	#ds: "\(#prefix)_gke_hub_feature": data.#google_gke_hub_feature
	#ds: "\(#prefix)_gke_hub_feature_iam_policy": data.#google_gke_hub_feature_iam_policy
	#ds: "\(#prefix)_gke_hub_membership_binding": data.#google_gke_hub_membership_binding
	#ds: "\(#prefix)_gke_hub_membership": data.#google_gke_hub_membership
	#ds: "\(#prefix)_gke_hub_membership_iam_policy": data.#google_gke_hub_membership_iam_policy
	#ds: "\(#prefix)_gke_hub_scope_iam_policy": data.#google_gke_hub_scope_iam_policy
	#ds: "\(#prefix)_healthcare_consent_store_iam_policy": data.#google_healthcare_consent_store_iam_policy
	#ds: "\(#prefix)_healthcare_dataset_iam_policy": data.#google_healthcare_dataset_iam_policy
	#ds: "\(#prefix)_healthcare_dicom_store_iam_policy": data.#google_healthcare_dicom_store_iam_policy
	#ds: "\(#prefix)_healthcare_fhir_store_iam_policy": data.#google_healthcare_fhir_store_iam_policy
	#ds: "\(#prefix)_healthcare_hl7_v2_store_iam_policy": data.#google_healthcare_hl7_v2_store_iam_policy
	#ds: "\(#prefix)_iam_policy": data.#google_iam_policy
	#ds: "\(#prefix)_iam_role": data.#google_iam_role
	#ds: "\(#prefix)_iam_testable_permissions": data.#google_iam_testable_permissions
	#ds: "\(#prefix)_iam_workforce_pool_iam_policy": data.#google_iam_workforce_pool_iam_policy
	#ds: "\(#prefix)_iam_workload_identity_pool": data.#google_iam_workload_identity_pool
	#ds: "\(#prefix)_iam_workload_identity_pool_provider": data.#google_iam_workload_identity_pool_provider
	#ds: "\(#prefix)_iap_app_engine_service_iam_policy": data.#google_iap_app_engine_service_iam_policy
	#ds: "\(#prefix)_iap_app_engine_version_iam_policy": data.#google_iap_app_engine_version_iam_policy
	#ds: "\(#prefix)_iap_client": data.#google_iap_client
	#ds: "\(#prefix)_iap_tunnel_dest_group_iam_policy": data.#google_iap_tunnel_dest_group_iam_policy
	#ds: "\(#prefix)_iap_tunnel_iam_policy": data.#google_iap_tunnel_iam_policy
	#ds: "\(#prefix)_iap_tunnel_instance_iam_policy": data.#google_iap_tunnel_instance_iam_policy
	#ds: "\(#prefix)_iap_web_backend_service_iam_policy": data.#google_iap_web_backend_service_iam_policy
	#ds: "\(#prefix)_iap_web_cloud_run_service_iam_policy": data.#google_iap_web_cloud_run_service_iam_policy
	#ds: "\(#prefix)_iap_web_forwarding_rule_service_iam_policy": data.#google_iap_web_forwarding_rule_service_iam_policy
	#ds: "\(#prefix)_iap_web_iam_policy": data.#google_iap_web_iam_policy
	#ds: "\(#prefix)_iap_web_region_backend_service_iam_policy": data.#google_iap_web_region_backend_service_iam_policy
	#ds: "\(#prefix)_iap_web_region_forwarding_rule_service_iam_policy": data.#google_iap_web_region_forwarding_rule_service_iam_policy
	#ds: "\(#prefix)_iap_web_type_app_engine_iam_policy": data.#google_iap_web_type_app_engine_iam_policy
	#ds: "\(#prefix)_iap_web_type_compute_iam_policy": data.#google_iap_web_type_compute_iam_policy
	#ds: "\(#prefix)_kms_autokey_config": data.#google_kms_autokey_config
	#ds: "\(#prefix)_kms_crypto_key": data.#google_kms_crypto_key
	#ds: "\(#prefix)_kms_crypto_key_iam_policy": data.#google_kms_crypto_key_iam_policy
	#ds: "\(#prefix)_kms_crypto_key_latest_version": data.#google_kms_crypto_key_latest_version
	#ds: "\(#prefix)_kms_crypto_key_version": data.#google_kms_crypto_key_version
	#ds: "\(#prefix)_kms_crypto_key_versions": data.#google_kms_crypto_key_versions
	#ds: "\(#prefix)_kms_crypto_keys": data.#google_kms_crypto_keys
	#ds: "\(#prefix)_kms_ekm_connection_iam_policy": data.#google_kms_ekm_connection_iam_policy
	#ds: "\(#prefix)_kms_key_handle": data.#google_kms_key_handle
	#ds: "\(#prefix)_kms_key_handles": data.#google_kms_key_handles
	#ds: "\(#prefix)_kms_key_ring": data.#google_kms_key_ring
	#ds: "\(#prefix)_kms_key_ring_iam_policy": data.#google_kms_key_ring_iam_policy
	#ds: "\(#prefix)_kms_key_rings": data.#google_kms_key_rings
	#ds: "\(#prefix)_kms_secret_ciphertext": data.#google_kms_secret_ciphertext
	#ds: "\(#prefix)_kms_secret": data.#google_kms_secret
	#ds: "\(#prefix)_logging_folder_settings": data.#google_logging_folder_settings
	#ds: "\(#prefix)_logging_log_view_iam_policy": data.#google_logging_log_view_iam_policy
	#ds: "\(#prefix)_logging_organization_settings": data.#google_logging_organization_settings
	#ds: "\(#prefix)_logging_project_cmek_settings": data.#google_logging_project_cmek_settings
	#ds: "\(#prefix)_logging_project_settings": data.#google_logging_project_settings
	#ds: "\(#prefix)_logging_sink": data.#google_logging_sink
	#ds: "\(#prefix)_lustre_instance": data.#google_lustre_instance
	#ds: "\(#prefix)_memcache_instance": data.#google_memcache_instance
	#ds: "\(#prefix)_memorystore_instance": data.#google_memorystore_instance
	#ds: "\(#prefix)_monitoring_app_engine_service": data.#google_monitoring_app_engine_service
	#ds: "\(#prefix)_monitoring_cluster_istio_service": data.#google_monitoring_cluster_istio_service
	#ds: "\(#prefix)_monitoring_istio_canonical_service": data.#google_monitoring_istio_canonical_service
	#ds: "\(#prefix)_monitoring_mesh_istio_service": data.#google_monitoring_mesh_istio_service
	#ds: "\(#prefix)_monitoring_notification_channel": data.#google_monitoring_notification_channel
	#ds: "\(#prefix)_monitoring_uptime_check_ips": data.#google_monitoring_uptime_check_ips
	#ds: "\(#prefix)_netblock_ip_ranges": data.#google_netblock_ip_ranges
	#ds: "\(#prefix)_network_management_connectivity_test_run": data.#google_network_management_connectivity_test_run
	#ds: "\(#prefix)_network_management_connectivity_tests": data.#google_network_management_connectivity_tests
	#ds: "\(#prefix)_network_security_address_group_iam_policy": data.#google_network_security_address_group_iam_policy
	#ds: "\(#prefix)_notebooks_instance_iam_policy": data.#google_notebooks_instance_iam_policy
	#ds: "\(#prefix)_notebooks_runtime_iam_policy": data.#google_notebooks_runtime_iam_policy
	#ds: "\(#prefix)_oracle_database_autonomous_database": data.#google_oracle_database_autonomous_database
	#ds: "\(#prefix)_oracle_database_autonomous_databases": data.#google_oracle_database_autonomous_databases
	#ds: "\(#prefix)_oracle_database_cloud_exadata_infrastructure": data.#google_oracle_database_cloud_exadata_infrastructure
	#ds: "\(#prefix)_oracle_database_cloud_exadata_infrastructures": data.#google_oracle_database_cloud_exadata_infrastructures
	#ds: "\(#prefix)_oracle_database_cloud_vm_cluster": data.#google_oracle_database_cloud_vm_cluster
	#ds: "\(#prefix)_oracle_database_cloud_vm_clusters": data.#google_oracle_database_cloud_vm_clusters
	#ds: "\(#prefix)_oracle_database_db_nodes": data.#google_oracle_database_db_nodes
	#ds: "\(#prefix)_oracle_database_db_servers": data.#google_oracle_database_db_servers
	#ds: "\(#prefix)_organization": data.#google_organization
	#ds: "\(#prefix)_organization_iam_custom_role": data.#google_organization_iam_custom_role
	#ds: "\(#prefix)_organization_iam_custom_roles": data.#google_organization_iam_custom_roles
	#ds: "\(#prefix)_organization_iam_policy": data.#google_organization_iam_policy
	#ds: "\(#prefix)_organizations": data.#google_organizations
	#ds: "\(#prefix)_parameter_manager_parameter": data.#google_parameter_manager_parameter
	#ds: "\(#prefix)_parameter_manager_parameter_version": data.#google_parameter_manager_parameter_version
	#ds: "\(#prefix)_parameter_manager_parameter_version_render": data.#google_parameter_manager_parameter_version_render
	#ds: "\(#prefix)_parameter_manager_parameters": data.#google_parameter_manager_parameters
	#ds: "\(#prefix)_parameter_manager_regional_parameter": data.#google_parameter_manager_regional_parameter
	#ds: "\(#prefix)_parameter_manager_regional_parameter_version": data.#google_parameter_manager_regional_parameter_version
	#ds: "\(#prefix)_parameter_manager_regional_parameter_version_render": data.#google_parameter_manager_regional_parameter_version_render
	#ds: "\(#prefix)_parameter_manager_regional_parameters": data.#google_parameter_manager_regional_parameters
	#ds: "\(#prefix)_privateca_ca_pool_iam_policy": data.#google_privateca_ca_pool_iam_policy
	#ds: "\(#prefix)_privateca_certificate_authority": data.#google_privateca_certificate_authority
	#ds: "\(#prefix)_privateca_certificate_template_iam_policy": data.#google_privateca_certificate_template_iam_policy
	#ds: "\(#prefix)_privileged_access_manager_entitlement": data.#google_privileged_access_manager_entitlement
	#ds: "\(#prefix)_project_ancestry": data.#google_project_ancestry
	#ds: "\(#prefix)_project": data.#google_project
	#ds: "\(#prefix)_project_iam_custom_role": data.#google_project_iam_custom_role
	#ds: "\(#prefix)_project_iam_custom_roles": data.#google_project_iam_custom_roles
	#ds: "\(#prefix)_project_iam_policy": data.#google_project_iam_policy
	#ds: "\(#prefix)_project_organization_policy": data.#google_project_organization_policy
	#ds: "\(#prefix)_project_service": data.#google_project_service
	#ds: "\(#prefix)_projects": data.#google_projects
	#ds: "\(#prefix)_pubsub_schema_iam_policy": data.#google_pubsub_schema_iam_policy
	#ds: "\(#prefix)_pubsub_subscription": data.#google_pubsub_subscription
	#ds: "\(#prefix)_pubsub_subscription_iam_policy": data.#google_pubsub_subscription_iam_policy
	#ds: "\(#prefix)_pubsub_topic": data.#google_pubsub_topic
	#ds: "\(#prefix)_pubsub_topic_iam_policy": data.#google_pubsub_topic_iam_policy
	#ds: "\(#prefix)_redis_cluster": data.#google_redis_cluster
	#ds: "\(#prefix)_redis_instance": data.#google_redis_instance
	#ds: "\(#prefix)_scc_source_iam_policy": data.#google_scc_source_iam_policy
	#ds: "\(#prefix)_scc_v2_organization_source_iam_policy": data.#google_scc_v2_organization_source_iam_policy
	#ds: "\(#prefix)_secret_manager_regional_secret": data.#google_secret_manager_regional_secret
	#ds: "\(#prefix)_secret_manager_regional_secret_iam_policy": data.#google_secret_manager_regional_secret_iam_policy
	#ds: "\(#prefix)_secret_manager_regional_secret_version_access": data.#google_secret_manager_regional_secret_version_access
	#ds: "\(#prefix)_secret_manager_regional_secret_version": data.#google_secret_manager_regional_secret_version
	#ds: "\(#prefix)_secret_manager_regional_secrets": data.#google_secret_manager_regional_secrets
	#ds: "\(#prefix)_secret_manager_secret": data.#google_secret_manager_secret
	#ds: "\(#prefix)_secret_manager_secret_iam_policy": data.#google_secret_manager_secret_iam_policy
	#ds: "\(#prefix)_secret_manager_secret_version_access": data.#google_secret_manager_secret_version_access
	#ds: "\(#prefix)_secret_manager_secret_version": data.#google_secret_manager_secret_version
	#ds: "\(#prefix)_secret_manager_secrets": data.#google_secret_manager_secrets
	#ds: "\(#prefix)_secure_source_manager_instance_iam_policy": data.#google_secure_source_manager_instance_iam_policy
	#ds: "\(#prefix)_secure_source_manager_repository_iam_policy": data.#google_secure_source_manager_repository_iam_policy
	#ds: "\(#prefix)_service_account_access_token": data.#google_service_account_access_token
	#ds: "\(#prefix)_service_account": data.#google_service_account
	#ds: "\(#prefix)_service_account_iam_policy": data.#google_service_account_iam_policy
	#ds: "\(#prefix)_service_account_id_token": data.#google_service_account_id_token
	#ds: "\(#prefix)_service_account_jwt": data.#google_service_account_jwt
	#ds: "\(#prefix)_service_account_key": data.#google_service_account_key
	#ds: "\(#prefix)_service_accounts": data.#google_service_accounts
	#ds: "\(#prefix)_service_networking_peered_dns_domain": data.#google_service_networking_peered_dns_domain
	#ds: "\(#prefix)_site_verification_token": data.#google_site_verification_token
	#ds: "\(#prefix)_sourcerepo_repository": data.#google_sourcerepo_repository
	#ds: "\(#prefix)_sourcerepo_repository_iam_policy": data.#google_sourcerepo_repository_iam_policy
	#ds: "\(#prefix)_spanner_database": data.#google_spanner_database
	#ds: "\(#prefix)_spanner_database_iam_policy": data.#google_spanner_database_iam_policy
	#ds: "\(#prefix)_spanner_instance": data.#google_spanner_instance
	#ds: "\(#prefix)_spanner_instance_iam_policy": data.#google_spanner_instance_iam_policy
	#ds: "\(#prefix)_sql_backup_run": data.#google_sql_backup_run
	#ds: "\(#prefix)_sql_ca_certs": data.#google_sql_ca_certs
	#ds: "\(#prefix)_sql_database": data.#google_sql_database
	#ds: "\(#prefix)_sql_database_instance": data.#google_sql_database_instance
	#ds: "\(#prefix)_sql_database_instance_latest_recovery_time": data.#google_sql_database_instance_latest_recovery_time
	#ds: "\(#prefix)_sql_database_instances": data.#google_sql_database_instances
	#ds: "\(#prefix)_sql_databases": data.#google_sql_databases
	#ds: "\(#prefix)_sql_tiers": data.#google_sql_tiers
	#ds: "\(#prefix)_storage_bucket": data.#google_storage_bucket
	#ds: "\(#prefix)_storage_bucket_iam_policy": data.#google_storage_bucket_iam_policy
	#ds: "\(#prefix)_storage_bucket_object_content": data.#google_storage_bucket_object_content
	#ds: "\(#prefix)_storage_bucket_object": data.#google_storage_bucket_object
	#ds: "\(#prefix)_storage_bucket_objects": data.#google_storage_bucket_objects
	#ds: "\(#prefix)_storage_buckets": data.#google_storage_buckets
	#ds: "\(#prefix)_storage_control_folder_intelligence_config": data.#google_storage_control_folder_intelligence_config
	#ds: "\(#prefix)_storage_control_organization_intelligence_config": data.#google_storage_control_organization_intelligence_config
	#ds: "\(#prefix)_storage_control_project_intelligence_config": data.#google_storage_control_project_intelligence_config
	#ds: "\(#prefix)_storage_insights_dataset_config": data.#google_storage_insights_dataset_config
	#ds: "\(#prefix)_storage_managed_folder_iam_policy": data.#google_storage_managed_folder_iam_policy
	#ds: "\(#prefix)_storage_object_signed_url": data.#google_storage_object_signed_url
	#ds: "\(#prefix)_storage_project_service_account": data.#google_storage_project_service_account
	#ds: "\(#prefix)_storage_transfer_project_service_account": data.#google_storage_transfer_project_service_account
	#ds: "\(#prefix)_tags_tag_key": data.#google_tags_tag_key
	#ds: "\(#prefix)_tags_tag_key_iam_policy": data.#google_tags_tag_key_iam_policy
	#ds: "\(#prefix)_tags_tag_keys": data.#google_tags_tag_keys
	#ds: "\(#prefix)_tags_tag_value": data.#google_tags_tag_value
	#ds: "\(#prefix)_tags_tag_value_iam_policy": data.#google_tags_tag_value_iam_policy
	#ds: "\(#prefix)_tags_tag_values": data.#google_tags_tag_values
	#ds: "\(#prefix)_vertex_ai_index": data.#google_vertex_ai_index
	#ds: "\(#prefix)_vmwareengine_cluster": data.#google_vmwareengine_cluster
	#ds: "\(#prefix)_vmwareengine_external_access_rule": data.#google_vmwareengine_external_access_rule
	#ds: "\(#prefix)_vmwareengine_external_address": data.#google_vmwareengine_external_address
	#ds: "\(#prefix)_vmwareengine_network": data.#google_vmwareengine_network
	#ds: "\(#prefix)_vmwareengine_network_peering": data.#google_vmwareengine_network_peering
	#ds: "\(#prefix)_vmwareengine_network_policy": data.#google_vmwareengine_network_policy
	#ds: "\(#prefix)_vmwareengine_nsx_credentials": data.#google_vmwareengine_nsx_credentials
	#ds: "\(#prefix)_vmwareengine_private_cloud": data.#google_vmwareengine_private_cloud
	#ds: "\(#prefix)_vmwareengine_subnet": data.#google_vmwareengine_subnet
	#ds: "\(#prefix)_vmwareengine_vcenter_credentials": data.#google_vmwareengine_vcenter_credentials
	#ds: "\(#prefix)_vpc_access_connector": data.#google_vpc_access_connector
	#ds: "\(#prefix)_workbench_instance_iam_policy": data.#google_workbench_instance_iam_policy

}
