package data

#google_compute_ha_vpn_gateway: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/data/google_compute_ha_vpn_gateway")
	close({
		// An optional description of this resource.
		description?: string

		// All of labels (key/value pairs) present on the resource in GCP,
		// including the labels configured through Terraform, other
		// clients and services.
		effective_labels?: [string]: string

		// The IP family of the gateway IPs for the HA-VPN gateway
		// interfaces. If not specified, IPV4 will be used. Default
		// value: "IPV4" Possible values: ["IPV4", "IPV6"]
		gateway_ip_version?: string

		// A fingerprint for the labels being applied to this VpnGateway,
		// which is essentially a hash
		// of the labels set used for optimistic locking. The fingerprint
		// is initially generated by
		// Compute Engine and changes after every request to modify or
		// update labels.
		// You must always provide an up-to-date fingerprint hash in order
		// to update or change labels,
		// otherwise the request will fail with error 412 conditionNotMet.
		label_fingerprint?: string
		id?:                string

		// Labels for this resource. These can only be added or modified
		// by the setLabels method.
		// Each label key/value pair must comply with RFC1035. Label
		// values may be empty.
		//
		//
		// **Note**: This field is non-authoritative, and will only manage
		// the labels present in your configuration.
		// Please refer to the field 'effective_labels' for all of the
		// labels present on the resource.
		labels?: [string]: string

		// Name of the resource. Provided by the client when the resource
		// is
		// created. The name must be 1-63 characters long, and comply with
		// RFC1035. Specifically, the name must be 1-63 characters long
		// and
		// match the regular expression '[a-z]([-a-z0-9]*[a-z0-9])?' which
		// means
		// the first character must be a lowercase letter, and all
		// following
		// characters must be a dash, lowercase letter, or digit, except
		// the last
		// character, which cannot be a dash.
		name!: string

		// The network this VPN gateway is accepting traffic for.
		network?: string
		project?: string

		// The region this gateway should sit in.
		region?:    string
		self_link?: string

		// The stack type for this VPN gateway to identify the IP
		// protocols that are enabled.
		// If not specified, IPV4_ONLY will be used. Default value:
		// "IPV4_ONLY" Possible values: ["IPV4_ONLY", "IPV4_IPV6",
		// "IPV6_ONLY"]
		stack_type?: string

		// The combination of labels configured directly on the resource
		// and default labels configured on the provider.
		terraform_labels?: [string]: string

		// A list of interfaces on this VPN gateway.
		vpn_interfaces?: [...close({
			id?:                      number
			interconnect_attachment?: string
			ip_address?:              string
		})]
	})
}
