package res

#elasticstack_kibana_security_exception_list: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/elasticstack_kibana_security_exception_list")
	close({
		kibana_connection?: matchN(1, [#kibana_connection, [...#kibana_connection]])

		// The timestamp of when the exception list was created.
		created_at?: string

		// The user who created the exception list.
		created_by?: string

		// Describes the exception list.
		description!: string

		// The unique identifier of the exception list (auto-generated by
		// Kibana).
		id?: string

		// Whether the exception list is immutable.
		immutable?: bool

		// The exception list's human readable string identifier.
		list_id?: string

		// Placeholder for metadata about the list container as JSON
		// string.
		meta?: string

		// The name of the exception list.
		name!: string

		// Determines whether the exception list is available in all
		// Kibana spaces or just the space in which it is created. Can be
		// `single` (default) or `agnostic`.
		namespace_type?: string

		// Array of OS types for which the exceptions apply. Valid values:
		// `linux`, `macos`, `windows`.
		os_types?: [...string]

		// An identifier for the space. If space_id is not provided, the
		// default space is used.
		space_id?: string

		// String array containing words and phrases to help categorize
		// exception containers.
		tags?: [...string]

		// Field used in search to ensure all containers are sorted and
		// returned correctly.
		tie_breaker_id?: string

		// The type of exception list. Can be one of: `detection`,
		// `endpoint`, `endpoint_trusted_apps`, `endpoint_events`,
		// `endpoint_host_isolation_exceptions`, `endpoint_blocklists`.
		type!: string

		// The timestamp of when the exception list was last updated.
		updated_at?: string

		// The user who last updated the exception list.
		updated_by?: string
	})

	#kibana_connection: close({
		// API Key to use for authentication to Kibana
		api_key?: string

		// Bearer Token to use for authentication to Kibana
		bearer_token?: string

		// A list of paths to CA certificates to validate the certificate
		// presented by the Kibana server.
		ca_certs?: [...string]

		// A comma-separated list of endpoints where the terraform
		// provider will point to, this must include the http(s) schema
		// and port number.
		endpoints?: [...string]

		// Disable TLS certificate validation
		insecure?: bool

		// Password to use for API authentication to Kibana.
		password?: string

		// Username to use for API authentication to Kibana.
		username?: string
	})
}
