package elasticstack

import "github.com/roman-mazur/cuetf/elasticstack/res"

_res: elasticstack_apm_agent_configuration: res.#elasticstack_apm_agent_configuration
_res: elasticstack_elasticsearch_cluster_settings: res.#elasticstack_elasticsearch_cluster_settings
_res: elasticstack_elasticsearch_component_template: res.#elasticstack_elasticsearch_component_template
_res: elasticstack_elasticsearch_data_stream: res.#elasticstack_elasticsearch_data_stream
_res: elasticstack_elasticsearch_data_stream_lifecycle: res.#elasticstack_elasticsearch_data_stream_lifecycle
_res: elasticstack_elasticsearch_enrich_policy: res.#elasticstack_elasticsearch_enrich_policy
_res: elasticstack_elasticsearch_index: res.#elasticstack_elasticsearch_index
_res: elasticstack_elasticsearch_index_lifecycle: res.#elasticstack_elasticsearch_index_lifecycle
_res: elasticstack_elasticsearch_index_template: res.#elasticstack_elasticsearch_index_template
_res: elasticstack_elasticsearch_ingest_pipeline: res.#elasticstack_elasticsearch_ingest_pipeline
_res: elasticstack_elasticsearch_logstash_pipeline: res.#elasticstack_elasticsearch_logstash_pipeline
_res: elasticstack_elasticsearch_script: res.#elasticstack_elasticsearch_script
_res: elasticstack_elasticsearch_security_api_key: res.#elasticstack_elasticsearch_security_api_key
_res: elasticstack_elasticsearch_security_role: res.#elasticstack_elasticsearch_security_role
_res: elasticstack_elasticsearch_security_role_mapping: res.#elasticstack_elasticsearch_security_role_mapping
_res: elasticstack_elasticsearch_security_system_user: res.#elasticstack_elasticsearch_security_system_user
_res: elasticstack_elasticsearch_security_user: res.#elasticstack_elasticsearch_security_user
_res: elasticstack_elasticsearch_snapshot_lifecycle: res.#elasticstack_elasticsearch_snapshot_lifecycle
_res: elasticstack_elasticsearch_snapshot_repository: res.#elasticstack_elasticsearch_snapshot_repository
_res: elasticstack_elasticsearch_transform: res.#elasticstack_elasticsearch_transform
_res: elasticstack_elasticsearch_watch: res.#elasticstack_elasticsearch_watch
_res: elasticstack_fleet_agent_policy: res.#elasticstack_fleet_agent_policy
_res: elasticstack_fleet_integration: res.#elasticstack_fleet_integration
_res: elasticstack_fleet_integration_policy: res.#elasticstack_fleet_integration_policy
_res: elasticstack_fleet_output: res.#elasticstack_fleet_output
_res: elasticstack_fleet_server_host: res.#elasticstack_fleet_server_host
_res: elasticstack_kibana_action_connector: res.#elasticstack_kibana_action_connector
_res: elasticstack_kibana_alerting_rule: res.#elasticstack_kibana_alerting_rule
_res: elasticstack_kibana_data_view: res.#elasticstack_kibana_data_view
_res: elasticstack_kibana_import_saved_objects: res.#elasticstack_kibana_import_saved_objects
_res: elasticstack_kibana_security_role: res.#elasticstack_kibana_security_role
_res: elasticstack_kibana_slo: res.#elasticstack_kibana_slo
_res: elasticstack_kibana_space: res.#elasticstack_kibana_space
_res: elasticstack_kibana_synthetics_monitor: res.#elasticstack_kibana_synthetics_monitor
_res: elasticstack_kibana_synthetics_parameter: res.#elasticstack_kibana_synthetics_parameter
_res: elasticstack_kibana_synthetics_private_location: res.#elasticstack_kibana_synthetics_private_location
