package euwest1

AvailabilityZones: [{
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-1"
	ZoneName:           "eu-west-1a"
	ZoneId:             "euw1-az3"
	GroupName:          "eu-west-1"
	NetworkBorderGroup: "eu-west-1"
	ZoneType:           "availability-zone"
}, {
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-1"
	ZoneName:           "eu-west-1b"
	ZoneId:             "euw1-az1"
	GroupName:          "eu-west-1"
	NetworkBorderGroup: "eu-west-1"
	ZoneType:           "availability-zone"
}, {
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-1"
	ZoneName:           "eu-west-1c"
	ZoneId:             "euw1-az2"
	GroupName:          "eu-west-1"
	NetworkBorderGroup: "eu-west-1"
	ZoneType:           "availability-zone"
}]
