package github

import (
	"github.com/roman-mazur/cuetf"
	"github.com/roman-mazur/cuetf/providers/github/data"
)

#Terraform: {
	#githubPrefix: string
	_#ds: "\(#githubPrefix)_actions_environment_public_key": close({data.github_actions_environment_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_environment_secrets": close({data.github_actions_environment_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_environment_variables": close({data.github_actions_environment_variables & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_organization_oidc_subject_claim_customization_template": close({data.github_actions_organization_oidc_subject_claim_customization_template & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_organization_public_key": close({data.github_actions_organization_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_organization_registration_token": close({data.github_actions_organization_registration_token & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_organization_secrets": close({data.github_actions_organization_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_organization_variables": close({data.github_actions_organization_variables & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_public_key": close({data.github_actions_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_registration_token": close({data.github_actions_registration_token & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_repository_oidc_subject_claim_customization_template": close({data.github_actions_repository_oidc_subject_claim_customization_template & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_secrets": close({data.github_actions_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_actions_variables": close({data.github_actions_variables & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_app": close({data.github_app & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_app_token": close({data.github_app_token & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_branch": close({data.github_branch & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_branch_protection_rules": close({data.github_branch_protection_rules & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_codespaces_organization_public_key": close({data.github_codespaces_organization_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_codespaces_organization_secrets": close({data.github_codespaces_organization_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_codespaces_public_key": close({data.github_codespaces_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_codespaces_secrets": close({data.github_codespaces_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_codespaces_user_public_key": close({data.github_codespaces_user_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_codespaces_user_secrets": close({data.github_codespaces_user_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_collaborators": close({data.github_collaborators & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_dependabot_organization_public_key": close({data.github_dependabot_organization_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_dependabot_organization_secrets": close({data.github_dependabot_organization_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_dependabot_public_key": close({data.github_dependabot_public_key & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_dependabot_secrets": close({data.github_dependabot_secrets & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_enterprise": close({data.github_enterprise & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_external_groups": close({data.github_external_groups & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_ip_ranges": close({data.github_ip_ranges & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_issue_labels": close({data.github_issue_labels & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_membership": close({data.github_membership & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_app_installations": close({data.github_organization_app_installations & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_custom_properties": close({data.github_organization_custom_properties & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_custom_role": close({data.github_organization_custom_role & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_external_identities": close({data.github_organization_external_identities & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization": close({data.github_organization & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_ip_allow_list": close({data.github_organization_ip_allow_list & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_repository_role": close({data.github_organization_repository_role & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_repository_roles": close({data.github_organization_repository_roles & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_role": close({data.github_organization_role & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_role_teams": close({data.github_organization_role_teams & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_role_users": close({data.github_organization_role_users & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_roles": close({data.github_organization_roles & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_security_managers": close({data.github_organization_security_managers & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_team_sync_groups": close({data.github_organization_team_sync_groups & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_teams": close({data.github_organization_teams & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_organization_webhooks": close({data.github_organization_webhooks & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_ref": close({data.github_ref & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_release_asset": close({data.github_release_asset & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_release": close({data.github_release & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repositories": close({data.github_repositories & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_autolink_references": close({data.github_repository_autolink_references & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_branches": close({data.github_repository_branches & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_custom_properties": close({data.github_repository_custom_properties & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_deploy_keys": close({data.github_repository_deploy_keys & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_deployment_branch_policies": close({data.github_repository_deployment_branch_policies & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_environment_deployment_policies": close({data.github_repository_environment_deployment_policies & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_environments": close({data.github_repository_environments & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_file": close({data.github_repository_file & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository": close({data.github_repository & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_milestone": close({data.github_repository_milestone & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_pages": close({data.github_repository_pages & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_pull_request": close({data.github_repository_pull_request & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_pull_requests": close({data.github_repository_pull_requests & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_teams": close({data.github_repository_teams & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_repository_webhooks": close({data.github_repository_webhooks & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_rest_api": close({data.github_rest_api & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_ssh_keys": close({data.github_ssh_keys & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_team": close({data.github_team & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_tree": close({data.github_tree & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_user_external_identity": close({data.github_user_external_identity & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_user": close({data.github_user & cuetf.MetaArgs})
	_#ds: "\(#githubPrefix)_users": close({data.github_users & cuetf.MetaArgs})

}
