package github

import (
	"github.com/roman-mazur/cuetf"
	"github.com/roman-mazur/cuetf/providers/github/res"
)

#Terraform: {
	#githubPrefix: string
	_#res: "\(#githubPrefix)_actions_environment_secret": close(res.github_actions_environment_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_environment_variable": close(res.github_actions_environment_variable & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_hosted_runner": close(res.github_actions_hosted_runner & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_oidc_subject_claim_customization_template": close(res.github_actions_organization_oidc_subject_claim_customization_template & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_permissions": close(res.github_actions_organization_permissions & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_secret": close(res.github_actions_organization_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_secret_repositories": close(res.github_actions_organization_secret_repositories & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_secret_repository": close(res.github_actions_organization_secret_repository & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_variable": close(res.github_actions_organization_variable & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_variable_repositories": close(res.github_actions_organization_variable_repositories & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_variable_repository": close(res.github_actions_organization_variable_repository & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_organization_workflow_permissions": close(res.github_actions_organization_workflow_permissions & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_repository_access_level": close(res.github_actions_repository_access_level & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_repository_oidc_subject_claim_customization_template": close(res.github_actions_repository_oidc_subject_claim_customization_template & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_repository_permissions": close(res.github_actions_repository_permissions & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_runner_group": close(res.github_actions_runner_group & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_secret": close(res.github_actions_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_actions_variable": close(res.github_actions_variable & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_app_installation_repositories": close(res.github_app_installation_repositories & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_app_installation_repository": close(res.github_app_installation_repository & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_branch_default": close(res.github_branch_default & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_branch": close(res.github_branch & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_branch_protection": close(res.github_branch_protection & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_branch_protection_v3": close(res.github_branch_protection_v3 & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_codespaces_organization_secret": close(res.github_codespaces_organization_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_codespaces_organization_secret_repositories": close(res.github_codespaces_organization_secret_repositories & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_codespaces_secret": close(res.github_codespaces_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_codespaces_user_secret": close(res.github_codespaces_user_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_dependabot_organization_secret": close(res.github_dependabot_organization_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_dependabot_organization_secret_repositories": close(res.github_dependabot_organization_secret_repositories & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_dependabot_organization_secret_repository": close(res.github_dependabot_organization_secret_repository & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_dependabot_secret": close(res.github_dependabot_secret & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_emu_group_mapping": close(res.github_emu_group_mapping & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_enterprise_actions_permissions": close(res.github_enterprise_actions_permissions & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_enterprise_actions_runner_group": close(res.github_enterprise_actions_runner_group & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_enterprise_actions_workflow_permissions": close(res.github_enterprise_actions_workflow_permissions & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_enterprise_ip_allow_list_entry": close(res.github_enterprise_ip_allow_list_entry & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_enterprise_organization": close(res.github_enterprise_organization & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_enterprise_security_analysis_settings": close(res.github_enterprise_security_analysis_settings & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_issue": close(res.github_issue & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_issue_label": close(res.github_issue_label & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_issue_labels": close(res.github_issue_labels & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_membership": close(res.github_membership & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_block": close(res.github_organization_block & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_custom_properties": close(res.github_organization_custom_properties & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_custom_role": close(res.github_organization_custom_role & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_project": close(res.github_organization_project & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_repository_role": close(res.github_organization_repository_role & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_role": close(res.github_organization_role & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_role_team_assignment": close(res.github_organization_role_team_assignment & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_role_team": close(res.github_organization_role_team & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_role_user": close(res.github_organization_role_user & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_ruleset": close(res.github_organization_ruleset & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_security_manager": close(res.github_organization_security_manager & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_settings": close(res.github_organization_settings & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_organization_webhook": close(res.github_organization_webhook & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_project_card": close(res.github_project_card & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_project_column": close(res.github_project_column & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_release": close(res.github_release & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_autolink_reference": close(res.github_repository_autolink_reference & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_collaborator": close(res.github_repository_collaborator & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_collaborators": close(res.github_repository_collaborators & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_custom_property": close(res.github_repository_custom_property & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_dependabot_security_updates": close(res.github_repository_dependabot_security_updates & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_deploy_key": close(res.github_repository_deploy_key & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_deployment_branch_policy": close(res.github_repository_deployment_branch_policy & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_environment_deployment_policy": close(res.github_repository_environment_deployment_policy & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_environment": close(res.github_repository_environment & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_file": close(res.github_repository_file & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository": close(res.github_repository & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_milestone": close(res.github_repository_milestone & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_pages": close(res.github_repository_pages & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_project": close(res.github_repository_project & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_pull_request": close(res.github_repository_pull_request & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_ruleset": close(res.github_repository_ruleset & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_tag_protection": close(res.github_repository_tag_protection & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_topics": close(res.github_repository_topics & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_vulnerability_alerts": close(res.github_repository_vulnerability_alerts & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_repository_webhook": close(res.github_repository_webhook & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_team": close(res.github_team & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_team_members": close(res.github_team_members & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_team_membership": close(res.github_team_membership & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_team_repository": close(res.github_team_repository & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_team_settings": close(res.github_team_settings & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_team_sync_group_mapping": close(res.github_team_sync_group_mapping & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_user_gpg_key": close(res.github_user_gpg_key & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_user_invitation_accepter": close(res.github_user_invitation_accepter & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_user_ssh_key": close(res.github_user_ssh_key & cuetf.MetaArgs)
	_#res: "\(#githubPrefix)_workflow_repository_permissions": close(res.github_workflow_repository_permissions & cuetf.MetaArgs)

}
