package euwest3

AvailabilityZones: [{
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-3"
	ZoneName:           "eu-west-3a"
	ZoneId:             "euw3-az1"
	GroupName:          "eu-west-3-zg-1"
	NetworkBorderGroup: "eu-west-3"
	ZoneType:           "availability-zone"
}, {
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-3"
	ZoneName:           "eu-west-3b"
	ZoneId:             "euw3-az2"
	GroupName:          "eu-west-3-zg-1"
	NetworkBorderGroup: "eu-west-3"
	ZoneType:           "availability-zone"
}, {
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-3"
	ZoneName:           "eu-west-3c"
	ZoneId:             "euw3-az3"
	GroupName:          "eu-west-3-zg-1"
	NetworkBorderGroup: "eu-west-3"
	ZoneType:           "availability-zone"
}]
