package res

#google_workload_identity_service_agent: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_workload_identity_service_agent")
	close({
		timeouts?: #timeouts
		id?:       string

		// The parent resource path.
		parent!: string

		// The list of ServiceAgents generated by the API call.
		service_agents?: [...close({
			container?:        string
			name?:             string
			principal?:        string
			role?:             string
			service_producer?: string
			state?:            string
		})]
	})

	#timeouts: close({
		create?: string
		delete?: string
	})
}
