package res

import "list"

google_ces_agent: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_ces_agent")
	close({
		after_agent_callbacks?: matchN(1, [#after_agent_callbacks, [...#after_agent_callbacks]])
		after_model_callbacks?: matchN(1, [#after_model_callbacks, [...#after_model_callbacks]])
		after_tool_callbacks?: matchN(1, [#after_tool_callbacks, [...#after_tool_callbacks]])
		before_agent_callbacks?: matchN(1, [#before_agent_callbacks, [...#before_agent_callbacks]])
		before_model_callbacks?: matchN(1, [#before_model_callbacks, [...#before_model_callbacks]])
		before_tool_callbacks?: matchN(1, [#before_tool_callbacks, [...#before_tool_callbacks]])
		llm_agent?: matchN(1, [#llm_agent, list.MaxItems(1) & [...#llm_agent]])
		model_settings?: matchN(1, [#model_settings, list.MaxItems(1) & [...#model_settings]])
		remote_a2a_agent?: matchN(1, [#remote_a2a_agent, list.MaxItems(1) & [...#remote_a2a_agent]])
		remote_dialogflow_agent?: matchN(1, [#remote_dialogflow_agent, list.MaxItems(1) & [...#remote_dialogflow_agent]])
		timeouts?: #timeouts
		toolsets?: matchN(1, [#toolsets, [...#toolsets]])
		transfer_rules?: matchN(1, [#transfer_rules, [...#transfer_rules]])

		// The ID to use for the agent, which will become the final component of
		// the agent's resource name. If not provided, a unique ID will be
		// automatically assigned for the agent.
		agent_id?: string

		// Resource ID segment making up resource 'name'. It identifies the resource
		// within its parent collection as described in https://google.aip.dev/122.
		app!: string

		// List of child agents in the agent tree.
		// Format: 'projects/{project}/locations/{location}/apps/{app}/agents/{agent}'
		child_agents?: [...string]

		// Timestamp when the agent was created.
		create_time?: string

		// Whether Terraform will be prevented from destroying the instance. Defaults to "DELETE".
		// When a 'terraform destroy' or 'terraform apply' would delete the instance,
		// the command will fail if this field is set to "PREVENT" in Terraform state.
		// When set to "ABANDON", the command will remove the resource from Terraform
		// management without updating or deleting the resource in the API.
		// When set to "DELETE", deleting the resource is allowed.
		deletion_policy?: string

		// Human-readable description of the agent.
		description?: string

		// Display name of the agent.
		display_name!: string

		// Etag used to ensure the object hasn't changed during a read-modify-write
		// operation. If the etag is empty, the update will overwrite any concurrent
		// changes.
		etag?: string

		// If the agent is generated by the LLM assistant, this field contains a
		// descriptive summary of the generation.
		generated_summary?: string

		// List of guardrails for the agent.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/guardrails/{guardrail}'
		guardrails?: [...string]
		id?: string

		// Instructions for the LLM model to guide the agent's behavior.
		instruction?: string

		// Resource ID segment making up resource 'name'. It identifies the resource
		// within its parent collection as described in https://google.aip.dev/122.
		location!: string

		// Identifier. The unique identifier of the agent.
		// Format: 'projects/{project}/locations/{location}/apps/{app}/agents/{agent}'
		name?: string

		// List of available tools for the agent.
		// Format: 'projects/{project}/locations/{location}/apps/{app}/tools/{tool}'
		tools?: [...string]
		project?: string

		// Timestamp when the agent was last updated.
		update_time?: string
	})

	#after_agent_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are ignored by the
		// agent.
		disabled?: bool

		// If enabled, the callback will also be executed on intermediate model
		// outputs. This setting only affects after model callback.
		// **ENABLE WITH CAUTION**. Typically after model callback only needs to be
		// executed after receiving all model responses. Enabling proactive execution
		// may have negative implication on the execution cost and latency, and
		// should only be enabled in rare situations.
		proactive_execution_enabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#after_model_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are ignored by the
		// agent.
		disabled?: bool

		// If enabled, the callback will also be executed on intermediate model
		// outputs. This setting only affects after model callback.
		// **ENABLE WITH CAUTION**. Typically after model callback only needs to be
		// executed after receiving all model responses. Enabling proactive execution
		// may have negative implication on the execution cost and latency, and
		// should only be enabled in rare situations.
		proactive_execution_enabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#after_tool_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are ignored by the
		// agent.
		disabled?: bool

		// If enabled, the callback will also be executed on intermediate model
		// outputs. This setting only affects after model callback.
		// **ENABLE WITH CAUTION**. Typically after model callback only needs to be
		// executed after receiving all model responses. Enabling proactive execution
		// may have negative implication on the execution cost and latency, and
		// should only be enabled in rare situations.
		proactive_execution_enabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#before_agent_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are ignored by the
		// agent.
		disabled?: bool

		// If enabled, the callback will also be executed on intermediate model
		// outputs. This setting only affects after model callback.
		// **ENABLE WITH CAUTION**. Typically after model callback only needs to be
		// executed after receiving all model responses. Enabling proactive execution
		// may have negative implication on the execution cost and latency, and
		// should only be enabled in rare situations.
		proactive_execution_enabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#before_model_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are ignored by the
		// agent.
		disabled?: bool

		// If enabled, the callback will also be executed on intermediate model
		// outputs. This setting only affects after model callback.
		// **ENABLE WITH CAUTION**. Typically after model callback only needs to be
		// executed after receiving all model responses. Enabling proactive execution
		// may have negative implication on the execution cost and latency, and
		// should only be enabled in rare situations.
		proactive_execution_enabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#before_tool_callbacks: close({
		// Human-readable description of the callback.
		description?: string

		// Whether the callback is disabled. Disabled callbacks are ignored by the
		// agent.
		disabled?: bool

		// If enabled, the callback will also be executed on intermediate model
		// outputs. This setting only affects after model callback.
		// **ENABLE WITH CAUTION**. Typically after model callback only needs to be
		// executed after receiving all model responses. Enabling proactive execution
		// may have negative implication on the execution cost and latency, and
		// should only be enabled in rare situations.
		proactive_execution_enabled?: bool

		// The python code to execute for the callback.
		python_code!: string
	})

	#llm_agent: close({})

	#model_settings: close({
		// The LLM model that the agent should use.
		// If not set, the agent will inherit the model from its parent agent.
		model?: string

		// If set, this temperature will be used for the LLM model. Temperature
		// controls the randomness of the model's responses. Lower temperatures
		// produce responses that are more predictable. Higher temperatures produce
		// responses that are more creative.
		temperature?: number
	})

	#remote_a2a_agent: close({
		a2a_config!: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config", list.MaxItems(1) & [_, ...] & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config"]])
	})

	#remote_dialogflow_agent: close({
		// The
		// [Dialogflow](https://cloud.google.com/dialogflow/cx/docs/concept/console-conversational-agents
		// agent resource name.
		// Format: 'projects/{project}/locations/{location}/agents/{agent}'
		agent!: string

		// The environment ID of the Dialogflow agent be used for the agent
		// execution. If not specified, the draft environment will be used.
		environment_id?: string

		// The flow ID of the flow in the Dialogflow agent.
		flow_id!: string

		// The mapping of the app variables names to the Dialogflow session
		// parameters names to be sent to the Dialogflow agent as input.
		input_variable_mapping?: [string]: string

		// The name of the variable that contains the language code to be used for
		// the Dialogflow session. If unspecified, the default language code of the
		// Dialogflow agent will be used.
		language_code_variable?: string

		// The mapping of the Dialogflow session parameters names to the app
		// variables names to be sent back to the CES agent after the Dialogflow
		// agent execution ends.
		output_variable_mapping?: [string]: string

		// Indicates whether to respect the message-level interruption settings
		// configured in the Dialogflow agent. * If false: all response messages from
		// the Dialogflow agent follow the app-level barge-in settings. * If true: only
		// response messages with
		// ['allow_playback_interruption'](https://docs.cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.dialogflow.cx.v3#text)
		// set to true will be interruptable, all other messages follow the app-level
		// barge-in settings.
		respect_response_interruption_settings?: bool
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})

	#toolsets: close({
		// The tools IDs to filter the toolset.
		tool_ids?: [...string]

		// The resource name of the toolset.
		// Format:
		// 'projects/{project}/locations/{location}/apps/{app}/toolsets/{toolset}'
		toolset!: string
	})

	#transfer_rules: close({
		deterministic_transfer?: matchN(1, [_#defs."/$defs/transfer_rules/$defs/deterministic_transfer", list.MaxItems(1) & [..._#defs."/$defs/transfer_rules/$defs/deterministic_transfer"]])
		disable_planner_transfer?: matchN(1, [_#defs."/$defs/transfer_rules/$defs/disable_planner_transfer", list.MaxItems(1) & [..._#defs."/$defs/transfer_rules/$defs/disable_planner_transfer"]])

		// The resource name of the child agent the rule applies to.
		// Format: 'projects/{project}/locations/{location}/apps/{app}/agents/{agent}'
		child_agent!: string

		// The direction of the transfer. Possible values: ["PARENT_TO_CHILD", "CHILD_TO_PARENT"]
		direction!: string
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config": close({
		agent_card?: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card", list.MaxItems(1) & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card"]])
		api_authentication?: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication", list.MaxItems(1) & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication"]])

		// Reference to the agent in the Agent Registry.
		// Format: 'projects/{project}/locations/{location}/agents/{agent}'
		agent_registry?: string

		// If not empty, interactions with the remote A2A agent will use this context
		// ID. This context_id field can refer to a session variable like
		// '$context.variables.order_agent_session_id'.
		context_id?: string

		// Mapping of input variable names of remote agent to GECX variable names.
		input_variable_mapping?: [string]: string

		// Mapping of output variable names of remote agent to GECX variable names.
		output_variable_mapping?: [string]: string

		// Whether streaming is enabled for the remote agent.
		streaming_enabled?: bool
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card": close({
		skills!: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card/$defs/skills", [_, ...] & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card/$defs/skills"]])
		supported_interfaces!: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card/$defs/supported_interfaces", [_, ...] & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card/$defs/supported_interfaces"]])

		// A description of the agent's domain of action/solution space.
		description!: string

		// A human-readable name for the agent.
		name!: string

		// The version of the agent.
		version!: string
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card/$defs/skills": close({
		// A detailed description of the skill.
		description!: string

		// Example prompts or scenarios that this skill can handle.
		examples?: [...string]

		// A unique identifier for the agent's skill.
		id!: string

		// The set of supported input media types for this skill, overriding the
		// agent's defaults.
		input_modes?: [...string]

		// A human-readable name for the skill.
		name!: string

		// The set of supported output media types for this skill, overriding the
		// agent's defaults.
		output_modes?: [...string]

		// A set of keywords describing the skill's capabilities.
		tags!: [...string]
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/agent_card/$defs/supported_interfaces": close({
		// The protocol binding supported at this URL. The core ones officially
		// supported are JSONRPC, GRPC and HTTP+JSON.
		protocol_binding!: string

		// The version of the A2A protocol this interface exposes.
		// Examples: "0.3", "1.0"
		protocol_version!: string

		// Tenant ID to be used in the request when calling the agent.
		tenant?: string

		// The URL where this interface is available. Must be a valid absolute HTTPS
		// URL in production.
		url!: string
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication": close({
		api_key_config?: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/api_key_config", list.MaxItems(1) & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/api_key_config"]])
		bearer_token_config?: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/bearer_token_config", list.MaxItems(1) & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/bearer_token_config"]])
		oauth_config?: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/oauth_config", list.MaxItems(1) & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/oauth_config"]])
		service_account_auth_config?: matchN(1, [_#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/service_account_auth_config", list.MaxItems(1) & [..._#defs."/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/service_account_auth_config"]])
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/api_key_config": close({
		// The name of the SecretManager secret version resource storing the API key.
		// Format: 'projects/{project}/secrets/{secret}/versions/{version}'
		// Note: You should grant 'roles/secretmanager.secretAccessor' role to the CES
		// service agent
		// 'service-@gcp-sa-ces.iam.gserviceaccount.com'.
		api_key_secret_version!: string

		// The parameter name or the header name of the API key.
		// E.g., If the API request is "https://example.com/act?X-Api-Key=", "X-Api-Key"
		// would be the parameter name.
		key_name!: string

		// Key location in the request.
		// Possible values:
		// HEADER
		// QUERY_STRING
		request_location!: string
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/bearer_token_config": close({
		// The bearer token.
		// Must be in the format '$context.variables.<name_of_variable>'.
		token!: string
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/oauth_config": close({
		// The client ID from the OAuth provider.
		client_id!: string

		// The name of the SecretManager secret version resource storing the
		// client secret.
		// Format: 'projects/{project}/secrets/{secret}/versions/{version}'
		//
		// Note: You should grant 'roles/secretmanager.secretAccessor' role to the CES
		// service agent
		// 'service-@gcp-sa-ces.iam.gserviceaccount.com'.
		client_secret_version!: string

		// OAuth grant types.
		// Possible values:
		// CLIENT_CREDENTIAL
		oauth_grant_type!: string

		// The OAuth scopes to grant.
		scopes?: [...string]

		// The token endpoint in the OAuth provider to exchange for an access token.
		token_endpoint!: string
	})

	_#defs: "/$defs/remote_a2a_agent/$defs/a2a_config/$defs/api_authentication/$defs/service_account_auth_config": close({
		// The OAuth scopes to grant. If not specified, the default scope
		// 'https://www.googleapis.com/auth/cloud-platform' is used.
		scopes?: [...string]

		// The email address of the service account used for authenticatation. CES
		// uses this service account to exchange an access token and the access token
		// is then sent in the 'Authorization' header of the request.
		//
		// The service account must have the
		// 'roles/iam.serviceAccountTokenCreator' role granted to the
		// CES service agent
		// 'service-@gcp-sa-ces.iam.gserviceaccount.com'.
		service_account!: string
	})

	_#defs: "/$defs/transfer_rules/$defs/deterministic_transfer": close({
		expression_condition?: matchN(1, [_#defs."/$defs/transfer_rules/$defs/deterministic_transfer/$defs/expression_condition", list.MaxItems(1) & [..._#defs."/$defs/transfer_rules/$defs/deterministic_transfer/$defs/expression_condition"]])
		python_code_condition?: matchN(1, [_#defs."/$defs/transfer_rules/$defs/deterministic_transfer/$defs/python_code_condition", list.MaxItems(1) & [..._#defs."/$defs/transfer_rules/$defs/deterministic_transfer/$defs/python_code_condition"]])
	})

	_#defs: "/$defs/transfer_rules/$defs/deterministic_transfer/$defs/expression_condition": close({
		// The string representation of cloud.api.Expression condition.
		expression!: string
	})

	_#defs: "/$defs/transfer_rules/$defs/deterministic_transfer/$defs/python_code_condition": close({
		// The python code to execute. The function must be named
		// 'should_trigger_transfer_callback'.
		python_code!: string
	})

	_#defs: "/$defs/transfer_rules/$defs/disable_planner_transfer": close({
		expression_condition!: matchN(1, [_#defs."/$defs/transfer_rules/$defs/disable_planner_transfer/$defs/expression_condition", list.MaxItems(1) & [_, ...] & [..._#defs."/$defs/transfer_rules/$defs/disable_planner_transfer/$defs/expression_condition"]])
	})

	_#defs: "/$defs/transfer_rules/$defs/disable_planner_transfer/$defs/expression_condition": close({
		// The string representation of cloud.api.Expression condition.
		expression!: string
	})
}
