package res

import "list"

google_monitoring_snooze: {
	@jsonschema(schema="https://json-schema.org/draft/2020-12/schema")
	@jsonschema(id="https://github.com/roman-mazur/cuetf/schema/res/google_monitoring_snooze")
	close({
		criteria!: matchN(1, [#criteria, list.MaxItems(1) & [_, ...] & [...#criteria]])
		interval!: matchN(1, [#interval, list.MaxItems(1) & [_, ...] & [...#interval]])
		timeouts?: #timeouts

		// A display name for the Snooze. This can be, at most, 512 unicode characters.
		display_name!: string
		id?:           string

		// Identifier. The name of the Snooze. The format is:
		// projects/[PROJECT_ID_OR_NUMBER]/snoozes/[SNOOZE_ID]
		// The ID of the Snooze will be generated by the system.
		name?:    string
		project?: string
	})

	#criteria: close({
		// When you define a snooze, you can also define a filter for that snooze.
		// The filter is a string containing one or more key-value pairs. The string
		// uses the standard https://google.aip.dev/160 filter syntax. If you define
		// a filter for a snooze, then the snooze can only apply to one alert policy.
		// When the snooze is active, incidents won't be created when the incident
		// would have key-value pairs (labels) that match those specified by the
		// filter in the snooze.
		//
		// Snooze filters support resource, metric, and metadata labels. If multiple
		// labels are used, then they must be connected with an AND operator. For
		// example, the following filter applies the snooze to incidents that have a
		// resource label with an instance ID of 1234567890, a metric label with an
		// instance name of test_group, a metadata user label with a key of foo and a
		// value of bar, and a metadata system label with a key of region and a value
		// of us-central1:
		//
		// "filter": "resource.labels.instance_id=\"1234567890\" AND
		// metric.labels.instance_name=\"test_group\" AND
		// metadata.user_labels.foo=\"bar\" AND
		// metadata.system_labels.region=\"us-central1\""
		filter?: string

		// The specific AlertPolicy names for the alert that should be snoozed.
		// The format is: projects/[PROJECT_ID_OR_NUMBER]/alertPolicies/[POLICY_ID]
		// There is a limit of 16 policies per snooze. This limit is checked during
		// snooze creation. Exactly 1 alert policy is required if filter is specified
		// at the same time.
		policies?: [...string]
	})

	#interval: close({
		// The end of the time interval.
		// A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and
		// up to nine fractional digits. Examples: "2014-10-02T15:01:23Z" and
		// "2014-10-02T15:01:23.045123456Z".
		end_time!: string

		// The beginning of the time interval. The default value for the start time
		// is the end time. The start time must not be later than the end time.
		// A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and
		// up to nine fractional digits. Examples: "2014-10-02T15:01:23Z" and
		// "2014-10-02T15:01:23.045123456Z".
		start_time?: string
	})

	#timeouts: close({
		create?: string
		delete?: string
		update?: string
	})
}
