package euwest2

AvailabilityZones: [{
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-2"
	ZoneName:           "eu-west-2a"
	ZoneId:             "euw2-az2"
	GroupName:          "eu-west-2"
	NetworkBorderGroup: "eu-west-2"
	ZoneType:           "availability-zone"
}, {
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-2"
	ZoneName:           "eu-west-2b"
	ZoneId:             "euw2-az3"
	GroupName:          "eu-west-2"
	NetworkBorderGroup: "eu-west-2"
	ZoneType:           "availability-zone"
}, {
	State:       "available"
	OptInStatus: "opt-in-not-required"
	Messages: []
	RegionName:         "eu-west-2"
	ZoneName:           "eu-west-2c"
	ZoneId:             "euw2-az1"
	GroupName:          "eu-west-2"
	NetworkBorderGroup: "eu-west-2"
	ZoneType:           "availability-zone"
}]
