name: analysis
"on": workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GENERATOR_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4
      - name: Set up CUE
        run: go install cuelang.org/go/cmd/cue
      - name: Execute
        run: go generate ./internal/analysis
