name: metadata
"on":
  schedule:
    - cron: 35 * * * *
jobs:
  aws:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.METADATA_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.METADATA_AWS_ACCESS_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GENERATOR_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Set up CUE
        run: go install cuelang.org/go/cmd/cue
      - name: Execute
        run: |-
          git config user.name "cuetf generator (bot)"
          git config user.email "cuetf-bot@rmazur.io"
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout "origin/$branch"

          cd aws && ./import.sh

          if [ $(git status --porcelain | wc -l) -gt 0 ]; then
          		git add .
          		git commit -m "aws: update metadata"
          		git push origin HEAD:"$branch"
          fi
