name: test
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.5
      - name: Set up CUE
        run: go install cuelang.org/go/cmd/cue@v0.10.0
      - name: Test
        run: go test ./...
